### ISSUE TITLE
Spec `handler` signature

### ISSUE THREAD

**Issue by Acentelles** [anoma/juvix#1006]
What's the expected signature of `handler`?

```
handler printer =
  let print = printLn
  let pure x = toString x
end
```

The current state of the compiler currently complains on its pass to `toHR` with the following error
```
"Error on toHR: Signature required for definition "Prelude" :|
    [ "Handler"
    , "foo"
    ] because type inference is not yet implemented"
```

**Comment by cyberglot** [comment]
We need to add the CPS conversion to the pipeline.

**Comment by Acentelles** [comment]
The question is on "Does `handler` need a signature, as the error says?"

I guess it doesn't, but would like to confirm

**Comment by Acentelles** [comment]
Closing because the question doesn't make much sense

**Comment by cyberglot** [comment]
It should have a regular function signature for now, before effect types.
