### ISSUE TITLE
Effects signature

### ISSUE THREAD

**Issue by Acentelles** [anoma/juvix#1007]
The signature of an effectful function needs to reflect those effects. In this case, what would be the signature of `prog`?

```
let prog a =
  print a;
  pure a

let foo = prog via printer
```

**Comment by cyberglot** [comment]
```
sig prog : string -> string
sig foo  : string
```

We need effect types to reflect what's going on with handlers.

**Comment by Acentelles** [comment]
How would that signature _ideally_ look like?

**Comment by cyberglot** [comment]
There are many ways to type effects, all with its own pros and cons.

Ideally something with box/modalities (as in [Contextual Modal Types for Algebraic Effects and Handlers](https://software.imdea.org/~aleks/icfp21/icfp21.pdf)) that also reflects effect rows/row polymorphism (as usually implemented in languages with effect handlers, like Links, Koka, etc). However, I don't know what would be feasible for Juvix atm.

**Comment by Acentelles** [comment]
Could you summarise your proposal/s with their pros and cons?

**Comment by mariari** [comment]
There are quite a few number of ways we can deal with this. We are constrained by being able to have multiple effects at once, and thus we can't use F*'s technique

1. Have effects be on the left hand side as arguments

```ocaml
sig prog (printer eff) (db eff) = string -> eff string
```

2. have named arguments on the left hand side (note I like this one a lot as it gives us places to extend sigantures further)
```ocaml
sig prog :effs [printer m, db m]
         :usage 2
         :interfaces [showable c] =
  string -> m string
```
  - Note that the `:usage` and `interfaces` are irrelevent here
3. Mix 1 and 2, with effects being implicit but other details being named arguments

```ocaml
sig prog (printer m) (db m) :usage 2 :interfaces [showable c] = 
  string -> m string
```

Note I am using `=` for sig to reflect the new syntax, but these proposals also could work for the current syntax

```ocaml
sig prog (printer eff) (db eff) : string -> eff string
sig prog :effs [printer eff, db eff]
         :usage 2
         :interfaces [showable c] :
  string -> eff string 

sig prog (printer m) (db m) :usage 2 :interfaces [showable c] :
  string -> m string
```

**Comment by cyberglot** [comment]
I like the syntax of 
```
sig prog :effects <printer, db | e >
         :usage 2
         :interfaces <showable a> :
    a -> string -> string
```
`e` means effect/row polymorphism, meaning that we can have other effects happening as well (it is important for function composition). row types can also be used for records.

```
sig prog :usage 2
         :interfaces <showable a> :
    <id: Int, access: Bool | r> -> Bool
```
here we take a record with fields `id` and `access` and the `r` meaning row polymorphism where the record can have more fields.

---

In terms of effect typing, row polymorphism is good to signify that a effect **can** happen, but nothing more. It's the least we can do to show that effects have happened. However, it doesn't give any more useful information about effects even though we know they are algebraic (ie, we have an equational theory that describes the effect but it's a bit more tricky as said theories in terms of handlers, not effect interfaces). Good thing about it is that it should be easier to implement than most other solutions.

The version with modalities would require a significant effort to implement but it would also mean that we would be able to guarantee that effects follow algebraic laws, and that info would be really nice to have for optimisation, correctness, etc. However, I see two major cons with this approach: would probably require a significant revisit of Juvix's type theory and I don't know if Witch would really benefit from it. General effects would definitely benefit from it, but Witch's effects are most declarative/ of limited scope.

We can alternatively use something like Liquid Haskell's Proof-by-Logic-Evaluation where we can also prove some algebraic laws. I belive Liquid Haskell's approach is significantly weaker that modalities for that, but it still comes with its own implementation effort.

I belive we should survey (ie, an actual survey explaining pros and cons in a more detailed fashion where implementation effort is somewhat measured) our options and to make an educated choice.
