### ISSUE TITLE
Witch Metaprogramming Spec

### ISSUE THREAD

**Issue by cyberglot** [anoma/juvix#1010]
Status: draft

---

# Witch Metaprograming Spec
#algeff #witch #juvix

## Goals
>  Dependent type theory is also flexible enough to serve as its own metaprogramming language, that is, a language in which one can write programs that assist in the construction and manipulation of terms in dependent type theory itself -- Ebner et al, 2017 in reference to Christiansen and Brady, 2016.

The metaprogramming layer makes it possible for Juvix users to have programatic access to typechecking, and hand-craft their own proof strategies. It will let Juvix users create not only generic proof automation, but also proof automation for recurring properties in their code that would otherwise require code duplication. Specific proof automation is a feature made possible by the use of algebraic effect and handlers that let users instanciate generic strategies into more simple ones via handler composition.

--> An example of "strategy instanciation" would be nice to have here.

### Codebase additions

*What parts of the codebase it touches?*
The metaprogramming layer creates an API for using Juvix Core to programatically apply Juvix's type theory to programs written in Juvix. Therefore, the metaprogramming layer touches mainly Core and the Standard Library.

*What are its inputs and outputs?*
The metaprogramming layer receives as an input a typechecked Juvix Core program and outputs either:
 - tychecking is complete, 
	 + no holes left and no type errors.
 - typechecking is complete,
	 + holes left, but no type errors.
 - typechecking is not complete,
	 +	holes may be left, type errors occur.

In the first case, the user is done creating a new proof strategy or creating a new proof. All proofs can be erased now.

*Any library/rewrite/improvement **must** take place for this addition to be implemented?*

*Any library/rewrite/improvement would be **nice to have**?*

## Glossary
- **proof strategy** Witch comprises 3 different ways to create a proof automation procedures, we call them "proof strategies". In other dependently-typed languages, they use the term "tactic". For Juvix, we prefer naming it "proof strategy" and using the term "tactic" for strategies that take a step towards the goal (it may or may not reach the goal). Other proof strategies are solver and proof search. The reason for such thin conceptual slicing is the underlying efffects that take place for each of strategy: 
	+ solvers depend on IO (eg, integration with z3);
	+ proof search depend on prolog-style non-deterministic search;
	+ tactics may be pure.

**Comment by cyberglot** [comment]
I have just realised that we don't have reflection yet. I remember talking to @andy-morris about it and our quick-and-dirty solution for the last release was to just make the AST available. However, I believe a proper solution should come with this spec. Thoughts, @andy-morris @Acentelles @rokopt ?

**Comment by rokopt** [comment]
I will have to read this deeper and ask some questions to understand whether this is sensible, but the first thing that comes to my mind is that I think that it would work well with what I'm doing to provide S-expressions as a built-in type, the way that products and coproducts currently are, allowing Juvix code to use them.  With specific atoms and constraints, such a type could perhaps be used to reflect the Juvix AST.  Is that the sort of thing that might be useful here?

**Comment by cyberglot** [comment]
@rokopt I think the S-exp built-in type would be fantastic but given the references I'm investigating, we'd want a smaller Core rather than a full AST. I will report back in time.

**Comment by Acentelles** [comment]
Shall we close this in favor of https://hackmd.io/V5Ct5wg-SVyaBOtdV7P34g? @cyberglot

**Comment by cyberglot** [comment]
The idea of the prototype is to finish this one up, so I don't know what to do.
