### ISSUE TITLE
Backend: Representation coming in.

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#1011]
### Preamble

Currently the backends get the type `Juvix.Core.Erased.Ann.Types.Term` when trying to compile. This type, while nice for the type checker, is not so friendly to the backends. This is because the representation is optimized for type checking and naguht else.

Further, the tragedy sets in when we realize that instead of getting a list of these terms to compile against some name, that we just get the `Term` directly with no ceremony surrounding it. This puts heavy constraint not only on the `Backend` but `Core` as well, as they have to inline all forms for us to effectively compile against.

#### The Environment

Thus I propose the following.

Instead of taking a  `Juvix.Core.Erased.Ann.Types.Term` we take.

```haskell
data NameOrExpression = Name NameSymbol.T | Expression Compile.Term.T

data Processing = List.T NameOrExpression
```

Namely, we want to either take the expression to evaluate if it's a throw away expression, or a `Name` the `NameSymbol.T` represents the location in the surrounding environment it belongs (this is simply an indirection pointer to know what to compile against).

```haskell
data Environment = {
  context :: Context.t Sexp.t
}
```

Here I give the `Context.t` type as the name to lookup against but we could always use
```haskell
data Environment = {
  context :: RawGlobal
}
```

that `Core` already maintains, if we don't want to manually convert these.

An actual `Context.t` would allow us to commit back compiled code into the structure itself so we can reuse it for jitting purposes, but this can be extended at a later date once we have this structure up.

#### Terms

While the above suggestion is great, it lacks substance in regards to the criticisms levied at `Core.Ann.Term`.

Thus If we look at the type core looks over we can note a few details.

```haskell
data Term primTy primVal
  = Var NameSymbol.T
  | Prim primVal
  | LamM
      { capture :: [NameSymbol.T], -- Capture
        arguments :: [NameSymbol.T], -- Arguments
        -- the Term in AnnTerm is not lam!
        body :: AnnTerm primTy primVal
      }
  | PairM (AnnTerm primTy primVal) (AnnTerm primTy primVal)
  | CatProductIntroM (AnnTerm primTy primVal) (AnnTerm primTy primVal)
  | CatProductElimLeftM (AnnTerm primTy primVal) (AnnTerm primTy primVal)
  | CatProductElimRightM (AnnTerm primTy primVal) (AnnTerm primTy primVal)
  | CatCoproductIntroLeftM (AnnTerm primTy primVal)
  | CatCoproductIntroRightM (AnnTerm primTy primVal)
  | CatCoproductElimM
      (AnnTerm primTy primVal)
      (AnnTerm primTy primVal)
      (AnnTerm primTy primVal)
      (AnnTerm primTy primVal)
      (AnnTerm primTy primVal)
  | UnitM
  | AppM (AnnTerm primTy primVal) [AnnTerm primTy primVal]
  deriving (Show, Read, Eq, Generic)

data Type primTy
  = SymT NameSymbol.T
  | Star Universe
  | PrimTy primTy
  | -- TODO: How to deal with dependency?
    Pi Usage.T (Type primTy) (Type primTy)
  | Sig Usage.T (Type primTy) (Type primTy)
  | CatProduct (Type primTy) (Type primTy)
  | CatCoproduct (Type primTy) (Type primTy)
  | UnitTy
  deriving (Show, Read, Eq, Generic)

data AnnTerm primTy primVal = Ann
  { usage :: Usage.T,
    type' :: Type primTy,
    term :: Term primTy primVal
  }
  deriving (Show, Read, Eq, Generic)
```

Namely that  `CatProduct*` doesn't have a very obvious representation in a backend (some may be able to lambda encode, but that is quite a slow strategy and more confusing to introsepct!).

Further by this point, having an explicit `Let` to replace the `(Lambda ....) Term` would also create an easier to introspect backend.

Thus I propose a very rough term representation similar to

```haskell
Data Expression 
  = Lambda 
  | Application
  | Variable
  | Case Case
  | Let Bind Expression 
  | Literal Literal
  -- We may have to coerce to fulfill certain typing constraints placed upon us by the backends
  | Coerce
  | Note
  -- Type is just another expression/term! We want a representation
  | Type

data Bind =  {
  -- Should we introduce the name into the scope of the body?
  recrusive :: Bool,
  contents :: Expression
}
data Case = {
  term :: Expression,
  -- either an anon record type or a name referencing what type it corresponds to.
  type :: NameSymbol.T | Record,
  matches [Alt]
}

data Alt = {
  con :: AltCon
  bindings :: [Symbol.T],
  body :: Expression,
}

data AltCon = Con NameSymbol.t | Lit Literal | Default
```

This code is heavily inpsired from:
- https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/core-syn-type

Thus the given example is not ideal. I suspect over time we will need to add more support for the `LISPY` and dependetly typed elements of the lanugage.

Furhter I think we should break `Lambda` down into
- Closure
  - This talks about Allocations and Captures 
- Block
  - This allows us to note that the current form is recursive by setting the block
- Body
  - The body of the code that we generate for.  

## Links
- https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/core-syn-type
- https://dev.realworldocaml.org/compiler-backend.html

**Comment by Acentelles** [comment]
> Instead of taking a form we take.

Almost everything is a form, can you specify?

I can't fully understand this proposal, apart from the value of converting lambdas to `Let` to reduce the work the compiler will do otherwise. Can you share other forms that the backend/s will benefit from modifying? Can these changes be generalised to all backends?

I can't see how the `Environment` works either.

**Comment by systemf-frank** [comment]
> The CatProduct* gets translated into a case for Elims, and normal function calls for introductions.

Wouldn't that take away the possibility of defining the types in terms of first-class types in the backend (for example structs)?

> The Environment will host the LLVM version of the function name, for when we wish to link foo back into the code. Currently since we take only a Term we have to inline foo in some fashion, meaning that instead of seeing clean generated code, we get a large main function which is hard to understand and debug.

Wouldn't that mean that core and the backend get more intertwined? Why would core force an environment type for the backend?

**Comment by mariari** [comment]
> > The CatProduct* gets translated into a case for Elims, and normal function calls for introductions.
> 
> Wouldn't that take away the possibility of defining the types in terms of first-class types in the backend (for example structs)?

No, as the function in this case, would be a struct construction. For plain `CatProducts*` that deal with Product types, we could just generate lookup functions from the field names which really just call `GEP`.



> 
> > The Environment will host the LLVM version of the function name, for when we wish to link foo back into the code. Currently since we take only a Term we have to inline foo in some fashion, meaning that instead of seeing clean generated code, we get a large main function which is hard to understand and debug.
> 
> Wouldn't that mean that core and the backend get more intertwined? Why would core force an environment type for the backend?


Not really, as you need a consistent environment for code to live in. For example if we have incremental computation/development, when we pass some code down to `LLVM`, we may see the function again further on. Meaning that LLVM would have to maintain a lookup table between invocations that has the same semantics as what the frontend language has. At which point we'd be reimplementing the entirety of `Context` data type within LLVM. If we reuse the `Context` type we have now, we can store information in there that relates to `LLVM` data in the `Context` and thus do a lookup there to find out what `f` refers to and even the proper function name we've even compiled in LLVM along with type checking meta data if things go wrong.

Even if we don't want to support incremental computation, when we make changes to the pipeline to be more friendly to core, core will get a few function declarations at a time, meaning this kind of infrastructure is needed somewhere.
