### ISSUE TITLE
Inspiration from other smart contracting languages

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#121]
We should investigate other smart contracting languages and see how well quality of life features fit into Juvix and how we improve them.

Below is a list of smart contracting languages that we should look at, feel free to suggest more.

### List
1. [Alacris](https://github.com/AlacrisIO/alacrity)
2. [Ink](https://github.com/paritytech/ink)
3. [Solana](https://github.com/solana-labs/solana)

**Comment by cwgoes** [comment]
[RedPRL language reference](https://www.redprl.org/en/latest/language.html).

**Comment by thealmarty** [comment]
[F*](https://www.fstar-lang.org/#tutorial) and [low*](https://fstarlang.github.io/lowstar/html/), especially how F* uses its effect system [to detect vulnerabilities](https://www.cs.umd.edu/~aseem/solidetherplas.pdf) (thanks @A-Manning )

**Comment by cwgoes** [comment]
@mariari Solana is a blockchain, not a contract language. Is there an associated language? AFAIK they use(d) [Berkeley Packet Filter](https://en.wikipedia.org/wiki/Berkeley_Packet_Filter) as a VM, which can be targeted [with Rust](https://github.com/solana-labs/example-tictactoe/blob/master/program-bpf-rust/src/game.rs) - potentially we could target this with Juvix in the future.

As far as I can tell, Ink is just an alteration of Rust & targets WASM.

I can't find any comprehensive theory documentation for Alacris, but based on [the example](https://github.com/AlacrisIO/alacrity/blob/master/examples/rps-auto/rps/rps.canReach.ala) and [this slide deck](https://alacrisio.github.io/lavbda/) it seems like it's more a DSL which uses various techniques, then outputs either JavaScript or Solidity.

**Comment by cwgoes** [comment]
[Pact](https://medium.com/kadena-io/pact-formal-verification-for-blockchain-smart-contracts-done-right-889058bd8c3f) is also a possible source of inspiration.
