### ISSUE TITLE
Investigate proof systems that are more user-friendly

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#124]
See this [paper](http://strictlypositive.org/obseqnow.pdf) about observational equality. I haven't read it yet but it seems to be better than the intensional equality we have. 

I'll update here as I gain more understanding of this.

**Comment by andy-morris** [comment]
Yes! I think this would be great to have.

**Comment by andy-morris** [comment]
btw we can probably skip the separate `Prop` universe and just have zero-usage stuff in its place, right?

**Comment by thealmarty** [comment]
Also we can look into [other types of equality](https://ncatlab.org/nlab/show/equality) that would allow us to decrease the need to prove trivial facts.

**Comment by thealmarty** [comment]
Consolidated from #14 : 
- from @cwgoes : 
  Note: allow 1-step beta reduction equality as separate from NF-beta reduction equality, it will make the proofs more explicit (optionally).
- [Type-Theory In Color](https://dl.acm.org/citation.cfm?id=2500577) ([Research Gate Copy](https://www.researchgate.net/publication/266654430_Type-Theory_in_Color))

**Comment by thealmarty** [comment]
Also, check out Epigram 2, which supports function extensionality. See the paper with Haskell code (being updated atm, couldn't find the updated copy) [*An Epigram Implementation*](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.188.5704&rep=rep1&type=pdf) and the [talk](https://vimeo.com/428161108) by Conor McBride.

**Comment by thealmarty** [comment]
Also, check out these [talks](http://math.andrej.com/category/talks/) about various proof assistants and systems.

**Comment by thealmarty** [comment]
@cyberglot mentioned [The Marriage of Univalence and Parametricity](https://arxiv.org/abs/1909.05027) which allows users to transparently transfer definitions and theorems for a type to an equivalent one, as if they were equal. There's proof that it's not very hard to implement - they've implemented it in Coq.

**Comment by atennapel** [comment]
Note on `Prop`: https://github.com/AndrasKovacs/setoidtt/issues/1 , zero-usage does not subsume `Prop` as zero-usage is on a binder while `Prop` is more general. Any `t : Prop` can be erased.

**Comment by cwgoes** [comment]
Superseded by more recent issues by @cyberglot
