### ISSUE TITLE
Recognising unused functions should be done earlier in the pipeline

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1383]
As discussed with @janmasrovira, we should recognise unused functions and avoid compiling them earlier in the pipeline, by doing DFS on the graph of function dependencies, checking for reachability.

Currently, unused functions are recognised by having a polymorphic type after monomorphisation. This will no longer work after removing MonoJuvix, and checking reachability is a more direct and general solution.

**Comment by janmasrovira** [comment]
This can be done right after scoping. It should work for inductive types and axioms as well.

I consider a couple of options:
1. Have it as part of the translation to abstract.
2. New step in the pipeline. Between scoping and abstract.

I remeber that @paulcadman is working on an interface to specify which functions should be exported (i.e. keep the original name) in the wasm file. We should take into account that too.
