### ISSUE TITLE
Replace `FilePath` by `OsPath`

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#1390]
We are currently using the library [`filepath-1.4.2.2`](https://www.stackage.org/nightly-2022-07-16/package/filepath-1.4.2.2). In this version, the library offers its API for the type [`Filepath`](https://www.stackage.org/haddock/nightly-2022-07-16/base-4.16.2.0/src/GHC-IO.html#FilePath):
```
type FilePath = String
```
We are all aware of the problems of using `String` in haskell.

Recently, a newer version of the library, [`filepath-1.4.100.0`](https://hackage.haskell.org/package/filepath-1.4.100.0), introduces a new type, called `OsPath` for encoding file paths in a more efficient and safe way. One can read the benefits of it in the [documentation of the library](https://hackage.haskell.org/package/filepath-1.4.100.0/docs/System-OsPath.html).

I think we should refactor all uses of `FilePath` by `OsPath`.

**Comment by janmasrovira** [comment]
Adding the `filepath-1.4.100.0` dependency causes dependency conflicts with other dependencies. I'll freeze this issue until `filepath-1.4.100.0` is part of a stackage nightly

**Comment by lukaszcz** [comment]
We're using the path library.
