### ISSUE TITLE
Discuss documentation structure

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#1394]
We should discuss how we want to structure the documentation. 

This website contains some guidelines in that regard. 
https://diataxis.fr/

**Comment by jonaprieto** [comment]
We need a better structure/hierarchy for sections in the REAMDE but also in the whole Juvix Book. We want to rethink the adequacy of certain contents that suggests removing/moving parts from the current documentation to different places depending on their relevancy. Important questions for every section are What is the real purpose for this? does it fit in some previous hierarchy or should create a new one? is the content/example self-contained?

**Comment by janmasrovira** [comment]
We unanimously agreed to follow all the guidelines in https://diataxis.fr
