### ISSUE TITLE
 Support Wasm import and exported symbol names in C backend

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1419]
### Background

See #1355 

To support compilation of WASM binaries that can be executed in Anoma we need to be able to choose names for symbols we generate in the C backend.

Specifically Anoma expects validity predicates to have a particular name and signature in the binary WASM file, this is visible in the Anoma source as: https://github.com/anoma/anoma/blob/5831077bf1f1ff917f97264471b0ddcae224e739/macros/src/lib.rs#L75

This feature is also required to support our example web application https://github.com/anoma/juvix/issues/1352.

### How to export a name 

To export a symbol it should be in scope in the entry point module at compilation time.

Any function with a name consisting only of alpha numeric plus `_` characters will be exported.

### How to import a name 

Any axiom without a compile block with a name consisting only of alpha numeric plus `_` characters will be marked as imported.

### Code generation

The compiler can use the `exports` map from the configuration to name the corresponding symbols in the WASM binary. We can do this with the [`export_name` attribute](https://clang.llvm.org/docs/AttributeReference.html#export-name), and [`import_name` attribute](https://clang.llvm.org/docs/AttributeReference.html#import-name)

The `export_name` attribute sets the name for the exported symbol and ensures that the symbol is exported in the binary:

```c
__attribute__((export_name("exportedName1")))
int juvixName1_1234(int fa0)
```

The `import_name` attribute adds a function and signature to the import table of the Wasm binary.

```c
__attribute__((import_name("importedName1")))
int juvixName1_1234(int fa0)
```

**Comment by janmasrovira** [comment]
I think what you suggest is reasonable

**Comment by paulcadman** [comment]
I changed the issue to remove yaml configuration since we will export / import all symbols with alpha numeric names, this is sufficient for now.

**Comment by paulcadman** [comment]
This was implemented in https://github.com/anoma/juvix/pull/1425, https://github.com/anoma/juvix/pull/1426 and https://github.com/anoma/juvix/pull/1449
