### ISSUE TITLE
Notes on Monoid-Indexed Monads ("Minads")

### ISSUE THREAD

**Issue by A-Manning** [anoma/juvix#144]
As we know from Mac Lane, "A monad is just a monoid in the category of endofunctors".
It's a well known result that for any two monoids `(A, 0_A, •_A)`, `(B, 0_B, •_B)`, the triple 
`(A × B, 0_A × 0_B, •_A × •_B)` is also a monoid (up to isomorphism).

Thus note that we can pair any monad with any monoid, and obtain a pair that is also a monoid (and a monad).

```
instance Monad m, Monoid μ => Monad (m a, μ) where
  return x = return x, mzero
  (mx, y) >>= f =
     let (my, z) = mx >>= f in
     (my, y <> z)
```

This is fairly unremarkable in a language without dependent types. However, with dependent types, we can make the second element of the product type instead a type-level argument, obtaining a type that looks like

```
type monoid: Type
val mzero: monoid
val ( <> ): monoid -> monoid -> monoid

type minad: Type -> monoid -> Type
val return: a -> minad a mzero
val ( >=> ): (a -> minad b x) -> (b -> minad c y) -> a -> minad c (x <> y)
```

Various monoids are quite interesting as indices for the trivial monad.
The booleans under `&&` can represent composure of erasability, invertability, purity, or safe totality;
The booleans under `||` can represent erasure, functions with exceptional cases, and divergence; 
The naturals under addition give Danielsson's minad for abstract resource consumption;
The naturals under multiplication give the upper bound of the cardinality of the codomain;
Lists under `++` can model sequential effects;
Sets under union can model non-sequential effects;
Maps with monoids as values under `unionWith (<>)` can encapsulate both sequential and non-sequential effects with arbitrary monoids that model the composition of those individual effects.

Of course there are specific monads that benefit also from being promoted to minads with specific monoidal indices - for example, the list monad can be indexed with the naturals under multiplication, by which we obtain the vectors. 

As a corollary to maps, a single trivial monad indexed with a map of monoidal effects would suffice to model any number of effects, with painless composition. Alternatively a product of a set and a list could be employed. So long as these monoidal components normalize well through composition, this could constitute a relatively pleasant effects mechanism.

**Comment by cwgoes** [comment]
According to @mariari better ideas have been since had
