### ISSUE TITLE
Create a ready-to-use emacs configuration for juvix

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#1444]

**Comment by janmasrovira** [comment]
I think we can close this issue or mark it as `wont-fix`.
The original purpose of this issue was to provide a plug and play environment for people in the first Juvix workshop. However I don't think this is longer needed because:
1. If a user prefers emacs over vscode, they are probably experienced enough to follow the simple instructions to setup the juvix-mode for emacs.
2. If a user is not experienced enough to follow those instructions, then they'll probably prefer to use vscode.
If you agree with this reasoning, we should cose this issue.

**Comment by paulcadman** [comment]
I agree we should close this.
