### ISSUE TITLE
Typechecking of incorrect polymorphic self-application generates wrong error message

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1455]
Typechecking
```agda
module identity;

id : {A : Type} -> A -> A;
id a := a;

id' : {A : Type} -> A -> A;
id' {A} := id {(A -> A) -> A -> A} id;

end;
```
results in
```
The expression id {(A → A) → A → A} (id {_}) has type:
  A → A
but is expected to have type:
  A
```
Unless I misunderstood the syntax, this is wrong. The body of `id'` is `id id` and it should have type `A -> A`.

The type of the first `id` is `((A -> A) -> A -> A) -> (A -> A) -> A -> A` and the type of `id id` is `(A -> A) -> A -> A`. So the program is correctly rejected, but with a wrong error message.

**Comment by janmasrovira** [comment]
This is a bug and is most likely caused by how substitution is done. We'll need to investigate how to fix it
