### ISSUE TITLE
VSCode syntax highlighting uses different colors within the same token

### ISSUE THREAD

**Issue by rokopt** [anoma/juvix#1464]
The attached screenshot shows example code which induces the Juvix VSCode extension to use different colors for different parts of some of the same words.

**Comment by rokopt** [comment]
![Screenshot from 2022-08-20 02-40-26](https://user-images.githubusercontent.com/17652016/185740265-fb716eec-2750-4fd4-847b-2685b1339ca8.png)

**Comment by jonaprieto** [comment]
Thanks for reporting this. Can you please also post the code here @rokopt? to reproduce this issue.

**Comment by jonaprieto** [comment]
We decided to throw an error if any tab character is detected while parsing the file.
