### ISSUE TITLE
Provide statically linked release binaries for Linux x86_64 and arm64

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1469]
Currently Linux users need to install juvix using stack and build from source. We want to provide a convenient way of installing Juvix without building from source by distributing statically linked binaries.

**Comment by paulcadman** [comment]
There are many pitfalls around static linking with glibc so it's common to use the musl libc (via the Alpine linux distribution) to produce statically linked Haskell binaries.

 The first issue is that `System.Environment.getEnv` does not work on GHC in alpine. This is used by the gitrev package which we use to display the Juvix version, see: https://gitlab.haskell.org/ghc/ghc/-/issues/20977

The second issue is that the stack segfaults during the Juvix build. Strangely, running the build several times fixes the segfault. Cabal / GHC produces a core dump however it is useless because I was using a build of Cabal / GHC without debug symbols.

I installed GHC using `ghcup` because stack does not have a binary distribution of GHC for alpine:

```
ghcup install ghc --force -i /usr/local 9.2.4
```

FP Complete produces docker images of static stack builds with alpine https://github.com/fpco/alpine-haskell-stack/tree/ghc923, unfortunately they do not have an image for GHC 9.2.4 yet (they have 9.2.3). We should try this image when it becomes available.

**Comment by paulcadman** [comment]
Actually it looks like the GHC binaries for 9.2.x distributed by ghcup may be broken wrt template Haskell, see https://gitlab.haskell.org/ghc/ghc/-/issues/20266

**Comment by paulcadman** [comment]
I tried to build static aarch64 (linux arm64) - but the Haskell tooling for this OS/architecture is too immature. For example there are no alpine distributions of GHC for linux arm64 and no binary distributions of stack https://github.com/commercialhaskell/stack/issues/5709

I tried building GHC and stack from source for linux arm64 but there were many compilation errors. I think we should wait for the Haskell project to better support this OS/architecture before tackling this.

**Comment by paulcadman** [comment]
I've added a linux x86_64 binary to the 0.2.4 release https://github.com/anoma/juvix/releases/download/v0.2.4/juvix-0.2.4_linux-x86_64.gz

In future we can use the [linux static binary](https://github.com/anoma/juvix/actions/workflows/linux-static-binary.yaml) action to produce the release binary.

**Comment by janmasrovira** [comment]
Great! I've tried it and it works fine on my machine

**Comment by paulcadman** [comment]
Thanks for trying it @janmasrovira !
