### ISSUE TITLE
Replace the highlight command by a new command `ide` 

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1471]
The idea of this new command `ide` is to generate files to be consumed for our text editor plugins (emacs and vs code). The initial proposal is to have:

- `.juvix-highlighting` 
- `.juvix-goto`
- `.juvix-types`

Eventually, all the logic to generate these files will be implemented in the LSP implementation. Currently, this is an easy way to support expected features from the plugin editors.

**Comment by paulcadman** [comment]
Superseded by:
* https://github.com/anoma/juvix/issues/2832
