### ISSUE TITLE
WASM Backend from LLVM

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#155]
[It seems since LLVM 8 that WASM support is no longer experimental](https://releases.llvm.org/8.0.0/docs/ReleaseNotes.html#changes-to-the-webassembly-target)

It thus makes sense that for our WASM backend that we experiment and figure out all quirks from the pipeline of LLVM to WASM.

[As of  LLVM9 it seems that some work regarding the support is still under development](https://github.com/llvm-mirror/llvm/tree/master/lib/Target/WebAssembly). However [the web assmembly faq even mentions the new "clean WebAssembly backend" being development in LLVM](https://webassembly.org/docs/faq/).

We should see if with the current support that #103 is easily fulfilled by this pipeline.

**Comment by cwgoes** [comment]
One note is that I expect we will want *two* WASM backends (or at least two variants) - one with interaction nets & parallel evaluation, and one without for sequential evaluation and/or very small functions - since some of the WASM execution environments might not support any parallelism.

**Comment by cwgoes** [comment]
Now exists, thank you @systemf-frank
