### ISSUE TITLE
Rewrite the test for lambda-lifting to use evaluation

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1569]
Right now, the tests for lambda-lifting are extremely fragile, and in fact buggy. I just broke them by adding builtin inductive types, which changed the numbering of new symbols. They may break even with no changes (while printing IdentContext, the order of elements obtained with HashMap.toList is unspecified -- it depends on the details of the HashMap implementation, which may differ with different computer architectures or minor versions of the library or even with time on the same computer if there is some randomisation involved).

Instead of comparing the textual representation of IdentContex, we should compare the results of evaluation of functions applied to some arguments before and after lambda-lifting. And check that there are no lambdas after lambda-lifting (except at the top).

**Comment by lukaszcz** [comment]
In fact, why not just lambda-lift (some) of the tests for the evaluator and see if the evaluation results are preserved?

**Comment by janmasrovira** [comment]
> 

I thought that would we a good idea as well, let's do that
