### ISSUE TITLE
Multiple backend targeting strategy

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#157]
Inspired by @thealmarty's question on parameterisations sharing primitives.

Juvix should support multiple backends - LLVM, Michelson, WASM, (later, maybe) EVM, etc. Insofar as it is possible, I think we want developers to be able to 'write once, deploy everywhere' - meaning that as few properties of high-level contracts as possible should be dependent on the particular backend. However, many of these backends are not (directly) compatible - they have different primitive types & values, different cost models, different architectures, etc.

Thus, we have a choice to make about where to 'fix' the backend in the stack.

I see two main options:
1. The whole core language could be parameterised over the target backend. If the frontend language was also parameterised, contracts would be backend-specific. There could, however, be a general library using a lot of typeclasses which automated most of the boilerplate, I think. If the higher-level library can automate this 'backend selection' well, the advantage of this option is that the primitives of the backend can be directly exposed to the developer for cases where they might need to use them.
2. The core language could be parameterised over a 'general' set of types/values (naturals, integers, etc.) and then each backend could have a translation layer. This might introduce some inefficiencies or incompatibilities, and adds an extra step between core and each backend, but it does mean that all contracts would be cross-backend (assuming we write this translation layer correctly).

(there may be options I have not thought of)

I am inclined towards option 1 because I think developers will sometimes need to use backend-specific primitives and we should make them accessible (although perhaps behind a 'warning' label). It is a bit of abstraction leakage, though.

**Comment by cwgoes** [comment]
Higher-level representation of the backend as a value/type in the language?

**Comment by cwgoes** [comment]
...so, ideally, if we do that nicely, it will also be possible to typecheck as one project (set of source files which can co-reference each other) a multi-chain / multi-backend application.

**Comment by cwgoes** [comment]
Architecturally, I suppose we would do this by having individual parameterisations of core per backend, one 'meta-parameterisation' combining them all, and a downcast function, run at compile time, that evaluates the term, walks all primitives, and either succeeds in translating them to a single backend or fails if terms from other backends are still present. We can figure out the details later.

**Comment by cwgoes** [comment]
Another aspect to consider is automatic "wire format" conversion between backends - e.g. if you define a datatype which is passed between Michelson & a zk-SNARK circuit, the two backends will utilise different underlying representations, which must be correctly converted between if the Michelson code calls the zk-SNARK verifier. Hopefully there is a clean way to do this automatically (& thereby save time for the developer and remove the risk of silly encoding mistakes).

**Comment by fdedden** [comment]
Backends could be implemented through a class proving the interface:
```haskell
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE GADTs #-}

module Backend where

-- | Simplified term datatype.
data Term = Term deriving Show

-- | Class defines an interface for a backend. The functional dependency tells
-- the compiler that there will only be a single target per backend, and that
-- per target there will only be a single backend.
class Backend backend target | backend -> target, target -> backend where
  -- | Check the types for given backend. The output is annotated, as sending
  -- the checked code to a different compiler backend doesn't make sense.
  typecheck :: Term   -> backend Term

  -- | Compile a backend annotated term into its target.
  compile   :: backend Term -> target

-- Bogus Michelson implementation.
data Michelson t  = Michelson t  deriving Show
data MichelsonASM = MichelsonASM deriving Show

instance Backend Michelson MichelsonASM where
  typecheck Term             = Michelson Term
  compile   (Michelson Term) = MichelsonASM

-- Bogus LLVM implementation.
data LLVM t  = LLVM t  deriving Show
data LLVMASM = LLVMASM deriving Show

instance Backend LLVM LLVMASM where
  typecheck Term        = LLVM Term
  compile   (LLVM Term) = LLVMASM

-- | This functions type checks only because of the dual functional dependency
-- in the Backend-class.
test1 :: Backend b target => Term -> target
test1 t = compile $ typecheck t

-- | Datatype for storing the backend to use.
data BackendChoice b where
  BMichelson :: BackendChoice Michelson
  BLLVM      :: BackendChoice LLVM

-- | Examples use of BackendChoice.
test2 :: Backend b target => BackendChoice b -> Term -> target
test2 b t = case b of
  BLLVM      -> compile $ typecheck t
  BMichelson -> compile $ typecheck t
```

**Comment by fdedden** [comment]
I don't think the prototype is going to work. For parsing we need a function that returns a `BackendChoice` without any witness:

```haskell
pBackend :: Parser (BackendChoice b)
pBackend = do
  symbol <- pSymbol
  case symbol of
    "llvm" -> return BLLVM
    ...
```
GHC is not able to find the right type for each case, due to the lacking witness.

**Comment by fdedden** [comment]
As Andy pointed out during the meeting on 11th March, using `TypeApplications` to force an instance selection for a function could help us.
