### ISSUE TITLE
Consider backend integration with CosmWASM

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#1570]
[CosmWASM](https://cosmwasm.com/) is a WASM runtime for many Cosmos ecosystem blockchains, including [Osmosis](https://docs.osmosis.zone/) and [Nyx](https://blog.nymtech.net/nym-now-supports-smart-contracts-2186da46bc7f). CosmWASM uses Wasmer inside, so it shouldn't require changes to compilation - we just need to support [these API entrypoints](https://github.com/CosmWasm/cosmwasm#api-entry-points). Several of these Cosmos blockchains have active developer communities and could be a good environment to start testing out Juvix in the short to mid term. The [CosmWASM docs](https://docs.cosmwasm.com/docs/1.0/) may also be helpful.

A few examples of what we could write in CosmWASM:
- Multi-signature contract
- Simple AMM
- IBC rate limiting code for Osmosis (they're interested in this)

cc @paulcadman thoughts?

**Comment by paulcadman** [comment]
Thanks @cwgoes - I believe the only missing ingredient we have with the current Juvix setup is a JSON de/serialisation capability, then we could try this.

**Comment by cwgoes** [comment]
This is no longer a priority from the organisational side, no need to spend time on it - better to just compile to Taiga, and deploy Taiga verifiers wherever folks happen to need them.
