### ISSUE TITLE
Proposal for supporting basic dependencies

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#1620]
Currently Juvix only supports compiling a single package with no dependencies.
The goal of this proposal is to give the user the ability to specify dependencies in the `juvix.yaml` file.

Example `juvix.yaml`:
```
name: my-library
version: 1.0
dependencies:
- ~/juvix-libs/containers
- ~/juvix-libs/extra
```
Then, the compiler will expect to find a `juvix.yaml` file in each of the directories specified in `dependencies`. The modules defined in these packages should be available through regular `import` statements.
We can discuss what happens when there are name collisions. The Ghc behaviour is that the local package takes precedence over dependencies. If two dependencies have the same module, it is an error.

The idea is that these changes do not affect anything that comes after the scoper. This is not something that will stay true in the long term, but for now it can be ok.

**Comment by jonaprieto** [comment]
PR #1622 closes this issue.
