### ISSUE TITLE
Typing for variables in let expressions

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1637]
Instead of:

```haskell
let { x : A;
      x := y } in z;
```
We want to type:

```haskell
let x : A := y in z;
```

**Comment by lukaszcz** [comment]
With the shorter syntax we should allow omitting the braces, at least when there is just one equation. Otherwise it gets unnecessarily verbose, in my opinion.

**Comment by janmasrovira** [comment]
@lukaszcz I agree. Moreover, since the braces for let expressions serve no purpose, I think we should get rid of them entirely
