### ISSUE TITLE
Arithmetic circuit backend

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#171]
Not a priority to ship soon, but an interesting test-case for our compiler architecture.

- How to structure the core dialect? Will need to eventually turn into an arithmetic circuit with addition gates, multiplication gates, and an element type (usually a field element) which is converted into a rank-1 constraint system. The circuit encodes a relation between the input & output, i.e. `circuit :: Input -> Output -> Bool`
- Input & output types must desugar to vectors of the element type with fixed lengths.
- Higher-order functions must be reducable at compile time to relations.
- Probably will eventually need Rust bindings to the prover/verifier code ([ref](https://blog.mgattozzi.dev/haskell-rust/), [ref](http://hackage.haskell.org/package/curryrs)). This doesn't matter so much if our primary goal is to output a circuit description in some standard format and 'glue code' for integration into smart contracts, though.

Inspirations: [snarky](https://github.com/o1-labs/snarky), [genSTARK](https://github.com/GuildOfWeavers/genSTARK), [ZoKrates](https://github.com/zokrates/zokrates).

We should only do this if it will actually be useful (compared to existing DSLs). I think it would be useful if and only if:
- We can implement a higher level of abstraction without sacrificing performance thanks to the powerful typesystem & usage information, and possible optimisation layers
- We can nicely integrate code running in zero-knowledge with regular smart contract code in a way that is very convenient for contract authors, automates all the data conversion tedium, and allows for proofs across multi-backend code (ref https://github.com/cryptiumlabs/juvix/issues/157#issuecomment-552046922)
- We can output performant code (circuit descriptions to be executed on dedicated provers/verifiers and smart contracts as appropriate) that can be used in production.

**Comment by cwgoes** [comment]
With regards to:
> Higher-order functions must be reducable at compile time to relations.

I believe this should be possible if we fully evaluate under lambdas - in particular consider the following case:

```haskell
relation :: Input -> Output -> Bool
relation input output =
  (case input of
     1 -> (==) 2)
     2 -> (==) 3) output
```

If we evaluate under the case (which will desugar to a lambda), we should end up with:

```haskell
relation :: Input -> Output -> Bool
relation input output =
  (input == 1 && output == 2) ||
  (input == 2 && output == 3)
```

which is just fine.

(to encode the OR - `or x y -> x + y - (x * y) = 1`)

**Comment by cwgoes** [comment]
Maybe we could also try an evaluation monad which keeps intermediary results (basically 'allocating memory' as necessary) and can output a circuit representation. Might be convenient for avoiding duplication of intermediary evaluations.

**Comment by cwgoes** [comment]
To study:
- [ ] Existing DSL implementations (Snarky, ZEXE, genSTARK, gadget libs, etc.)
- [ ] Addition/multiplication gate costs in different ZKP systems
- [ ] Plausible / beneficial optimisation passes

**Comment by cwgoes** [comment]
- [ZoKrates expression flattener](https://github.com/Zokrates/ZoKrates/blob/master/zokrates_core/src/flatten/mod.rs)
- [ZoKrates constraint system optimiser](https://github.com/Zokrates/ZoKrates/tree/master/zokrates_core/src/optimizer)
- [Snarky source](https://github.com/o1-labs/snarky/tree/master/src)

**Comment by cwgoes** [comment]
We should write out the approximate expression ~> constraint list transform.

**Comment by cwgoes** [comment]
[Daira's talk slides](https://github.com/daira/r1cs/blob/master/zkproofs.pdf) are helpful.

**Comment by cwgoes** [comment]
Possibly we can use [this library](https://github.com/adjoint-io/zkp) for in-process proving/verification.

**Comment by cwgoes** [comment]
Example high-level usage example (approximate):

```haskell
```

Compilation questions

We can assume that the compiler will operate on a closed term `rel :: x -> y -> Bool` (a relation) where `x` and `y` are either primitive types or ADTs (possibly inductive) composed of primitive types, and that all lambda functions will be inlined & fully evaluated at compile-time, so `rel` will necessarily be a two-argument function returning a boolean (with arbitrarily nested pattern-matching & fully applied primitive functions, e.g. and, or, add, mul, etc.). Calls to other functions - recursive functions must have compile-time fixed depth (e.g. folding for Merkle path verification) - will be fully inlined (at least for the initial version, later, e.g. with custom gate compilation or AIR, this might change, but it's easiest for now). 

*Compiling ADTs*

At this level, inductive families should desugar/erase to simple algebraic datatypes.

Product types:
- Associated field elements (association tracked at compile-time)
- Figure out when sums (e.g. `(int, int)`) can be packed in one field element

Sum types:
- Tagged union (again, figure out how to pack this efficiently)

*Custom gate generation*

Investigate PLONK-style custom gates & compile-time generation. Needs more research.

**Comment by cwgoes** [comment]
Ah, also - closures will work only for values known at compile-time, otherwise they must be in inputs/outputs (unless we want to do some sort of "implicit output" thing, which is possible, could also be interesting - maybe we should go all the way and have only the witness data be the secret input).

**Comment by cwgoes** [comment]
Another aspect here is custom gate generation - https://github.com/cryptiumlabs/cryptography/issues/12.

**Comment by cwgoes** [comment]
![IMG_20200131_103250461_HDR](https://user-images.githubusercontent.com/24760279/73589967-2d7f4c80-44dd-11ea-9394-c16f70793cb5.jpg)

![IMG_20200131_105638316_HDR](https://user-images.githubusercontent.com/24760279/73589971-307a3d00-44dd-11ea-8aa6-61badf6cfc2d.jpg)

![IMG_20200131_110214591_HDR](https://user-images.githubusercontent.com/24760279/73589972-32dc9700-44dd-11ea-9030-6d4b2458545c.jpg)

**Comment by cwgoes** [comment]
For now, we can use [arithmetic-circuits](https://github.com/adjoint-io/arithmetic-circuits) and [zkp](https://github.com/adjoint-io/zkp) for the backend.

Later we will want to export provers/verifiers to Rust or other platforms.

**Comment by joebebel** [comment]
https://github.com/ZcashFoundation/GrantProposals-2018Q2/issues/33

proposal for integrating MPC and SNARK compilers (on the principle that people have been working on MPC compilers for quite a while)

https://www.microsoft.com/en-us/research/uploads/prod/2019/01/paper.pdf

**Comment by cwgoes** [comment]
It's fine if we start with a primitive type which is just a field element.

This can be done with a parameterised version of the core language.

**Comment by joebebel** [comment]
We should investigate how to encode integer comparison operations on native field elements. Surely people have looked extensively into this, but it is not obvious to me what the status of this is.

**Comment by cwgoes** [comment]
Further discussion: https://hackmd.io/0p3Fpn_0RkqxddtPeXZ-oA?both

**Comment by cwgoes** [comment]
This should be split into research discussions & specific tasks for the circuit backend.
