### ISSUE TITLE
Non-judoc comments are removed when generating HTML output

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1723]
This makes it impossible to e.g. write a comment above an import statement.

It also makes it hard to write a tutorial as a Juvix file and generate nice html output for it.

**Comment by paulcadman** [comment]
The same issue affects the formatter, but we have no ideas on how to fix it. https://github.com/anoma/juvix/issues/1593

**Comment by janmasrovira** [comment]
I have been thinking about this today.
Collecting the string comments is an easy task. The hard part is printing them in the appropriate place wihtout storing them in the ast.
I've been looking at the implementation of [`ghc's exact print`](https://hackage.haskell.org/package/haskell-src-exts-1.23.1/docs/src/Language.Haskell.Exts.ExactPrint.html#exactPrint) for inspiration. It looks a bit hacky but I'll see what I can get out of it

**Comment by paulcadman** [comment]
An interesting note on GHC exact printing annotations: https://gitlab.haskell.org/ghc/ghc/-/wikis/api-annotations
