### ISSUE TITLE
Support polymorphism in the GEB backend

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1752]
Depending on whether predicative polymorphism is available in GEB in the near future, either directly translate polymorphic functions to polymorphic GEB or monomorphise first (giving a compilation error on a small subset of the language that cannot be monomorphised).

Note that even if the datatypes used with the GEB backend are mostly monomorphic, the programmer may still want the convenience of polymorphic functions. For example, `map`, `fold` or `filter` on polymorphic lists from the standard library.

**Comment by paulcadman** [comment]
The geb backend is not supported.
