### ISSUE TITLE
Add a format command

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1777]
Let's make `format` the command out of `dev scope` with a few extra options.

- `--check` which only checks if the file is formatted
- `--in-place` to replace the file contents with the juvix formatting output

We can then use this in the Juvix stdlib CI to bring more uniformity to that codebase.

**Comment by janmasrovira** [comment]
Once this is done, I think we should ensure that all juvix test files are formatted

**Comment by paulcadman** [comment]
Recommended safe behaviour of `--in-place` (from `gofmt`) to avoid data loss:

* Write to the file only if the file's formatting is different from `juvix format`'s version.
* If an error occurs during overwriting, the original file is restored from an automatic backup.
