### ISSUE TITLE
The Juvix formatter works poorly with multi-line ifs

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1793]
For example it formats a single multi-line `if` (or generally function application) in a function clause as follows:
```
  go n s := if
    (s < n)
    (go (sub n 1) s)
    (go n (sub s n) + go (sub n 1) s);
```
I think this is not very readable, because the arguments have smaller indentation than the `if`. One solution could be to put the `if` on a new line in this case.

**Comment by lukaszcz** [comment]
And for `if` it would make a lot of sense to have the first argument always on the same line as the `if`.

**Comment by jonaprieto** [comment]
Possible options:

```
  go n s := 
    if 
      (s < n)
      (go (sub n 1) s)
      (go n (sub s n) + go (sub n 1) s);
```
or

```
  go n s := 
    if (s < n)
      (go (sub n 1) s)
      (go n (sub s n) + go (sub n 1) s);
```
