### ISSUE TITLE
Output proper Geb Lisp programs for Geb Binary Usage

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1807]
We must ensure that the Geb Lisp files generated by `juvix dev core compile -t geb` are properly formatted for use with the Geb binary. 

 - https://github.com/anoma/geb/pull/45

As a model, the output should be like the following: 

```bash
$ cat foo.lisp
```

```lisp
(defpackage #:foo
  (:shadowing-import-from :geb.lambda.spec #:func #:pair)
  (:shadowing-import-from :geb.spec #:case)
  (:use #:common-lisp #:geb.lambda.spec #:geb))

(in-package :foo)

(defparameter *entry*
  (typed x typeOfX))
```

Where `*entry*` is a name for the current output if we run `juvix dev core compile -t geb foo.jvc`.
The term `(typed x typeOfX)` is where the term-and-type information associated with `*entry*` goes; however, as far as I know, the type is not used/checked in geb-lisp.

Ultimately, by running the following commands (Using geb-instructions from [here](https://github.com/anoma/geb/tree/mariari/binaries#x-28GEB-2EENTRY-3A-40GEB-ENTRY-20MGL-PAX-3ASECTION-29), one should be able to get VampIR output from JuvixCore programs.

```bash
juvix dev core compile -t geb foo.jvc -o foo.lisp
./geb.image -i "foo.lisp" -e "foo::*entry*" -l -v t
``` 

The flags for geb-image may change unexpectedly. 

- https://github.com/anoma/geb/pull/44

**Comment by lukaszcz** [comment]
> The term (typed unit so1) is where the type information of the entry term goes; however, as far as I know, it's not used/checked in geb-lisp.

Are you sure it's the type and not the body, i.e., the term we should paste in?

http://clhs.lisp.se/Body/m_defpar.htm

**Comment by jonaprieto** [comment]
Yes, The term and the type, `(typed x typeOfx)`.
