### ISSUE TITLE
Implement unification

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#181]
Resources:
- [Higher-Order Dynamic Pattern Unification for
Dependent Types and Records](http://www.cse.chalmers.se/~abela/unif-sigma-long.pdf)
- [Towards Unification for Dependent Types](https://xnning.github.io/slides/towards-unification-for-dependent-types.pdf)
- Idris 2 codebase

Additional goals:
- Usage inference (integer, polynomial usages)
- Monadic cost inference (later)

**Comment by andy-morris** [comment]
[A Tutorial Implementation of Dynamic Pattern Unification](http://adam.gundry.co.uk/pub/pattern-unify/) might also be useful?

**Comment by cwgoes** [comment]
There are definitely more up-to-date issues, since things have happened since 2019, or so I am told by @andy-morris
