### ISSUE TITLE
Variable shadowing doesn't work correctly with bindings introduced by a let

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1826]
Typing into REPL
```
case zero | x := let x : Nat := suc zero in x
```
the result is
```
zero
```
but should be
```
suc zero
```

Tested on main branch, without the any transformations on core.

**Comment by jonaprieto** [comment]
Check using `juvix --show-name-ids dev scope fileName.juvix`

**Comment by lukaszcz** [comment]
This is a bug in the scoper:
```
case zero@62
        | x@287 := let 
          x@288 : Nat@61 := suc@63 zero@62;
         in x@287
```

**Comment by lukaszcz** [comment]
I think the error is due to this in Scoping.hs:1067:
```haskell
checkUnqualified s = do
  -- Local vars have scope priority
  l <- HashMap.lookup s <$> asks (^. localVars)
```
Because let-bound variables are treated as functions, so local variables which they should shadow incorrectly take priority.

But I don't know a nice way to solve this.
