### ISSUE TITLE
Make the Juvix formatter respects the ASCII symbols

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1836]
I'm getting this:
```
  odd := λ {
      | zero := false
      | (suc n) := even n
    };
```
after formatting the code:

```
  odd := \ {
      | zero := false
      | (suc n) := even n
    };
```
We should respect the symbols the user decides to use.

Related to this topic:

- https://github.com/anoma/juvix/pull/1834

**Comment by lukaszcz** [comment]
I think we should also respect the user's decisions about spaces before `,` and after `\` and `λ`. For someone not coming from the Agda world, it is super annoying that spaces get automatically inserted there, especially with the comma. In terms of annoyance, it's as if we were automatically inserting a space after every '('.

**Comment by janmasrovira** [comment]
> I think we should also respect the user's decisions about spaces before `,` and after `\` and `λ`. For someone not coming from the Agda world, it is super annoying that spaces get automatically inserted there, especially with the comma. In terms of annoyance, it's as if we were automatically inserting a space after every `(`.

please, create a separate issue for that
