### ISSUE TITLE
 Integration of Juvix with Mdbook for  Juvix Excerpts

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1839]
The current user documentation renders using the Mdbook tool. Some Juvix examples in the documentation may not type check or, even worse, parse. 

We need a first integration of Juvix with Mdbook to:
- enable parsing and highlighting for easier readability, and
- type checking of Juvix snippets to improve the documentation's accuracy and reliability.

**Comment by janmasrovira** [comment]
being worked on in #1857
