### ISSUE TITLE
Add option to omit generation of fail nodes in pattern matching compilation

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1889]
It is not possible to compile JuvixCore fail nodes to Geb. The current pattern matching compilation algorithm generates fail nodes on all default case branches, even when all constructors have been covered, because it does not check for exhaustiveness.

Exhaustiveness checking will be implemented as part of https://github.com/anoma/juvix/issues/1798. In the meantime it would be useful to have an option to omit the generation of fail nodes in the default case branch so that we can compile examples to Geb. The user would use this option to assert full coverage of pattern matches.

Suggested flag name: `--assume-coverage`.

**Comment by janmasrovira** [comment]
related: https://github.com/anoma/geb/issues/90

**Comment by lukaszcz** [comment]
I think we can close this after #1798 and #1947.
