### ISSUE TITLE
Juvix should not traverse subdirectories when launching the REPL

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1895]
This makes it impossible e.g. to launch the REPL in the home directory on MacOS because of permission issues. And it's unnecessary.

We should also consider disabling the directory traversal when compiling a single file, i.e., when there is no yaml file. Then presumably the user doesn't want this file to be a part of a project.

One proposed solution: look for other files only when there is a yaml file, both for compilation and for the REPL. In the future we want to have import in REPL, and then it makes sense to be within the context of a project in a REPL session.

**Comment by janmasrovira** [comment]
To not scan the directory can be solved by doing what you propose. However, we'll need to figure out what to do with the standard library. Currently it is copied under `.juvix-build/stdlib` when launching the repl, and that requires write permissions. One option could be to put it under `/tmp`, but I am not sure if that has other unwanted consequences
