### ISSUE TITLE
Runtime juvix assertion error in Hanoi example 

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1919]
I compiled the Hanoi example with the `--debug` flag for the native target on macOS aarch64:

https://github.com/anoma/juvix/blob/dbe9ff61d794637a3315068c65bfd296512f07dc/examples/milestone/Hanoi/Hanoi.juvix

```
juvix compile -g Hanoi.juvix
```

When running the program you get the following error:

```
./Hanoi
examples/milestone/Hanoi/.juvix-build/Hanoi.c:216: Juvix assertion failed. Please report.
```

NB: The program runs without error and with the expected output when I use the `wasm32-wasi` target, or when I use the `native` target without the `--debug` flag .

After doing some debugging the trace looks like this:

JUVIX_STR_CONCAT  - https://github.com/anoma/juvix/blob/dbe9ff61d794637a3315068c65bfd296512f07dc/runtime/src/juvix/api.h#L79
CONCAT_CSTRINGS - https://github.com/anoma/juvix/blob/dbe9ff61d794637a3315068c65bfd296512f07dc/runtime/src/juvix/object/cstring.h#L43
ALLOC - https://github.com/anoma/juvix/blob/dbe9ff61d794637a3315068c65bfd296512f07dc/runtime/src/juvix/mem/alloc.h#L50

and the failing assertion is caused by an `is_same_page` check:

https://github.com/anoma/juvix/blob/dbe9ff61d794637a3315068c65bfd296512f07dc/runtime/src/juvix/mem/alloc.h#L51

**Comment by lukaszcz** [comment]
Probably forgot to include the memory allocated for string concatenation in the memory usage count. I'll look into it.
