### ISSUE TITLE
out of memory errors when running WASM compiled bench examples

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1926]
The runtime crash can be reproduced with the merge sort and fibonacci bench tests:

https://github.com/anoma/juvix/blob/8d7e669f7499b4122d9b1a9baf42828d1c163c7a/tests/benchmark/mergesort/juvix/mergesort.juvix
https://github.com/anoma/juvix/blob/8d7e669f7499b4122d9b1a9baf42828d1c163c7a/tests/benchmark/fibonacci/juvix/fibonacci.juvix

```
$ cd tests/benchmark/mergesort/juvix
$ juvix compile -t wasm32-wasi mergesort.juvix
$ wasmer mergesort.wasm
error: out of memory
error: failed to run `mergesort.wasm`
│   1: RuntimeError: unreachable
╰─▶ 2: unreachable
```

When running with wasmtime instead of wasmer there's a bit more information:

```
$ wasmtime mergesort.wasm
error: out of memory
Error: failed to run main module `mergesort.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x2795 - <unknown>!<wasm function 14>
           1: 0x20c3 - <unknown>!<wasm function 11>
           2: 0x20af - <unknown>!<wasm function 10>
           3: 0x1963 - <unknown>!<wasm function 3>
    2: wasm trap: wasm `unreachable` instruction executed
```

There are no errors when running the same example after compiling with the native target.

**Comment by lukaszcz** [comment]
The error is triggered by the runtime because more memory couldn't be allocated. The "unreachable" thing is because to exit the runtime triggers the trap instruction, which is the only way to abort in WASM.

It is possible that we've just run out of memory. The limit is 4GB or less in WASM, we don't do GC, we don't optimize memory representation (in contrast to the optimization I did manually for the "runtime" versions of the program), and programs like mergesort intentionally allocate a lot of memory. But I'll look into it more closely nonetheless.

**Comment by lukaszcz** [comment]
Hmm, that's strange for Fibonacci because it's a tail-recursive function that doesn't allocate memory. It works fine on my Mac. In the WASM disassembly there are only gotos. I have no idea where the "out of memory" error might come from on your Mac.

**Comment by lukaszcz** [comment]
No, it's fine. I was testing on the branch with the new pattern matching compiler. The naive pattern matching compiler introduces a lot of extra lambda that are then lifted-out and allocated as closures during runtime in each iteration. As we run 100,000,000 iterations, it's no wonder we hit the 4GB memory limit.

**Comment by lukaszcz** [comment]
Mergesort also works with the new pattern matching compiler. So I think a similar thing happens: the additional closure allocation generated by the native pattern matching compiler makes us hit the 4GB memory limit.

**Comment by lukaszcz** [comment]
Actually, this can be easily solved by let-folding lambdas, i.e., treating unapplied lambdas as immediate (which they should be). That would remove the extra closure creation generated by the naive pattern matching compiler.
