### ISSUE TITLE
Add one-liner installation command 

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#1937]
Let's improve the Juvix user experience by providing a single command for the main installation while including clear instructions for any further steps required to set up dependencies, for which calling `juvix doctor` can come in handy. This will make the overall process more efficient and user-friendly.

Examples:

- https://github.com/wasmerio/wasmer-install
- https://www.rust-lang.org/tools/install

**Comment by paulcadman** [comment]
As part of this we could consider bundling the architecture independent wasi-sysroot files into the Juvix compiler binary. We would write the wasi-sysroot to the `.juvix-build` directory as we do for other artefacts. This would avoid the "set the WASI_SYSROOT" environment setup in the installation.

**Comment by jonaprieto** [comment]
The script is living in this repo:
- https://github.com/anoma/juvix-installer/
