### ISSUE TITLE
The core transformation `RemoveTypeArgs` assigns incorrect `identifierArgsNum`

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#1944]
Given the following core code:
```
-- tmp.jvc
def sum := letrec sum := \x if x = 0 then 0 else x + sum (x - 1) in sum;
```

The output of `juvix dev core read tmp.jvc -t pipeline-eval,lifting,top-eta-expand,move-apps` is 
```
def sumrec_5[1] := λx if = x 0 then 0 else + x (sumrec_5 (- x 1));
```
The number in brackets next to the identifier is the `identifierArgsNum`.  So `sumrec_5[1]` is correct.

But when I add `remove-type-args` to the pipeline, `juvix dev core read tmp.jvc -t pipeline-eval,lifting,top-eta-expand,move-apps,remove-type-args`, I get
```
def sumrec_5[0] := λx if = x 0 then 0 else + x (sumrec_5 (- x 1));
```
And `sumrec_5[0]` seems to be wrong

**Comment by lukaszcz** [comment]
I can't reproduce. Are you sure `sumrec_5` has the right type? Why is the type not printed here?

After removing type arguments the number of arguments is simply set according to the type.

**Comment by janmasrovira** [comment]
The problem was that the test was lacking type annotations for the letrec items
