### ISSUE TITLE
DisambiguateNames is not run on the result node in the REPL

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1958]
Apparently, PR #1941 doesn't fix this. E.g. if you write `nil` in the REPL, you get:
```
λ(? : Type) nil ?
```

More long-term, we should reflect back the evaluated nodes to frontend syntax, using e.g. `<fun>` for lambdas and reverting eta-expansion so that `nil` gets printed as `nil`.

**Comment by paulcadman** [comment]
My mistake - I set the wrong default in the juvix repl options: https://github.com/anoma/juvix/blob/ff495ef32627913836a175fe2845b70354f99c14/app/Commands/Repl/Options.hs#L28

**Comment by paulcadman** [comment]
What is the expected output when you type `nil` into the REPL? Should the name `nil` be rewritten to something else?

**Comment by paulcadman** [comment]
Oh I see, the `?` should be disambiguated.

**Comment by lukaszcz** [comment]
For now, the expected output is `λ(_X : Type) nil _X` because `nil` gets eta-expanded, and we don't omit implicit parameters to constructors when printing Core. It's just about the name of the variable - if disambiguation were run then `?` would've been replaced.

Long-term, I would say the output should be just `nil`. But that's a bigger discussion on how to reflect and print things after they have been translated to Core.
