### ISSUE TITLE
User-friendly specification of operator priorities

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1964]
Specifying operator priorities by numbers is, in my opinion, a rather daft idea. These numbers are hard to remember and they don't mean anything: what matters is the relative order of the operators (linearised if necessary).

Instead, the user should be able to specify priorities relative to priorities of already defined operators. Something like:
```
infixl +;
infixl * after +;
infix == before +;
infix > with ==;
```

Perhaps it should also be possible to specify operator groups to reduce unnecessary inter-module dependencies.
```
operator group additive;
operator group multiplicative after additive;
operator group comparison before additive;

infixl + with additive;
infixl * with multiplicative;
infix == with comparison;
infix > with comparison;
```

**Comment by paulcadman** [comment]
I like this idea, named precedence groups is the approach that Swift takes so maybe we can learn from that:

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/declarations/#Operator-Declaration

**Comment by mariari** [comment]
If your languages is setup nicely then you can still take the approach of numbers. However you would need evaluation

```haskell
register-group : symbol -> Integer -> IO ()

group : symbol -> Integer

after : symbol -> Integer

before : symbol -> integer

in-group : symbol -> Integer
```

Thus we can say
```haskell

register-group arithmetic
register-group logical (after arithmetic)

infxl + (in-group arithmetic)

infxl * (in-group arithmetic)

infixl ! (in-group logical)

infxl !===! (before +) -- note that you can say for groups or symbols here, the logic of before works
```

**Comment by lukaszcz** [comment]
See #2007

**Comment by lukaszcz** [comment]
The advantage of the partial order approach is that we don't artificially impose an ordering between all operators. In case the relative order between two operators doesn't follow from the declarations, the operator resolution should fail when they are used ambiguously (that's what happens in Swift). If we use numbers, then the precedence levels of any two operators are comparable.
