### ISSUE TITLE
Pragmas to specify per-function and per-module compiler options

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1965]
Something analogous to Haskell's pragmas: `{-# ... #-}`.

Needed to be able to specify e.g. per-function unrolling depth. In the future: inlining and specialisation.

**Comment by janmasrovira** [comment]
It was agreed on the meeting that yaml would make a good languages for pragmas.
```
{-# <yaml object> #-}
```

Note that `#-}` should not appear in the yaml object
