### ISSUE TITLE
Compiler crash when importing a module with nested imports

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2005]
> ⚠️  There's a failing test case demonstrating this bug in https://github.com/anoma/juvix/tree/import-nested-module-bug
> specifically see: https://github.com/anoma/juvix/blob/38be0c14019f2454afcca1ce6859bf3c08973071/tests/Internal/positive/NestedModuleScope/Import.juvix

Say you have a module containing a definition:

Base2.juvix
```
module Base2;

type Foo := foo : Foo;
```

and a second module which contains a nested module that imports Base2 and exports:

Base.juvix
```
module Base;

module NestedBase;
  open import Base2 public;
end;
```

and a third module that imports both `Base` and `Base2` and uses the definition of `Foo` from Base2:

Import.juvix
```
module Import;

open import Base;
open import Base2;

main : Foo;
main := foo;
```

### Expected behaviour

I expect to compile `Import.juvix successfully`

### Actual behaviour

The compiler crashes when I try to compile `Import.juvix`

```
$ juvix compile Import.juvix
juvix: internal to core: undeclared identifier: foo
CallStack (from HasCallStack):
  error, called at src/Juvix/Prelude/Base.hs:338:9 in juvix-0.3.1-871d1i96WVd8tZZNJNhW2a:Juvix.Prelude.Base
  error, called at src/Juvix/Compiler/Core/Translation/FromInternal.hs:781:20 in juvix-0.3.1-871d1i96WVd8tZZNJNhW2a:Juvix.Compiler.Core.Translation.FromInternal
```

### Notes

If you switch the order of imports in `Input.juvix` then the module compiles successfully.

Import.juvix
```
module Import;

open import Base2;
open import Base;

main : Foo;
main := foo;
```

gives:

```
$ juvix compile Import.juvix
$ ./Import
foo
```

**Comment by janmasrovira** [comment]
If one disables `filterUnreachable` then it compiles correctly

**Comment by janmasrovira** [comment]
@lukaszcz I'm reassigning this to you since you are more familiar with reachability

**Comment by lukaszcz** [comment]
Reachability works under the (seeming reasonable) assumption that the `StatementInclude` correspond exactly to the imports present in the source code.

**Comment by lukaszcz** [comment]
I see that in FromAbstract we generate `StatementInclude` from `StatementImport` only if the module was not already included before, presumably to avoid traversing it multiple times.

I can change reachability to descend into included modules even if they're unreachable - then this should work. But if we're dropping some import statements when translating to Internal then I think it doesn't make much sense to have `StatementInclude` as a separate statement. Its exact position in the statement list gives no useful information, and some included modules are hidden inside other possibly unreachable included modules. In Internal we should just flatten all nested imports into a single module list.
