### ISSUE TITLE
Unexpected whitespace introduced by the formatter

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2059]
I'm getting extra spaces when running the formatter, for example with the
Bank example. Run the following to reproduce the error:

```bash
juvix format --in-place examples/milestone/Bank/Bank.juvix
```

https://github.com/anoma/juvix/blob/8f850c2e5b56182f4ce375245298ea5d77360bd8/examples/milestone/Bank/Bank.juvix#L69

```diff
  decrement _ _ nil := nil;
  decrement f n ((b, bn) :: bs) :=
    if
      (eqField f b)
      ((b, sub bn n) :: bs)
      ((b, bn) :: decrement f n bs);
-
+  
  emtpyBalances : Balances;
  emtpyBalances := nil;
```

**Comment by paulcadman** [comment]
Digging into the prettyprinter code seems to suggest that the whitespace associated with indentation (in the example, the indentation in a local module) should not be added on a blank line:

https://github.com/quchen/prettyprinter/blob/7e32c010ecfaa510c0cbf6ffea04bc7db95d4fcb/prettyprinter/src/Prettyprinter/Internal.hs#L1999

So perhaps we're doing something in ExactPrint that's confusing the library?

**Comment by paulcadman** [comment]
The above only applies to unannotated text. The trailing spaces in annotated text are preserved. So we should unannotate the `Doc` representing the file before rendering.

I tried this will my example from https://github.com/anoma/juvix/issues/2100

```
$ juvix format Example.juvix | cat -e
module Example;$
$
open import Stdlib.Prelude;$
$
module Local;$
  $
  a : Int;$
  a := 1;$
$
  b : Int;$
  b := 2;$
$
end;$
```

The indentation is preserved in the local module. All blank lines **except the first** do not have trailing whitespace. So now the question is why the trailing whitespace remains on the first line?

**Comment by paulcadman** [comment]
https://github.com/anoma/juvix/pull/2101/ Fixes the whitespace for indentation **within** the local module body. 

What remains is to fix the extra whitespace in indented comment lines (which is the case for the first line in the module body in the example above).

**Comment by paulcadman** [comment]
Reference to necessity of `removeTrailingWhitespace` in prettyprinter  https://github.com/quchen/prettyprinter/pull/139
