### ISSUE TITLE
Enhance `typecheck` subcommand functionality for projects

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2066]
Update the typecheck subcommand to accept different types of input. 

- If no arguments are given, it should typecheck the entire project (fail if there is no project with
  a *useful* error message like "No project found in current directory, maybe create one with `juvix init`?") 

```
$ juvix typecheck
```

- If a path is provided, it should typecheck the project at that location (fail similarly to above if
  there is no project at that location)

```
$ juvix typecheck ./my-project
```

- If a filepath is given, it should typecheck the specified file. (Currently, this is the only functionality of the typecheck subcommand.)

```
$ juvix typecheck ./my-project/src/Main.juvix
```

**Comment by paulcadman** [comment]
Currently `juvix typecheck` will use the `main` field of the Package file as default. We're happy with this behaviour.
