### ISSUE TITLE
Formatter adds trailing whitespace in local module body

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2100]
Compare the following Juvix file before and after formatting (The `$` symbol in the output of `cat` indicates the end of the line):

Before:
```
$ cat -e Example.juvix
module Example;$
$
open import Stdlib.Prelude;$
$
module Local;$
$
a : Int;$
a := 1;$
$
b : Int;$
b := 2;$
$
end;$
```

After:
```
$ juvix format Example.juvix | cat -e
module Example;$
$
open import Stdlib.Prelude;$
$
module Local;$
  $
  a : Int;$
  a := 1;$
  $
  b : Int;$
  b := 2;$
$
end;$
```

The body of the local module is indented as expected. However the blank lines are also indented. These blank lines are usually treated as trailing whitespace by editors and get trimmed.

This means that there will be a diff between files formatted within an editor and files formatted using `juvix format --in-place`. This will create noise when reviewing code diffs.

I think we should find a way to avoid indenting blank lines.

As a simple workaround I investigated using the [removeTrailingWhitespace](https://hackage.haskell.org/package/prettyprinter-1.7.1/docs/Prettyprinter.html#v:removeTrailingWhitespace) API - however it has no effect on this kind of trailing whitespace.

**Comment by paulcadman** [comment]
Digging into the prettyprinter code seems to suggest that this whitespace should not be added on a blank line:

https://github.com/quchen/prettyprinter/blob/7e32c010ecfaa510c0cbf6ffea04bc7db95d4fcb/prettyprinter/src/Prettyprinter/Internal.hs#L1999

So perhaps we're doing something in ExactPrint that's confusing the library?

**Comment by jonaprieto** [comment]
This issue was already reported here:

- #2059

and it's blocking

#2057

**Comment by paulcadman** [comment]
Duplicate of https://github.com/anoma/juvix/issues/2059
