### ISSUE TITLE
LLVM runtime debugging mode

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#211]
Proposal:

- Add a `Config` data structure, fixed at LLVM-compile-time (so Juvix runtime, when Juvix is compiling to LLVM code), which can be read by a reader monad in all the `Codegen` code.
- Initially this data structure just has a `debugEnabled` boolean member.
- If `debugEnabled` is true, the generated LLVM code will include:
  - Sanity checks of various lookup operations which could fail, where instead of segfaulting (if we didn't sanity-check) we print a nice error message and exit.
  - A `printf` of the initial state (all data in memory)
  - A `printf` at the end of each call to `reduce` (printing out the primary pair rewritten and all changes made to memory)
  - A `printf` at the end of the final state (all data in memory)
  - More `printf` calls in other places if we find them necessary to debug

cc @mariari thoughts?

**Comment by mariari** [comment]
A reader monad over `Config` sounds like the nice and simple way of doing it.

We'll probably make it a single `effect` record.

I'm guessing we will also put certain optimizations behind this as well at later points, or even ways to tweak the ratio between bespoke and inets.

**Comment by cwgoes** [comment]
Let's think about this, but not in the context of interaction nets
