### ISSUE TITLE
Qualified constructors

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#2111]
Consider this issue an unfinished draft.

- It has been brought up in https://github.com/anoma/juvix/issues/2074, that it would be useful to have the option to refer to constructors by their type. E.g. `List.nil`, `Maybe.nothing`, etc.

I see two approaches:
1. Add special rules to the scoper.
2. Implicitly declare a local module after each `type` definition. (Agda's approach).
For instance the implicit module defined for the `List` type would be:
```
module List;
  nil : {A : Type} -> List A;
  nil := nil (the constructor); 

  :: :  {A : Type} -> List A;
  :: h hs := h :: (the constructor) hs; 
end;
```
Now, this module would still require some special rules (I assume #2110).
See the following example:
```
module Example;
module M;
  type Unit := unit : Unit;
end;

-- we can import Unit as a normal module (nothing special)
open M using {module Unit};

u1 : M.Unit;
u1 := Unit.unit;

-- Special rule: If the type is brought into scope, the associated module needs
-- to be brought into scope with the same name. 
open M using {Unit as Unit2};

u2 : Unit2;
u2 := Unit2.unit;

open Unit2;
open M;

-- Special rule: This should not cause an ambiguity error. 
-- Note that `unit` could refer to both the constructor and the 
-- auxilliary function defined in the implicit module.
u3 : Unit2;
u3 := unit;
```
Some of the advantages of the implicit module approach is that it plays more nicely with module features. (TODO explain)

**Comment by lukaszcz** [comment]
Actually, we don't even need this issue to solve the problem of
* #2074 
All we need is to be able to qualify constructors with a module name. So one can write:
```
import M open hiding {c};

f : {A : Type} -> A -> A;
f c := B; 

g : Ty -> Ty;
g M.c := D;
```
I think this is already allowed.

**Comment by janmasrovira** [comment]
- Since https://github.com/anoma/juvix/pull/2260, we can refer to constructors though the local module that is automatically inserted for every type definition. E.g. `Nat.suc`. So we close this.
