### ISSUE TITLE
Makefile.generic prints spurious messages about missing dependency files

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2124]
The error is present in the last merged CI runs. See for example,

- https://github.com/anoma/juvix/actions/runs/5066589012/jobs/9096577581#step:8:1

```
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/arch/wasi.d: No such file or directory
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/defs.d: No such file or directory
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/funcall/stacktrace.d: No such file or directory
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/info.d: No such file or directory
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/io.d: No such file or directory
Makefile.generic:270: _build.native64-debug/src/juvix/arch/wasi.d: No such file or directory
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/mem/alloc.d: No such file or directory
Makefile.generic:270: _build.wasm32-wasi-debug/src/juvix/mem/gens.d: No such file or directory
Makefile.generic:270: _build.native64-debug/src/juvix/defs.d: No such file or 
```

**Comment by lukaszcz** [comment]
I don't think this is failing. The makefile just says that the dependency files have not yet been generated. I don't know how to disable these messages. They happen because the generic makefile includes the dependency files, and `make` prints this if they don't exist, but it also has rules to generate them, so it works in the end.

**Comment by lukaszcz** [comment]
I think one needs to use
```
-include $(DEPS)
```
instead of
```
include $(DEPS)
```
in `Makefile.generic`.

Then it shouldn't print the messages (see https://www.gnu.org/software/make/manual/html_node/Include.html)

**Comment by lukaszcz** [comment]
Well, it doesn't seem to work. I can't get rid of the messages, but I'll try more.

**Comment by lukaszcz** [comment]
> Well, it doesn't seem to work. I can't get rid of the messages, but I'll try more.

No, it does work. I was editing the wrong Makefile.
