### ISSUE TITLE
Encode concrete algebraic data types into field elements for VampIR input

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2135]
There could be a separate command in the Juvix compiler (like e.g. `juvix vampir encode`) which takes a json/yaml or whatever file with a high-level specification of function inputs (Juvix datatype elements) and produces a VampIR json file with the data encoded into field elements according to the same encoding which then Juvix would use for non-numeric arguments to `main`. The responsibility for specifying the encoding is left with Juvix, which just needs to expose an interface to translate into VampIR json.

Notes:
* Only elements of concrete (non-polymorphic) first-order (not storing functions) algebraic data types can be encoded. So we can encode elements of e.g. `List Nat` but not `List A` for an arbitrary `A`.
* Recursive datatypes (e.g. `List`) need to be unrolled. It should be possible to specify the unrolling depth globally on the command line (reuse the `--unroll` flag or have a separate `--unroll-types` flag) and per-type by pragmas:
```haskell
{-# unroll: 50 #-}
type List (A : Type) := ...;
```

The encoding command, in addition to the input json/yaml file specifying the datatype values, could take the Juvix source to read the datatype definitions and possible unrolling depth pragmas, e.g. with a `--source` or `-s` flag:
```
juvix vampir encode data.yaml -s program.juvix
```
If working inside a project, the `--source` flag could be omitted, and then the main source file path would be inferred from `juvix.yaml`:
```
juvix vampir encode data.yaml
```

**Comment by paulcadman** [comment]
We no longer support the vamp-ir backend.
