### ISSUE TITLE
Constant folding

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2154]
Functions whose all arguments are values can simply be evaluated with the Core evaluator and the calls replaced with the obtained values. This optimisation would affect all backends.

Perhaps we might want to restrict this to non-recursive functions, or those whose termination has been proven and not just declared with `terminating`.

**Comment by mariari** [comment]
There are some good literature on this technique from the scheme programming language. Lookup 『Partial Evaluation』in regards to scheme.

There was a lot of work put into one scheme compiler of this nature and got some decent performance and had lessons for other projects IIRC. 

Sorry I could not produce the exact project from memory

**Comment by lukaszcz** [comment]
Yes, partial evaluation is a nice and powerful optimization. A classic textbook on the subject is available online:
* [Jones, Gomard, Sestoft: Partial Evaluation and Automatic Program Generation](https://www.itu.dk/people/sestoft/pebook/)

But I was thinking of something more basic and easier to implement -- just "constant folding" when you know all arguments in a function application and you can unambiguously compute the result and replace the call with it. This works because of referential transparency in a purely functional language. It's also a common basic optimization in compilers for imperative languages (but then you restrict to things you know have no side effects). With partial evaluation you partially evaluate programs when some inputs are not known.
