### ISSUE TITLE
Use GHC docker images from benz0li / ghc-musl to build linux binaries

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2166]
We currently build our own GHC Docker images for alpine linux to produce the statically linked binaries for linux. (As a reminder we do this rather than use the GHC published binaries because of https://gitlab.haskell.org/ghc/ghc/-/issues/20266)

I've found a project which does the same thing as us and produces public Docker containers: https://github.com/benz0li/ghc-musl. These containers are used to build the pandoc releases.

We should switch to using these.

As a bonus they build aarch64 images so we could start publishing linux-aarch64 juvix binaries too (the blocker for this is the availability of aarch64,  musl compatible stack releases) .

**Comment by benz0li** [comment]
@paulcadman Please test first and ping me if something does not work as expected.

Be aware of the following:

1. My images are built using Hadrian, from source, without docs
2. The [security policy](https://github.com/benz0li/ghc-musl/security/policy), especially about prior versions of GHC

**Comment by benz0li** [comment]
Regarding *Stack* see issue https://github.com/commercialhaskell/stack/issues/6141.

ℹ️ It will be part of `glcr.b-data.ch/ghc/ghc-musl` as soon as official binaries for both architectures are available.

**Comment by benz0li** [comment]
In addition: You would have to use *Cabal* (the tool) instead of *Stack*, then.

**Comment by paulcadman** [comment]
Thanks for the help @benz0li , and for maintaining these Docker containers!

**Comment by benz0li** [comment]
I hope that there will be proper GHC bindists for [Linux (AArch64) Alpine releases](https://www.haskell.org/ghc/download_ghc_9_6_2.html#linux_aarch64) some time in the future.

Cross reference: https://github.com/commercialhaskell/stack/issues/6142

**Comment by benz0li** [comment]
@paulcadman I am thinking of including `stack` in the `glcr.b-data.ch/ghc/ghc-musl` image.

Cross reference: https://github.com/benz0li/ghc-musl/issues/2
