### ISSUE TITLE
Format command should not exit with 1 when needs formatting

### ISSUE THREAD

**Issue by vrom911** [anoma/juvix#2171]
Currently, the command exit with code 1 when file is not formatted and the output of the command differs from the initial content of the module.

However, I would expect it to succeed even if file is not formatted. The purpose of the command is to format, and if it does so uit should not fail.

**Comment by paulcadman** [comment]
We discussed this. Always returning exit code 0, regardless of the formatter result is OK in when formatting a single file.

We should continue to use exit code 1 for unformatted files when using `--check` or when running the formatter on a Juvix project.
