### ISSUE TITLE
Allow local module opening

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2185]
So that the scope of opening can be precisely controlled, e.g.,
```
module leto;

import Stdlib.Prelude open;
import Stdlib.Data.Nat.Ord as Nat.Ord;

main : Bool;
main := let open Nat.Ord in 3 > 4;
```

This is possible e.g. in Ada's module system: https://learn.adacore.com/courses/intro-to-ada/chapters/modular_programming.html#using-a-package

Related issue:
* #1792

**Comment by janmasrovira** [comment]
+1 for open statements in let expressions.

Question: should import statements also be allowed in let expressions?
