### ISSUE TITLE
Allow module assignment

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2186]
We can rename identifiers by introducing a new definition. This is not possible with modules, but would be useful, especially doing this locally in a let. For example:
```
module letm;

import Stdlib.Prelude open;
import Stdlib.Data.Nat.Ord;
import Stdlib.Data.Int.Ord as Int.Ord;

module N := Stdlib.Data.Nat.Ord;

main : Bool;
main := let module I := Int.Ord in 3 N.> 4 || 4 I.> 3;
```
Ada has a similar feature: https://learn.adacore.com/courses/intro-to-ada/chapters/modular_programming.html#renaming

Related issue:
* #1792

**Comment by lukaszcz** [comment]
The
```
module M := N
```
syntax is useful when we have parameter, because then one can write
```
module M := N P1 P2
```
Otherwise, perhaps a general aliasing mechanism that would work with any kind of name would be more useful:
```
alias N as M;
alias Constructor as C;
```

**Comment by paulcadman** [comment]
Closing in favour of https://github.com/anoma/juvix/issues/2429
