### ISSUE TITLE
Aliasing

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2188]
A general aliasing mechanism for any name.

Top-level:
```
alias OldName as NewName;
```
Local:
```
let
   alias OldName as NewName;
   alias Constructor as C;
   alias Module as M;
in
...
```

The idea is that the alias is completely interchangeable with the aliased (old) name within the scope of the alias, including in pattern matching, qualification, module opening.

See the discussions in:
* #2074 
* #2186

**Comment by lukaszcz** [comment]
Ada has a somewhat similar renaming mechanism:
https://people.cs.kuleuven.be/~dirk.craeynest/ada-belgium/docs/rm83/lrm-08-05.html

**Comment by janmasrovira** [comment]
This can be useful. I'd probably put `alias` under the `syntax` keyword however.

**Comment by lukaszcz** [comment]
yes, makes a lot of sense to put this under `syntax`, because the idea is that it's purely syntactic

**Comment by lukaszcz** [comment]
But for now we don't allow local `syntax` definitions. Maybe we should?

**Comment by janmasrovira** [comment]
> But for now we don't allow local `syntax` definitions. Maybe we should?

I think we should.

> But another way to think about it is that it's not actually introducing a new syntax/language construct, like operators or iterators. It's more about name scoping/resolution than pure syntax. So it could be more appropriate without the syntax keyword.

To me it is easier to think of it as a syntactical synonym. Also, it is nice to not have to reserve the keyword `alias`.

**Comment by lukaszcz** [comment]
The following syntax seems reasonable:
```
syntax alias NewName := OldName;
```
This could be used locally in lets as well. The addition of new names in syntax definitions is probably easier after #2270.
