### ISSUE TITLE
Comment before the import section leads to the parse error

### ISSUE THREAD

**Issue by vrom911** [anoma/juvix#2190]
When trying to typecheck this module:

```juvix
module HelloWorld;

------------------------------
--- Standard library imports
------------------------------

open import Stdlib.Prelude;

main : IO;
main := printStringLn "Hello world!";
```

I get the error:

```shell
> juvix typecheck HelloWorld.juvix                                                                                                                                                                                 
/.../HelloWorld.juvix:8:5: error:
/.../HelloWorld.juvix:8:5:
  |
8 | open import Stdlib.Prelude;
  |     ^
expecting "--", "{-", :=, or newline
```

However, when I remove the comment that is coming after the module and before the import:

```juvix
module HelloWorld;

open import Stdlib.Prelude open;

main : IO;
main := printStringLn "Hello world!";
```

It compiles just fine.

This is new behaviour that started with `0.4.0` juvix version. Before it was not the error.

**Comment by janmasrovira** [comment]
the problem is that `---` is reserved for introducing judoc comments, try
```
------------------------------
-- Standard library imports
------------------------------
```

I'm a bit confused about why this was introduced in 0.4.0, since we had judoc comments much before that

**Comment by janmasrovira** [comment]
After testing it I see that parsing more than two consecutive '-' as a comment does not work. I.e. `----` is not parsed as a valid comment.
