### ISSUE TITLE
[BUG] Juvix to VampIR transpilation produces uncompilable VampIR code

### ISSUE THREAD

**Issue by bazzilic** [anoma/juvix#2191]
**Describe the bug**
Transpiling [this code](https://gist.github.com/bazzilic/c0a88e62808d781b50c1d1d0651648eb) to VampIR produces an uncompilable code. VampIR compiler then fails with the following error:

``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnableDetermineType { v: Variable { name: Some("output_note_2_value"), id: 95 } }', src/transform.rs:1234:75``

I think the culprit is this particular part of the generated VampIR code, which does not look like a valid VampIR expression:

![image](https://github.com/anoma/juvix/assets/1805832/e7ea472d-6ae0-4fc0-b637-f3962daf2fdb)

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.4
- Juvix version: 0.4.0-925d7cb
- Vamp-IR compiler version: 0.1.2 (commit 778d5b5)

**To Reproduce**

1. Download [this Juvix source code file](https://gist.github.com/bazzilic/c0a88e62808d781b50c1d1d0651648eb) 
2. Execute `juvix compile -t vampir ./bug.juvix` to produce `bug.pir`
3. Execute `vamp-ir halo2 compile --source bug.pir --output bug.halo2`
4. Vamp-IR compilation will fail

**Comment by lukaszcz** [comment]
You didn't separate all fields with commas -- there are no commas when there is a newline. So the YAML parser apparently considered "output_note_1_belongs_to_me output_note_2_value" to be the name of a single variable with a space in the middle. There should be a check whether the name is a valid VampIR name - I'll add that.

**Comment by lukaszcz** [comment]
Besides, this should just work without the `argnames` pragma, because now Juvix by default uses the names of arguments to `main` when these are unambiguous.
