### ISSUE TITLE
Properly propagate types in the LLVM backend.

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#221]
In order to be generic on the kinds of interaction nets available, the code in [Codegen/Types](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Backends/LLVM/Codegen/Types.hs#L191)
are of type
```haskell
Type -> Type
```

This is fine on its own however, this has made most functions in [Codegen/Graph](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Backends/LLVM/Codegen/Graph.hs#L71) be parameterized by an extra type.

This also forces [Net/Defs](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Backends/LLVM/Net/EAC/Defs.hs) to alias all these functions. However, I think this is fine, as even if we take a reader monad approach, this will eventually be used(?).

The parameterization could be done much better, for example, a reader monad over these definitions with a struct/map of types to inject would scale better and not be as tedious.

**Comment by cwgoes** [comment]
Out of date
