### ISSUE TITLE
Type inference generates ill-typed terms

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2235]
If you run `from-concrete` on
```
module inferbug;

import Stdlib.Prelude open;

myfor : {A B : Type} → (A → B → A) → A → List B → A;
myfor := foldl {_} {_};

main : Nat;
main := fst (myfor λ{(a, b) x := b + x, a} (0, 0) (1 :: 2 :: 3 :: nil));
```
the definition generated for `myfor` is
```
def myfor : Π A : Type, Π B : Type, (A → B → A) → A → List B → A :=
  λ(_ω1080 : Type) λ(_ω1080' : Type) foldl _ω1080' _ω1080';
```
A wrong type was inferred for the second argument of `foldl` which makes `myfor` ill-typed, but the type-checker doesn't complain.

On `main` this seems to generate no further problems, because we mostly ignore the types. But in one of my development branches it causes a crash.

**Comment by janmasrovira** [comment]
tip: you can use `juvix dev internal typecheck inferbug.juvix --print-result` to see the result of inference in Internal syntax before translating to Core. 

The output for `myfor` is:
```
myfor : {A : Type} → {B : Type} → (A → B → A) → A → List B → A
myfor {_ω762} {_ω762} := foldl {_ω762} {_ω762}
```
