### ISSUE TITLE
Types in ADT syntax are printed incorrectly

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2277]
Formatting
```
type List (A : Type) := nil | cons A (List A)
```
results in
```
type List (A : Type) :=
  | nil
  | cons A List A;
```
The parentheses are missing.

I would also advocate avoiding splitting ADT syntax definitions into multiple lines if the user didn't do it themselves, unless they are too long.

**Comment by paulcadman** [comment]
The missing parentheses issue is fixed in https://github.com/anoma/juvix/pull/2284

**Comment by paulcadman** [comment]
I've spun out https://github.com/anoma/juvix/issues/2286 for the formatting suggestion. 

The remainder of this is closed by https://github.com/anoma/juvix/pull/2284
