### ISSUE TITLE
Do not format single line ADT definitions onto multiple lines

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2286]
Spun out from https://github.com/anoma/juvix/issues/2277

@lukaszcz made the following suggestion:

> I would also advocate avoiding splitting ADT syntax definitions into multiple lines if the user didn't do it themselves, unless they are too long.

Currently if the user writes:

```
type shape := triangle | square | pentagon;
```

The formatter transforms it to:

```
  type shape :=
    | triangle
    | square
    | pentagon;
```

The proposal here is for the formatter to avoid splitting and keep the definition on a single line. In particular the formatter should not add a leading `|` before the first constructor.

**Comment by janmasrovira** [comment]
In general, the formatter does not try to respect the user's newlines (except for comments). This has the advantage that we can normalize spacing. On the other hand, not everyone may like it. We can revisit this decision if you want.

In my opinion adt constructors should be in separate lines even if they fit in a line. This is the style that we are following in our haskell codebase as well. Personally, I prefer the vertical split as it is easier for me to visually parse (specially if there are more than just a couple of constructors).

>  In particular the formatter should not add a leading | before the first constructor.

We have discussed this in the past. We felt that the homogeneity of adding the first `|` (as long as there are more than one constructor) overweighted the redundantness.

**Comment by lukaszcz** [comment]
> In general, the formatter does not try to respect the user's newlines (except for comments). This has the advantage that we can normalize spacing. On the other hand, not everyone may like it. We can revisit this decision if you want.
> 
> In my opinion adt constructors should be in separate lines even if they fit in a line. This is the style that we are following in our haskell codebase as well. Personally, I prefer the vertical split as it is easier for me to visually parse (specially if there are more than just a couple of constructors).

This is a question how strict we want to be with the style, and what kind of style we want. I would agree that if there are many constructors then it's more readable to have them on separate lines.

But I'm not sure about the common case with two or three constructors. E.g.
```
type List A := nil | cons A (List A);
```
seems more concise and not any less readable than
```
type List A :=
  | nil
  | cons A (List A);
```
But again, we should maybe just decide on the style and enforce it.

> 
> > In particular the formatter should not add a leading | before the first constructor.
> 
> We have discussed this in the past. We felt that the homogeneity of adding the first `|` (as long as there are more than one constructor) overweighted the redundantness.

We have discussed this with respect to the GADT syntax, and there I agree. Here, I meant the situation with short syntax where all constructors fit on a single line.

**Comment by janmasrovira** [comment]
> In general, the formatter does not try to respect the user's newlines (except for comments). This has the advantage that we can normalize spacing. On the other hand, not everyone may like it. We can revisit this decision if you want.
> 
> In my opinion adt constructors should be in separate lines even if they fit in a line. This is the style that we are following in our haskell codebase as well. Personally, I prefer the vertical split as it is easier for me to visually parse (specially if there are more than just a couple of constructors).
> 
> > In particular the formatter should not add a leading | before the first constructor.
> 
> We have discussed this in the past. We felt that the homogeneity of adding the first `|` (as long as there are more than one constructor) overweighted the redundantness.

We have agreed to follow this approach for regular ADT's as well.
