### ISSUE TITLE
linux static build juvix version shows UNKNOWN for hash and date

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2294]
You can clearly see the issue by looking at the nightly-build release:

https://github.com/anoma/juvix-nightly-builds/releases/tag/nightly-2023-08-11-0.4.2-UNKNOWN

The version string for the published Juvix binary is `0.4.2-UNKNOWN`, instead of `0.4.2-<hash>`.

## Cause?

After merging https://github.com/anoma/juvix/pull/2275 we run the linux static build inside glcr.b-data.ch/ghc/ghc-musl:9.4.5. For some reason the [gitrev](https://hackage.haskell.org/package/gitrev) library cannot detect the git info in the Juvix checkout as part of the build, and is substituting UNKNOWN instead.

I cannot reproduce this by running the build locally in the `ghc-musl:9.4.5` docker container (i.e when I do a manual build, the version git information is populated correctly). So the bug may come from a bad interaction between the docker container an the `checkout` action in the GitHub action build.

**Comment by jonaprieto** [comment]
It's probably because we're not fetching all the git info. To fetch all history and the tags, I'd add the following to the nightly-builds ci to corresponding places, e.g: 

```
...
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ...
...
```

**Comment by paulcadman** [comment]
> It's probably because we're not fetching all the git info.

Unfortunately the fetch-depth trick doesn't work https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5924999532/job/16063576847

**Comment by benz0li** [comment]
Could it be that https://github.com/anoma/juvix-nightly-builds/blob/976dae867348b7bf388b501222b66616b8feda58/.github/workflows/release-nightly.yaml#L6-L9 + https://github.com/anoma/juvix-nightly-builds/blob/976dae867348b7bf388b501222b66616b8feda58/.github/workflows/release-nightly.yaml#L29 does not *exactly* the same as https://github.com/anoma/juvix-nightly-builds/blob/859869e0e67ead7bf88cb9e5eb82e102025a581d/.github/workflows/release-nightly.yaml#L21?

I know that would be weird. But you never know...

**Comment by paulcadman** [comment]
> Could it be that https://github.com/anoma/juvix-nightly-builds/blob/976dae867348b7bf388b501222b66616b8feda58/.github/workflows/release-nightly.yaml#L6-L9 + https://github.com/anoma/juvix-nightly-builds/blob/976dae867348b7bf388b501222b66616b8feda58/.github/workflows/release-nightly.yaml#L29 does not _exactly_ the same as https://github.com/anoma/juvix-nightly-builds/blob/859869e0e67ead7bf88cb9e5eb82e102025a581d/.github/workflows/release-nightly.yaml#L21?
> 
> I know that would be weird. But you never know...
> 
> (Not only the image was changed in In [anoma/juvix-nightly-builds@d0dbb42](https://github.com/anoma/juvix-nightly-builds/commit/d0dbb422128d08264aead471d960dc36ec7558be), but also these lines.)

Thanks for looking at this. My understanding is that `${{ github.event.inputs.ref }}` would become `main` in the default case (i.e no input ref is specified). Do you have a different understanding, as this could indeed be the issue if so.

**Comment by benz0li** [comment]
> Do you have a different understanding, as this could indeed be the issue if so.

No.

`${{ inputs.ref }}` should be sufficient, though. Single or double quotes does not matter. But you should define the type.

```yaml
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "the repository ref to build"
        required: true
        default: "main"
        type: string
```

I do not use GitHub Actions myself. I am more of a GitLab guy...

**Comment by benz0li** [comment]
See the difference:

https://github.com/anoma/juvix-nightly-builds/actions/runs/5828443441/job/15806173529#step:3:27 vs https://github.com/anoma/juvix-nightly-builds/actions/runs/5915039870/job/16040920936#step:3:28

**Comment by paulcadman** [comment]
> See the difference:
> 
> https://github.com/anoma/juvix-nightly-builds/actions/runs/5828443441/job/15806173529#step:3:27 vs https://github.com/anoma/juvix-nightly-builds/actions/runs/5915039870/job/16040920936#step:3:28

You mean in the second one there's a warning about default branch during `git init`? I think this can be explained because the second build uses a newer version of the git client. As far as I can see they both checkout the correct ref in the "checking out the ref" step. However the difference in git version may account for the UNKNOWN error in itself. I can try locally with `git version 2.38.4` to see if I can reproduce the issue with this git version and the haskell gitrev library, I am using git 2.39.1 on my machine.

**Comment by benz0li** [comment]
Simply revert the `workflow_dispatch` part to the old state and check, if it works again.

If not, there might be something missing in my image.

**Comment by benz0li** [comment]
Related to https://github.com/acfoltzer/gitrev/issues/23?

**Comment by benz0li** [comment]
Solution is maybe https://github.com/haskell/cabal/issues/7355#issuecomment-820553822.

In this case adding

```
extra-source-files: ../.git/HEAD
                  , ../.git/refs/heads/main
```

to the cabal file.

**Comment by paulcadman** [comment]
> Simply revert the `workflow_dispatch` part to the old state and check, if it works again.
> 
> If not, there might be something missing in my image.

Good idea - I will try that.

**Comment by paulcadman** [comment]
> Solution is maybe [haskell/cabal#7355 (comment)](https://github.com/haskell/cabal/issues/7355#issuecomment-820553822).
> 
> In this case adding
> 
> ```
> extra-source-files: ../.git/HEAD
>                   , ../.git/refs/heads/main
> ```
> 
> to the cabal file.

This an issue with cabal install sandboxed builds, the `.git` folder is not available. This does not affect `stack install`. This is the reason why we must use stack for releases.

**Comment by benz0li** [comment]
Still the same...

Two things:

* [jobs.<job_id>.steps[*].shell](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell): `bash` vs unspecified
* [jobs.<job_id>.steps[*].env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv): Setting `LANG` required?  

There are no locale-related `ENV` set in the [Dockerfile](https://github.com/benz0li/ghc-musl/blob/dfc3fe1a7a60394f08290ceba24ba02dc5efe9b3/prior/9.4.5.Dockerfile).

**Comment by paulcadman** [comment]
> P.S.: The following images are more recent and already include an unsupported (= self-built), _statically linked_ binary of Stack (v2.11.1):
> 
> * `glcr.b-data.ch/ghc/ghc-musl:9.6.2`
> * `glcr.b-data.ch/ghc/ghc-musl:9.4.6`
> * `glcr.b-data.ch/ghc/ghc-musl:9.2.8`

Great - this means we won't need to install stack when we next upgrade the LTS stackage resolver.

> 
> P.P.S.: [The Haskell Tool Stack](https://github.com/commercialhaskell/stack) [switched to `glcr.b-data.ch/ghc/ghc-musl:9.4.6`](https://github.com/commercialhaskell/stack/blob/fbd6542b8102ab25e0c9652b4ab8c4825acfae35/stack.yaml#L33) to build Stack.

Well done!

**Comment by benz0li** [comment]
Switch to githash?: https://hackage.haskell.org/package/githash

**Comment by benz0li** [comment]
Maybe @snoyberg has an idea why this happens.

The Haskell Tool Stack switched to githash some time ago: https://github.com/commercialhaskell/stack/commit/a0276aea747f3d8f4150e3ff881f5b70068b32b4

**Comment by paulcadman** [comment]
> Maybe @snoyberg has an idea why this happens.
> 
> The Haskell Tool Stack switched to githash some time ago: [commercialhaskell/stack@a0276ae](https://github.com/commercialhaskell/stack/commit/a0276aea747f3d8f4150e3ff881f5b70068b32b4)

Thanks for looking into this, we're planning to remove this information from the version string to avoid these issues https://github.com/anoma/juvix/issues/2130

**Comment by paulcadman** [comment]
> Switch to githash?: https://hackage.haskell.org/package/githash

I used githash - I see this error in the container when evaluating template haskell:

```
/__w/juvix-nightly-builds/juvix-nightly-builds/src/Juvix/Extra/Version.hs:16:13: error:
[8529](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8530)
    • Exception when trying to run compile-time code:
[8530](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8531)
        GHEGitRunFailed "." ["rev-parse","--show-toplevel"] (ExitFailure 128) "" "fatal: detected dubious ownership in repository at '/__w/juvix-nightly-builds/juvix-nightly-builds'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /__w/juvix-nightly-builds/juvix-nightly-builds\n"
[8531](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8532)
      Code: tGitInfoCwd
[8532](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8533)
    • In the Template Haskell splice $$tGitInfoCwd
[8533](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8534)
      In the expression: $$tGitInfoCwd
[8534](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8535)
      In an equation for ‘gitInfo’: gitInfo = $$tGitInfoCwd
[8535](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8536)
   |
[8536](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8537)
16 | gitInfo = $$tGitInfoCwd
[8537](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8538)
   |             ^^^^^^^^^^^
[8538](https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228#step:10:8539)
Completed 179 action(s).
```

https://github.com/paulcadman/juvix-nightly-builds/actions/runs/5951105777/job/16140262228

So there's a permissions issue in the container which makes the git command fail.

**Comment by paulcadman** [comment]
> So there's a permissions issue in the container which makes the git command fail.
> 
> I will try running `chown -R $(id -un):$(id -gn) .` in the container before running the Juvix build as a workaround.

This workaround fixes the issue. @benz0li I'm not sure if this is an issue with the container, or it's how permissions in containers are supposed to work? Should I raise an issue in https://github.com/benz0li/ghc-musl for this?

**Comment by benz0li** [comment]
> @benz0li I'm not sure if this is an issue with the container, or it's how permissions in containers are supposed to work?

If a local build succeeds in the `glcr.b-data.ch/ghc/ghc-musl:9.4.6` image, I do not consider this an issue with the image.

> Should I raise an issue in https://github.com/benz0li/ghc-musl for this?

Rather not.

**Comment by paulcadman** [comment]
> If a local build succeeds with `glcr.b-data.ch/ghc/ghc-musl:9.4.5`, I do not consider this an issue with the image.

I have not tried this locally, it's not easy for me to do this as I'm using a mac. Agreed we don't need to raise this unless it can be reproduced locally. Thanks

**Comment by benz0li** [comment]
> I have not tried this locally, it's not easy for me to do this as I'm using a mac.

My machine is a MacBook Pro. Docker Desktop should do the job.

And because the image is multi-arch (`linux/amd64`, `linux/arm64/v8`), everything runs fine/natively, even on Apple silicon.

**Comment by paulcadman** [comment]
> My machine is a MacBook Pro. 'Docker Desktop' or Podman should do the job.
> 
> And because the image is multi-arch (`linux/amd64`, `linux/arm64/v8`), everything runs fine/natively, even on Apple silicon.

You're right! I will try it then.

**Comment by benz0li** [comment]
## Dockerfile

```Dockerfile
ARG GHC_VERSION=9.4.5
ARG STACK_VERSION=2.11.1

FROM glcr.b-data.ch/commercialhaskell/ssi:${STACK_VERSION} as ssi

FROM glcr.b-data.ch/ghc/ghc-musl:${GHC_VERSION}

ARG STACK_VERSION

ENV STACK_VERSION=${STACK_VERSION}

COPY --from=ssi /usr/local/bin/stack /usr/local/bin/stack
```

## Host

```bash
docker build -t ghc-musl-stack .
```

```bash
docker run --rm -ti ghc-musl-stack bash
```

## Container

```bash
apk add --no-cache clang14
```

```bash
git clone https://github.com/anoma/juvix.git && cd juvix
```

```bash
make runtime LIBTOOL=llvm14-ar
```

```bash
stack install --no-install-ghc --system-ghc --ghc-options='-split-sections' --flag juvix:static
```

ℹ️ And yes: Juvix also builds fine on/for Linux AArch64 aka `linux/arm64/v8`.

**Comment by paulcadman** [comment]
> > My machine is a MacBook Pro. 'Docker Desktop' or Podman should do the job.
> > And because the image is multi-arch (`linux/amd64`, `linux/arm64/v8`), everything runs fine/natively, even on Apple silicon.
> 
> You're right! I will try it then.

I built locally and `juvix --version` works as expected in the container. So the issue is with how GitHub actions is configuring permissions in the container. Thanks for the steps @benz0li
