### ISSUE TITLE
Syntax change proposal for fixity declarations

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#2330]
Currently fixity declarations use yaml syntax. E.g:
```
syntax fixity additive {arity: binary, assoc: left, above: [comparison, range, cons]};
```
The advantage is that we can use an existing familiar syntax and parser.
The problem is that there is no currently available parser that has location information for the parsed items. This makes it impossible to properly highlight and give go-to information to the parsed identifiers.

We could write a custom yaml parser for the subset that we support in the fixity declarations. But the `yaml` syntax does not really play well with juvix syntax.
1. We use `;` instead of `,` to separate items.
2.  We support `:` as a valid character. So `assoc:` is a valid juvix identifier.

We could implement a custom lexer, but that would make the implementation slightly more involved. Also, having special lexical rules in some specific context could be confusing.

I propose an alternative record-inspired syntax. E.g.
```
syntax fixity rapp := binary {assoc := right; above := [lapp; rapp]; below := [rapp] }
syntax fixity rapp := unary {assoc := postfix; below := [x; y] }
```
In this syntax we have two "constructors": `binary` and `unary`. The fixity properties are given in the same way we create records. Note that for lists we use the builtin list syntax `[a;b;c]`.

**Comment by lukaszcz** [comment]
I think that's a fine idea, but then perhaps to keep things consistent we should introduce similar syntax in other places we use YAML (except pragmas, which allow unknown fields for backward compatibility): currently that's just fixities and iterators.
