### ISSUE TITLE
Proposal: Use a Juvix source file to define a package instead of YAML

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2336]
This issue is for discussion of the idea to replace the current juvix.yaml package file format with a Juvix source file.

Some advantages of using Juvix instead of YAML:

1. Users could take advantage of Juvix tooling when managing configuration (e.g when debugging missing/misspelled fields)
2. Typed configuration (user would import a module with the types / records used in configuration)
3. Line / column information when parsing (this is useful when reporting dependency errors and is lacking in the Haskell yaml parsers)

# Prior art

Some languages use language source code to define builds/packages already:

Lean4 / lake
https://github.com/leanprover/lake/blob/a2ced44b7e5e30c2a6b84b420e1bbdd8d6d8e079/examples/targets/lakefile.lean

Swift / swift package manager
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html

Kotlin / gradle
https://docs.gradle.org/current/userguide/kotlin_dsl.html

**Comment by lukaszcz** [comment]
I'm in favour of the idea. Would make it easier to write (in Juvix) tools manipulating Juvix packages and to do meta-programming with package information later (no need for YAML parser in Juvix).

**Comment by janmasrovira** [comment]
:+1:

**Comment by jonaprieto** [comment]
Perhaps something like this:

```
-- Package.juvix

module MyPackage;

import App;

examplePackage := mkPackage {
  name := "MyPackage";
  version := [ 0 ; 3 ; 1 ];
  main := App.main;
  dependencies: [
    ( "stdlib" , [ 0 ; 1 ; 0 ]);
    ("juvix-con , [ 0 ; 0 ; 1 ]);
};

```

**Comment by paulcadman** [comment]
Example package / dependency type. Version String would be parsed when evaluated.

```
module Package;

type Dependency :=
  | pathDependency {path : String}
  | gitDependency {
      url : String;
      name : String;
      ref : String
    };

type Package :=
  mkPackage {
    name : String;
    version : String;
    dependencies : List Dependency;
    main : Maybe String;
    buildDir : Maybe String
  };

package : Package :=
  mkPackage@{
    name := "quickcheck";
    version := "0.7.1";
    main := just "Example.juvix";
    buildDir := nothing;
    dependencies :=
      [ pathDependency (
        path := ".juvix-build/stdlib/"
        )
      ; gitDependency (
          url := "https://github.com/anoma/juvix-stdlib";
          name := "stdlib";
          ref := " ad27db542e0b220e117dec22f11ed6de78892f72"
        )
      ]
  };
```

Alternatively we could define types for Semantic Version, but this is not convenient to use:

```
type SemVer :=
  mkSemVer {
    major : Nat;
    minor : Nat;
    patch : Nat;
    release : Maybe String;
    meta : Maybe String
  };
```
