### ISSUE TITLE
Phantom Types in LLVM

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#234]
It would be nice for the calling conventions of all defined functions to be type checked. Currently this process is error prone and manually done.

What could be done, is define phantom type that reflects the type of the LLVM variable, and have the type checker make sure we make no mistakes.

We can take this further to all LLVM data, for example `getElementPointer` takes the type and the location, it'd be nice if we could index and get this
- This one is slightly unrealistic, since Haskell lacks dependent types, and indexing into the type would be hacky without this feature.

**Comment by cwgoes** [comment]
I quite like this idea. We *can* do some indexing (see e.g. [this blog post](https://www.schoolofhaskell.com/user/konn/prove-your-haskell-for-great-safety/dependent-types-in-haskell)), it tends to be very inefficient & un-ergonomic though, and I'm not sure if it's worth the time.

**Comment by cwgoes** [comment]
Use compilation strategy for 0 usage stuff
