### ISSUE TITLE
Add do-notation

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#2355]
- Depends on #2354.

We would support three kinds of statements (bind, let, expression), and we could borrow the syntax from haskell.
```
do {
  <var> <- <expr>; -- bind
  let <fundef>; -- pure let
  <expr>; -- monadic expression
};
```

In the future we can consider some extensions:
1. Allow patterns of single constructor types on the left of `<-`.
2. @paulcadman mentioned [Idris !-notation](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html#notation).
3. Do notation for `Applicative`.

**Comment by paulcadman** [comment]
Wait until we have use-cases in Anoma applications.
