### ISSUE TITLE
Types identifiers ignored in implicit arguments within a type sig.

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2413]
Consider the following program, which should type check, but it does not.

```
module Example;

type Nat := zero | suc Nat;

sadness : {Nat} -> Nat
  | {_} := zero;
```

The argument `Nat` is mistakenly considered an arbitrary name
in the type sig. and not as the inductive type defined above.
Priority should be given to types over argument names.
Under the same idea, this other function doesn't pass the TC.

```
please : {Nat} -> Nat  := zero;
```

As a remedy, the following makes Juvix happy.

```
please : {x : Nat} -> Nat := zero;
```

Atm, I'm getting this error for the example above (which, btw, doesn't help much)

```
/Users/jonaprieto/Desktop/Example.juvix:11:11-17: error:
The expression Nat cannot appear by itself.
It needs to be the argument of a function expecting an implicit argument.
```

Ps. Once again, the title may not be the best.
Also, this issue is not limited to inductive types, same occurs with
other user-defined types:

```
axiom Nat : Type;
axiom zero : Nat;

sadness : Nat -> Nat := \ { _ := zero};
```

**Comment by paulcadman** [comment]
We'll revisit this when we have dependent types.
