### ISSUE TITLE
Allow operator definitions for record projections

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2431]
This doesn't currently work.

```
syntax operator + additive;
syntax operator * multiplicative;

trait
type Natural A :=
  mkNatural {
    + : A -> A -> A;
    * : A -> A -> A;
  };
```

The problem seems to be that `+` and `-` are implicitly defined in a local module `Natural`. Perhaps we should make local modules inherit the syntax declarations from the enclosing scope?

**Comment by lukaszcz** [comment]
Or allow qualification in operator declarations?
```
syntax operator Natural.+ additive;
```

**Comment by janmasrovira** [comment]
what about allowing `syntax operator` inside record declarations?
E.g.
```
trait
type Natural A :=
  mkNatural {
    syntax operator + additive;
    + : A -> A -> A;
   
    syntax operator * multiplicative;
    * : A -> A -> A;
  };
```

**Comment by lukaszcz** [comment]
> what about allowing `syntax operator` inside record declarations? E.g.
> 
> ```
> trait
> type Natural A :=
>   mkNatural {
>     syntax operator + additive;
>     + : A -> A -> A;
>    
>     syntax operator * multiplicative;
>     * : A -> A -> A;
>   };
> ```

Yes, this makes sense
