### ISSUE TITLE
Improve the formatting of multiline list literals

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2466]
In this issue contains suggestions on how to improve the formatting of list literals that do not fit on a single line. They follow the ormolu formatting rules that we're familiar with from Haskell.

### Unformatted code

```
l : List Nat := [aFunction someLongLongLongLongLongLongArg; aFunction someLongLongLongLongLongLongArg];
```

### Current formatting

```
l : List Nat :=
  [aFunction someLongLongLongLongLongLongArg; aFunction
    someLongLongLongLongLongLongArg];
```

### Suggested formatting:

```
l : List Nat :=
  [ aFunction someLongLongLongLongLongLongArg
  ; aFunction someLongLongLongLongLongLongArg
  ];
```

### Unformatted code / Current formatting

The following is a list literal that cannot fit on one line.

```
l : List Nat :=
  [someLongLongLongLongLongLongArg; someLongLongLongLongLongLongArg; someLongLongLongLongLongLongArg];
```

### Suggested formatting

```
l : List Nat :=
  [ someLongLongLongLongLongLongArg
  ; someLongLongLongLongLongLongArg;
  ; someLongLongLongLongLongLongArg
  ];
```

### Unformatted code / Current formatting

The following is a list literal that fits on one line. We should not change this.

```
l : List Nat := [1;2;3];
```

### Suggested formatting

```
l : List Nat := [1; 2; 3];
```

**Comment by lukaszcz** [comment]
> 
> ```
> l : List Nat := [1;2;3];
> ```

I would suggest `[1; 2; 3]`, i.e., with spaces. It's similar to putting a space after a comma.

**Comment by paulcadman** [comment]
> > ```
> > l : List Nat := [1;2;3];
> > ```
> 
> 
> I would suggest `[1; 2; 3]`, i.e., with spaces. It's similar to putting a space after a comma.

Thank you - yes this is better.

**Comment by janmasrovira** [comment]
Have you thought about this format?
```
l : List Nat :=
  [  someLongLongLongLongLongLongArg
   ; someLongLongLongLongLongLongArg
   ; someLongLongLongLongLongLongArg
  ];
```
It makes it easier to append elements to the list, which is quite common.
