### ISSUE TITLE
Generalizing data throughout LLVM

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#247]
Currently the LLVM EAC layer has a lot of adhoc abstractions that should go away before we truly generalize it

1. To get a proper separation between the base graph operations, and the particular particular kind of net (EAC), I have to pass the ADT type `eac` to a lot of operations in `Codegen/Graph`. This is rather bad, as I manually rebind them in `EAC/Defs`.
      + This can be solved with a value in the map that allows the proper propogation of this eac type throughout the nodes.
2. Often for every node type I want a special allocation function that properly allocates the right tag, however in the current system, I basically have to manually generate them all per function that allocates.
     + The right way to handle this is to have a dynamic map that holds a mapping between `LLVM.Type` and the allocation function.

3. The last point holds true for data on the port as well
    + This involves yet another map that maps the type to copying port data, this needs two functions. One that takes the data already (this must be a list of arguments sadly) and one that grabs the data. This is to keep the overhead of regrabbing the data low.

We should also create an interface for the base node itself to fill, so the logic in EAC can be generalize to be outside of the EAC type itself, so a few interfaces are needed here.

**Comment by cwgoes** [comment]
Relatedly, I think we will likely want the bespoke encoding pipeline to output an intermediary "interaction net specification form" which contains a list of node types & reduction rules, and then the LLVM code generation should operate on that instead of hard-coding specific rules directly.
