### ISSUE TITLE
The format subcommand ignores the pragma `format`

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2491]
As the title says.

This prevents to execute `make pre-commit` without unexcepted changes.

**Comment by paulcadman** [comment]
I can't reproduce this and we have a smoke test to test the `format: false` pragma:

https://github.com/anoma/juvix/blob/7f009ce14c8f7ad677d8598887bd43c81a06244e/tests/smoke/Commands/format.smoke.yaml#L37
