### ISSUE TITLE
Optimizing LLVM

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#262]
Currently our LLVM code for mallocNodeH generates code similar to this

```llvm

define external cc 10  %eac_node* @test_function()    {
test_function:
  %0 =  call cc 10  i8*  @malloc(i64  68)
  %1 = bitcast i8* %0 to %eac_node*
  %2 =  call cc 10  i8*  @malloc(i64  193)
  %3 = bitcast i8* %2 to %graph_node*
  %4 = alloca <{i1, [4 x i16]}>
  %5 = getelementptr inbounds <{i1, [4 x i16]}>, <{i1, [4 x i16]}>* %4, i32 0, i32 0
  store  i1 0, i1* %5
  %6 = bitcast <{i1, [4 x i16]}>* %4 to <{i1, i64}>*
  %7 = getelementptr inbounds <{i1, i64}>, <{i1, i64}>* %6, i32 0, i32 1
  store  i64 1, i64* %7
  %8 = bitcast <{i1, i64}>* %6 to <{i1, [4 x i16]}>*
  %9 = alloca [1 x %graph_port*]
  %10 = alloca [0 x i64*]
  %11 = getelementptr inbounds %graph_node, %graph_node* %3, i32 0, i32 0
  %12 = load <{i1, [4 x i16]}>, <{i1, [4 x i16]}>* %8
  store <{i1, [4 x i16]}> %12, <{i1, [4 x i16]}>* %11
  ret %eac_node* %1
}
```

However instead of allocing `%4` we could instead do a gep like this

```llvm
  %6 = getelementptr inbounds %graph_node, %graph_node* %3, i32 0, i32 0, i32 0
  store  i1 0, i1* %6
  %7 = getelementptr inbounds %graph_node, %graph_node* %3, i32 0, i32 0, i32 1
  %8 = bitcast <{i1, [4 x i16]}>* %7 to <{i1, i64}>*
  store  i64 1, i64* %8
```

This will cause a bit of a rewrite, however we should look out for optimizations like these.

With that said, mem2reg may catch this uneeded alloca, and optimize it out

**Comment by mariari** [comment]
Another thing to optimize is allocating and freeing a node which has no data

currently our implementation has in `mallocNodeH`

```haskell
  case anyThere mData ∷ Integer of
    -- do this when we pass more information to deAllocateNode
    -- Until then it's not safe
    -- 0 → pure ()
    _ → do
      data' ← mallocDataH mData >>= flip bitCast Types.dataArray
      dataPtr ← getElementPtr $
        Types.Minimal
          { -- do I really want to say size 0?
            -- Yes, as we have to bitcast what get back to size 0!
            Types.type' = Types.pointerOf Types.dataArray,
            Types.address' = nodePtr,
            Types.indincies' = Block.constant32List [0, 2]
          }
      store dataPtr data'
  pure nodePtr

```

I comment out the _, as it's not safe to do this as of yet, as I will try to free the dataPort which is not there.

Thus we should pass around more information to see if there is any data.

**Comment by cwgoes** [comment]
> Thus we should pass around more information to see if there is any data.

By "more information", do you mean whether the node being created by the rewrite rule stores data or not (according to the kind of node it is)?

**Comment by mariari** [comment]
> > Thus we should pass around more information to see if there is any data.
> 
> By "more information", do you mean whether the node being created by the rewrite rule stores data or not (according to the kind of node it is)?

Correct, at the moment I don't have this logic up, but eventually when we generalize things it'll be quite easy to do.

**Comment by mariari** [comment]
currently the type of `graph_num_ports` is 

```llvm
%graph_num_ports = type <{i1, [4 x i16]}>
```

The two variants are
```llvm
; large
<{i1, i64*}>*
; small
<{i1, i64}>*
```
 Which seems pointless. as having `2^64` ports is rather insane. This was originally here, as I foolishly thought I could have a lot of pointers that are 16 bit, and thus only reserve an `i16` for the numPortsSmall.

Even on a 32 bit machine 2^32 number of arguments is rather a lot, and most likely never needed.

Maybe on some small architectures this abstraction could be useful, so I will keep it in for now.

But if we detect that the machine has a sufficient number of bits, we should just cut out this variant entirely

**Comment by mariari** [comment]
> currently the type of `graph_num_ports` is
> 
> ```llvm
> %graph_num_ports = type <{i1, [4 x i16]}>
> ```
> 
> The two variants are
> 
> ```llvm
> ; large
> <{i1, i64*}>*
> ; small
> <{i1, i64}>*
> ```
> 
> Which seems pointless. as having `2^64` ports is rather insane. This was originally here, as I foolishly thought I could have a lot of pointers that are 16 bit, and thus only reserve an `i16` for the numPortsSmall.
> 
> Even on a 32 bit machine 2^32 number of arguments is rather a lot, and most likely never needed.
> 
> Maybe on some small architectures this abstraction could be useful, so I will keep it in for now.
> 
> But if we detect that the machine has a sufficient number of bits, we should just cut out this variant entirely.
> 
> The difference in speed would be quite great, as this logic has to be done before we can ascertain which port we talk to. So for example even a simple function like `link` calls this twice, meaning we make 5 more labels than we should each with some dereferencing logic in them

#281 fixes this

**Comment by mariari** [comment]
https://llvm.org/docs/Frontend/PerformanceTips.html

Has some pretty good tips for us to do

1. We should make sure all allocas are near the top of the block
    - This may be annoying if we don't actually make functions be functions. Currently we just inline most intermediate functions, so this may need to be reconsidered!
2. Look into lifetime.start and lifetime.end
3. put metadata on pointers
4. use fast addition flags
5. Consider alignment of code

**Comment by cwgoes** [comment]
> This may be annoying if we don't actually make functions be functions. Currently we just inline most intermediate functions, so this may need to be reconsidered!

I'm not sure whether we should inline functions or let LLVM inline them for us. Probably we will just need to experiment.

All of the other seem worth investigation. In terms of arithmetic operations, hopefully we can have nice automatic translation of "natural numbers" or "integers" in the frontend/core language into the smallest safe machine type (since we can use dependent types to prove bounds on what the integers can be).

**Comment by cwgoes** [comment]
This issue is out-of-date.
