### ISSUE TITLE
LLVM Variable Size Array Specification

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#263]
Currently I'm unsure of how to encode variable size arrays into LLVM.

## Motivation and side stepping

So, we want variable size arrays, as nodes may have differing numbers of of ports and data that they hold. Since in LLVM, we have to type how many elements of the array there is at type creation time, we have to make the arrays variable size.

With this said, we will always know the portSize and dataSize coming from above and what we allocate, so really these arrays never "grow", and thus we could maybe find a trick like 

-  http://lists.llvm.org/pipermail/llvm-dev/2014-February/070381.html

That could solve this issue.

## Current implemeentation

Currently I store in node_type something like this
```llvm
%graph_node = type <{<{i1, [4 x i16]}>, [0 x %graph_port], [0 x i64]}>
```
so we use an array of size 0, and a tag to determine how big this array is.

However when we generate the Allocation logic for some llvm nodes we have to do
```llvm
  %9 = alloca [1 x %graph_port]
  %10 = alloca [0 x i64]
  %11 = getelementptr inbounds %graph_node, %graph_node* %3, i32 0, i32 0
  %12 = load  <{i1, [4 x i16]}>, <{i1, [4 x i16]}>* %8
  store  <{i1, [4 x i16]}> %12, <{i1, [4 x i16]}>* %11
  %13 = getelementptr inbounds %graph_node, %graph_node* %3, i32 0, i32 1
  %fooBitCast = bitcast [1 x %graph_port]* %9 to [0 x %graph_port]*
  %foo        = load [0 x %graph_port], [0 x %graph_port]* %fooBitCast
  store  [0 x %graph_port] %foo, [0 x %graph_port]* %13
```
I am not yet sure if this is correct, and how this interacts if the data we hold is greater than 0.

**Comment by mariari** [comment]
It seems even the [mapping high level constructs to llvm](https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/basic-constructs/structures.html) references this way of doing it.

I read [in the LLVM language ref](http://llvm.org/docs/LangRef.html#array-type) that the way we currently have is fine. However I think I will promote our ` [0 x %graph_port], [0 x i64]` types into pointers over these types

**Comment by cwgoes** [comment]
> I read in the LLVM language ref that the way we currently have is fine. However I think I will promote our [0 x %graph_port], [0 x i64] types into pointers over these types.

> This implies however that I need to do extra mallocs, which seems quite costly.

I read the section you reference & I agree that this approach makes sense, but I don't understand where the extra `malloc`s are happening. Shouldn't we only need to `malloc` at a time when we actually know the size (and therefore can `malloc` exactly that size, then cast to a zero-length array type)?

If we want other inspirations, two things we could check are how `clang` compiles `std::vector` (variable-sized C++ array) and how `rustc` compiles vectors.
