### ISSUE TITLE
Formatting of imports breaks lines unnecessarily

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2737]
The import
```
import Stdlib.Cairo.Ec as Ec;
```
gets formatted into
```
import
Stdlib.Cairo.Ec as Ec;
```
I don't understand the reason. It's merely 30 characters long - the line shouldn't be broken up.

**Comment by janmasrovira** [comment]
I haven't been able to reproduce this problem. Can you provide a minimal example?
