### ISSUE TITLE
The "Compiling" message should only be displayed for modules that are actually compiled

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2797]
Now we always display "[X of N] Compiling Module.juvix", including for all modules in the standard library, even if the module is only read from disk and deserialized. I think this message should be displayed only for modules that are actually re-compiled and not only read from disk. Otherwise, it's confusing and there is too much visual garbage every time you compile something.

Alternatively, we could use a different message for modules which are only read from disk, e.g., "Loading Module.juvix from disk". But I would advocate to remove the message entirely for modules that are not re-compiled.

## Agreed
* rename the --only-errors flag to --quiet.
* Differentiate between loading and compiling

**Comment by janmasrovira** [comment]
I am leaning towards having the `Loading` message. I think it gives relevant feedback as loading from the system does not take a negligible amount of time. Moreover, once we have optimized the files that we need to load, it'll become less noisy.

**Comment by paulcadman** [comment]
We agreed to rename the `--only-errors` flag to `--quiet`.
