### ISSUE TITLE
Create a dedicated Juvix website

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#286]
- [ ] Setup Github Pages or something (maybe that's not dynamic enough?)
- [ ] Project overview
- [ ] Links to all relevant blog-posts
- [ ] Compiler architecture diagrams (https://github.com/cryptiumlabs/juvix/issues/285)
- [ ] Rendered documentation from this repository
- [ ] Animations of interaction net reduction
- [ ] Animations of other reduction models
- [ ] Rendered language reference
- [ ] Tutorials (in the future)
- [ ] Point juvix.org to it
- [ ] Try-it feature with in-browser compilation (have to target WASM with the Haskell compiler...)

**Comment by cwgoes** [comment]
[Vuepress](https://vuepress.vuejs.org/guide/#how-it-works) might make sense.

**Comment by cwgoes** [comment]
Eventually, it would be nice to have an interactive walkthrough of the compiler pass sequence:

![output](https://user-images.githubusercontent.com/24760279/72668449-56a4d500-3a27-11ea-8163-8baf6a6463ee.png)

(quick example, will vary in the future)

The user should be able to enter actual frontend code (so this will require compilation to JS or a remote server instance), and take it step-by-step through the compilation sequence, with UI elements to control options / compilation targets / etc. - steps should also be linked to documentation & source locations where applicable. I think this will aid with entry into compiler engineering & understanding of how the system fits together.

**Comment by cyberglot** [comment]
idk the plans here, but I'm well-versed in elm-based SPA/static gen. And we can deploy either using gitlab or netlify.

**Comment by cwgoes** [comment]
Done, let's track website features in the website repositoryg
