### ISSUE TITLE
Juvix typecheck runs into an infinite loop

### ISSUE THREAD

**Issue by heueristik** [anoma/juvix#2866]
**Description**

The juvix typechecker freezes when 
- square brackets are removed around a `List Nat` function argument o
- a `Maybe` is added to the return type

**Systemn**

- OS: macOS 14.5 (23F79), MacBook Air M1, 2020
- Juvix version: 0.6.2-371f8f2

**To Reproduce**

1. Remove the square brackets
```diff
create (self : KeyPair) (tokenLabel : Label) (amount : Nat) (receiver : PublicKey) : Transaction :=
  let
    myself : PublicKey := KeyPair.pubKey self;
  in
    Internal.mkTransaction
      (KeyPair.privKey self)
---   [(Internal.mkToken true amount tokenLabel mkData@{owner := myself; previousOwner := myself})]
+++   (Internal.mkToken true amount tokenLabel mkData@{owner := myself; previousOwner := myself})
      [(Internal.mkToken false amount tokenLabel mkData@{owner := receiver; previousOwner := myself})];
```
in https://github.com/anoma/anoma-apps/blob/9cfc2011d0706ddc81f69da38d4ecfd1250df1d8/Token/Token.juvix#L19. 

2. Run the typechecker with `juvix typecheck Token.juvix`.

3. See the terminal not terminating.
```
[133 of 134] Compiling /Users/michaelheuer/Projects/Anoma/apps/anoma-apps/Token/Internal.juvix             
[134 of 134] Compiling /Users/michaelheuer/Projects/Anoma/apps/anoma-apps/Token/Token.juvix
```

The bug can be reproduced by making the following change to the code https://github.com/anoma/anoma-apps/blob/9cfc2011d0706ddc81f69da38d4ecfd1250df1d8/Token/Token.juvix#L25

```diff
--- createKudos (self : KeyPair) (amount : Nat) (receiver : PublicKey) : Transaction :=
+++ createKudos (self : KeyPair) (amount : Nat) (receiver : PublicKey) : Maybe Transaction :=
     create self (mkKudosLabel (KeyPair.pubKey self)) amount receiver;
```

**Expected behavior**

The typechecker should throw a type error demanding `List Nat` instead of `Nat` as a function argument.

**Screenshots**

![Bildschirmfoto 2024-06-28 um 10 42 37](https://github.com/anoma/juvix/assets/20623991/b3c1c383-2863-4b51-8450-d79ba291d8f4)

**Comment by janmasrovira** [comment]
I can't replicate this issue. Should we close this?
