### ISSUE TITLE
stdlib specs for Michelson

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#294]
Here is a non-exhaustive, working list of what we want to support to have full [Michelson](https://tezos.gitlab.io/whitedoc/michelson.html#core-data-types-and-notations) functionality:

Built-in types:
- [x] unit 
- [x] nat
- [ ] int
- [ ] bool
- [ ] amount (of currency, e.g., tez)
- [ ] string
- [ ] bytes
- [ ] time stamp
- [ ] cryptographic keys
- [ ] hashes of cryptographic keys
- [ ] cryptographic signatures
- [ ] operations - more below
- [ ] address of entities (owners, senders, contracts)

Data structures:
- [ ] lists
- [ ] sets
- [ ] maps
- [ ] big maps
- [ ] option type

Comparison operators (for values of the same type):
- [ ] equal
- [ ] not equal
- [ ] less than or equal
- [ ] greater than or equal
- [ ] strictly less
- [ ] strictly greater

See example implementation from [Idris](https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude/Nat.idr).

Operations on nat:
- [x] `ADD`,`SUB`, `MUL`, `EDIV`: Arithmetic operations
- [ ] `NEG`/`INT`: turn a nat to an int without alteration

Operations on int:
- [ ] `ADD`,`SUB`, `MUL`, `EDIV`: Arithmetic operations
- [ ] `NEG`: return the negative value of the same magnitude
- [ ] `ABS`: return the absolute value
- [ ] `ISNAT`: return an option of nat

Operations on booleans, nat, int:
- [ ] `OR`: Or
- [ ] `AND`: And
- [ ] `XOR`: Nor
- [ ] `NOT`: Not 

Operations on [string](https://tezos.gitlab.io/whitedoc/michelson.html#operations-on-strings) etc
-TBD

Retrieval functions (in Michelson):
- [ ] `BALANCE`: the balance of the current contract 
- [ ] `NOW`: the timestamp of the block in which the transaction is included
- [ ] `AMOUNT`: the amount of tez transferred by the current operation 
- [ ] `STEPS_TO_QUOTA`: the amount of gas available to execute the rest of the transaction
- [ ] `SOURCE`: the address that initiated the current top-level transaction
- [ ] `SENDER`: the address that initiated the current transaction

Operations:
- [ ] `FAILWITH`: abort the current program

**Comment by cwgoes** [comment]
All of the built-in datatypes & functions can be supported through [the core parameterisation](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Backends/Michelson/Parameterisation.hs) - we'll want to use typeclasses to resolve common operations (e.g. arithmetic) in the standard library per https://github.com/cryptiumlabs/juvix/issues/157, but I expect there will also be a custom "Michelson" section of the standard library initially which only works with contracts targeting Michelson.

**Comment by cwgoes** [comment]
No longer relevant.
