### ISSUE TITLE
Handling of record field names is inconsistent: different for record creation and record update

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2968]
In record creation, e.g.,
```
let r1 := A in
mkR@{r1 := r1}
```
the `r1` on the right side refers recursively to the field being defined.

In record update, e.g.,
```
let r1 := A in
r@R{r1 := r1}
```
the `r1` on the right side refers to the `r1` defined by the `let`.

Complete example:
```
module rec;

type T := A | B;

type R := mkR { rt : T };

r : R := mkR@{ rt := A };

g : T -> T
  | A := B
  | B := A;

f : R -> R
  | r@mkR@{rt} := (r@R{rt := g rt});

main : T := R.rt (f r);
```
This type-checks and prints `B`.

We should somehow unify the behaviour.

Possible solutions
------------------
1. Make references in record update recursive by default. I don't like this one, because it's making life harder for the users.
2. Make zero-argument functions in record creation/update always non-recursive and "proper" functions with multiple args recursive. This seems to match most closely with actual use-cases. In virtually all cases when using a zero-argument name in record creation you don't want it to be recursive. In most cases when you define a proper function you want it to be recursive by default.
3. Have a different way of indicating that a field defined in record creation/update is recursive: some `rec` keyword or something like this.

Option 1 seems to make the language most "unified" (the syntax for definitions is everywhere the same), but also most annoying to use the record update/creation.

Options 2, 3 make the syntax less consistent than 1, but seem to align more closely with actual use-cases.

Any more options?

**Comment by janmasrovira** [comment]
Summary of what we briefly discussed online
1. When defining a term we should only bind the name being defined in the body if the definition _looks like a function_. This needs to be consistent across top definition, record creation/update, let definition. Looking like a function means that either there is at least an argument on the left of the `:`, or there is at least one guard. This is what @lukaszcz proposed in the first two points. We don't need `rec` for now and most likely we won't need it in the future.
3. For record updates, we would access the old value by prefixing the reference by `@`. I.e.
   ```
   let x := 3 in
   r@R{ x := @x + 1; -- `@x` refers to the value of the field `x` in `r` before the update. 
        y := x}      -- `x` refers to the `x` defined in the outside let. 
   ```
3. Record puns do not need to change for record creation. They need to be supported for record updates (#2967).
