### ISSUE TITLE
Improve array formatting and add line continuation character

### ISSUE THREAD

**Issue by heueristik** [anoma/juvix#2971]
The following would look nicer if line breaks would be applied only after reaching the 100 char limit.

![Bildschirmfoto 2024-08-23 um 13 11 40](https://github.com/user-attachments/assets/3ff89776-2ec7-4182-be9c-32939e3237b4)

Maybe, a line continuation can be used to signal the intention for the line to be broken earlier (e.g, if you would like to group data in chunks).

```
[ \ 
  0x3b; 0x6a; 0x27; 0xbc; 0xce; 0xb6; 0xa4; 0x2d; \ 
  0x62; 0xa3; 0xa8; 0xd0; 0x2a; 0x6f; 0x0d; 0x73; \
  0x65; 0x32; 0x15; 0x77; 0x1d; 0xe2; 0x43; 0xa6; \
  0x3a; 0xc0; 0x48; 0xa1; 0x8b; 0x59; 0xda; 0x29 \
];
```

**Comment by paulcadman** [comment]
Two workarounds we can think of:

* Add `{-# format : false #-}` to the top of the file to disable formatting for the module
* Move the bytes literal to a separate file and import it.
