### ISSUE TITLE
Dependently-typed contract developer experience/proof UI design

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#3]
Implement several example contracts (perhaps sourcing from [this list](https://github.com/cryptiumlabs/smarter-contracts/blob/master/CONCEPTS.md)) in a dependently-typed frontend close to what we're likely to end up using - Idris is probably the best estimation.

Write formal proofs of correctness for the relevant invariants (e.g. token total supply).

Investigate what parts of this are tricky to learn & execute, and brainstorm how Juvix might automate parts of the proof construction process (perhaps by libraries of tactics, automated proof search, alternative syntactical or graphical representations, or other methods) to reduce the developer expertise & time costs required to write dependently-typed smart contracts.

**Comment by thealmarty** [comment]
> brainstorm how Juvix might automate parts of the proof construction process (perhaps by libraries of tactics, automated proof search, alternative syntactical or graphical representations, or other methods) to reduce the developer expertise & time costs required to write dependently-typed smart contracts.

I've been surveying proof assistants/languages such as Idris and Coq, [here](https://gist.github.com/thealmarty/1238301abff35d53cddc165ecd473705) are some thoughts I have on what Juvix can do to make it easier to write proofs. Will continue going though software foundations and also look into Agda for inspirations.

**Comment by thealmarty** [comment]
Next steps:
- survey relevant languages: 
  - [ ] Coq
  - [ ] Agda
  - [ ] F*
- Design documents (See #312 )
  - [ ] tactics
  - [ ] refinement types
  - [ ] interactivity/error message improvements
- [ ] Blogpost on design plans and ask for feedback

**Comment by cyberglot** [comment]
y'all know about [plfa](https://plfa.github.io/), right?

**Comment by thealmarty** [comment]
- [ ] Study other smart contract IDEs, e.g., [Remix](https://remix-ide.readthedocs.io/en/latest/layout.html)

**Comment by cyberglot** [comment]
about LF:
I think we can use that paper on LF and SMT solver to try to combine Auto in Agda with it.
I know some people have been trying to integrate SMT to Agda, but still not stable.
