### ISSUE TITLE
Lower Level IR language for Juvix

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#300]
While reading through [Implementing functional languages: a tutorial](https://www.microsoft.com/en-us/research/publication/implementing-functional-languages-a-tutorial/), I came to the realization that we need an intermediate stack language.

This IR will sit one level above all the various backends (LLVM, Michelson, etc).

This low level IR will most likely be some kind of stack machine that we could easily translate directly into the various language, hopefully with not too much more optimization.

This IR should encapsulate the Bespoke vs non-Bespoke or simply compile it down to different instructions.

**Comment by cwgoes** [comment]
A random but pertinent thought: with first-class usages, I think we should be able to do a sort of better-call-by-value, where arguments are only evaluated if they are actually used in the body of the function (this is of course trivial at compile-time, but there will be lots of cases where usages depend on arguments / other values that compile-time analysis can't handle - but we can do a bit of runtime usage calculation & hopefully avoid expensive evaluations).

**Comment by cwgoes** [comment]
Superseded by architectural discussions.
