### ISSUE TITLE
Crash in type argument removal: unsupported node

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#3096]
Check out commit 7439f2f1c558cda946111befa5ffac91bf948b6d from juvix-stdlib, go to `test` and run:
```
make test
```
The result:
```
juvix: remove type arguments: unsupported node
	(? lambda_304@Test!304@Test lambda_507@Test!507@Test ?!29@Stdlib.Data.List.Base) Bool
CallStack (from HasCallStack):
  error, called at src/Juvix/Prelude/Base/Foundation.hs:501:9 in juvix-0.6.6-Es9DwLRPTtLIIl9tezES8s:Juvix.Prelude.Base.Foundation
  error, called at src/Juvix/Compiler/Core/Transformation/RemoveTypeArgs.hs:16:24 in juvix-0.6.6-Es9DwLRPTtLIIl9tezES8s:Juvix.Compiler.Core.Transformation.RemoveTypeArgs
```

**Comment by paulcadman** [comment]
This is usually caused by the `quickcheck` dependency using a different copy of the standard library. I think it's related to:

* https://github.com/anoma/juvix/issues/2985

**Comment by paulcadman** [comment]
> This is usually caused by the `quickcheck` dependency using a different copy of the standard library. I think it's related to:
> 
> * [Package name & version are not set properly in moduleIds #2985](https://github.com/anoma/juvix/issues/2985)

Updating all of the stdlib test dependencies to use the same stdlib ref fixes this issue. Therefore this bug is indeed caused by #2985 and Is not a separate bug in the pipeline.
