### ISSUE TITLE
@? syntax errors

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#3155]
**Describe the bug**

```haskell
Stdlib.Prelude> snoc@?{elem := 5}
Maybe.fromJust: Nothing
CallStack (from HasCallStack):
  error, called at libraries/base/Data/Maybe.hs:150:21 in base:Data.Maybe
  fromJust, called at src/Juvix/Compiler/Internal/Translation/FromConcrete.hs:873:16 in juvix-0.6.6-63HcRSLJPON7XBeV31D9oO:Juvix.Compiler.Internal.Translation.FromConcrete
```

**Desktop (please complete the following information):**

- Juvix Version [e.g. 22] Juvix version 0.6.6-0961d87

**To Reproduce**

**Expected behavior**
No idea what this syntax should do

**Comment by paulcadman** [comment]
We agreed to remove the @? syntax:

* https://github.com/anoma/juvix/issues/3210
