### ISSUE TITLE
Cleanup of the Juvix Code Base

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#329]
Idioms and patterns in the Juvix codebase have slowly evolved, and thus some of the older code does not conform to current idioms.  

This issue tracks the transitions of idioms, assigns various TODOs when refactoring old code, and even hold suggestions for future refactoring

### Issues That deal with this topic directly
#328 Is the first PR that refactors a lot of the code base
   - 328 mainly deals with formatting and naming conventions

**Comment by mariari** [comment]
What currently is left for the superficial issues is.

1) [ ] change the param tuples into a proper type

2) [ ] format tests to be around 80 characters long

3) [ ] Add qualified names to the `Combinators` backend in the interpreter

**Comment by cwgoes** [comment]
Thank you!
