### ISSUE TITLE
Juvix Macro Language

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#337]
Currently Juvix's front end lanugage is not designed with a macro system in mind.

Below we list the the approaches we will look into and try in order

1. Having a Lisp alternative syntax
    - This would allow changing both the Juvix lisp reader and the Juvix ML reader
    - This would allow an isomorphism between the two syntaxs
        + ideally, we'd have an in editor way to transform ML to lisp and vice versa, this would allow the user to see their ML code as lisp before creating their macros!
    - We would get the benefit, of moving hard coded syntax, into a standard syntax set, that everyone would use
         + Racket has done this, and people don't really seem to rock the boat

2. Look into how other non homoiconic languages (Elixir, F*, Agda, Dylan [This may be homoiconic?]) and see how they consturct macros

3. Give up and accpet the Haskell style of language extensions.

**Comment by cyberglot** [comment]
[Rust has macros](https://danielkeep.github.io/tlborm/book/index.html).

**Comment by mariari** [comment]
A more apt language to look at is [the typer language](https://gitlab.com/monnier/typer). It claims to be a child of Coq and LISP.

From what I remember, this has lisp style macros in an ML like language. It may do this via the type system, I do forget though.

None the less, this shall be above the Lisp alternative syntax scheme if so.

**Comment by mariari** [comment]
Further discussion on some analysis on various macro systems are commented on #634

**Comment by cwgoes** [comment]
@mariari has a better issue on this topic
