### ISSUE TITLE
LLVM Sum Type Optimization

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#372]
While reading *Compiling with Continuations* I came across the following section.

> Also, datatypes with only one value-carrying constructor don’t need the tag
in their record. For example, the datatype xxx has three constructors, but only
one is not a constant. Therefore, if a value of type xxx is a pointer, it must be
an application of the P constructor. 

> Datatypes with only one value-carrying constructor applied to an always-boxed
value don’t even need the extra indirection. A boxed value is simply one represented
as a pointer; an unboxed value is represented as an integer (or other nonpointer).
Consider the type ’a list: Since the :: (pronounced cons) constructor is always
applied to a record, the value it carries is always a pointer. Since the nil value is
represented as a small integer, we know that :: values can always be distinguished
from nil values. Thus, we can represent 5::nil as a record containing 5 and nil,
without any extra indirection.

This means, that we can compile a list into LLVM as the following:

```llvm
%list = type [4 x i8]

%cons = type { %value, [ 4 x i8] }*
%nil  = type i32

@nil = constant nil 0
```

Currently we have

```llvm
%eac_list = type {%graph_node*, %eac_list*}
```

where value is the type of the contents of the list (most likely will just be a pointer (or an unboxed type), to the resolved type of α.

however this is special cased for compilation, and not intended to be for user defined types.

**Comment by cwgoes** [comment]
Out of date
