### ISSUE TITLE
Michelson: Fix usage and stack shuffling,

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#373]
Currently our backend for Michelson when considering usages has an issue.

consider the following examples

```ocaml
let f y x z = (\a -> a * x) x

f 2 3 4

let g y x z = x * x

g 2 3 4  
```

In both the g and f case, we can deduce that x has two usages while y and z has 0 usages.

This is great, however under our current model, we do the following
```
Executing g:

-- assume non constnat
Instructions: push 2, push 3, push 4. 
VStack: [(z,0), (x,2), (y,1)]

-- See lookup X
Instructions: SeqEx [PrimEx (DIG 1),PrimEx (DUP @),PrimEx (DUG 2)]
VStack [(x,1),(z,0), (x,1), (y,1)]

-- See lookup X
Instructions: DIG 0
VStack [(x,1),(z,0), (x,1), (y,1)]

-- Mult
```

The result is similar for f.

This happens because we move `n-1` usages of the variable (in this case `x`) to the front, leaving 1 usage behind. This has adverse behavior when we have to use the same x in the same application twice or more.

f shows us a more pathological case, as if we desugar the execution, we don't have `x` being called twice in the lambda.

I believe there are two ways to fix this issue.

Both these ways, have a new notion in the `VStack`, known as `save`.

What `save` does, is that it marks 1 usage as saved, and thus effectively to move it to the front, means to dup it (as its' been saved in it's position).

Thus here are two solutions

1) The easy solution, just implement save, and do no changes to how usages are carried

    An example of what this may look like is the following
   ```
   -- First Lookup X from Example above
   Instructions: SeqEx [PrimEx (DIG 1),PrimEx (DUP @),PrimEx (DUG 2)]
    VStack [(x,1, SAVE),(z,0), (x,1), (y,1)]
   -- Second Lookup X from Example
   Instructions: PrimEx (DIG 2)
    VStack [(x,1, SAVE), (x,1, SAVE), (z,0), (y,1)]
    ````

    This would also work under renaming with minimal modification.
    If a variable is renamed, and it is saved, we would have to look for all aliases as well
    Our current model does not do this, but could easily be done.

2) The Hard solution. Just move all n usages up, When a variable is about to be consumed with extra usages left, copy it before the execution spot.

    This solution should be more efficient, as instead of `DIG 2` above, we could instead just do a `dup`, and even avoid the dig dug.

    The only complicated factor, is that we have to implement knowing what spot is save to move the variable. I think this would add further complications, and thus should be tried later

**Comment by cwgoes** [comment]
> Just move all n usages up, When a variable is about to be consumed with extra usages left, copy it before the execution spot.

To me, this seems likely to be the more efficient option (as you mention).

> The only complicated factor, is that we have to implement knowing what spot is save to move the variable. I think this would add further complications, and thus should be tried later

Hmm, can we keep a placeholder (some special sentinel value) and move the variable back once we have finished e.g. compiling the function?

**Comment by mariari** [comment]
> > Just move all n usages up, When a variable is about to be consumed with extra usages left, copy it before the execution spot.
> 
> To me, this seems likely to be the more efficient option (as you mention).
> 
> > The only complicated factor, is that we have to implement knowing what spot is save to move the variable. I think this would add further complications, and thus should be tried later
> 
> Hmm, can we keep a placeholder (some special sentinel value) and move the variable back once we have finished e.g. compiling the function?

It seems Option 2 can't be safely done without normalizing... Consider

```haskell
f a (x + y) b
```
x and y will move interrupting either a or b for some primitive f.

Once normalization is up, this will look like
```ocaml
let xy0 = x + y in
f a xy0 b
```

this has an extra cost of computing x + y first (and thus being on the stack earlier, but makes the optimization safe.

**Comment by mariari** [comment]
As per #374 being merged. Strategy 1 is chosen until Strategy 2 is safe to do.

It should be noted, that the slowness of Strategy 1 can easily be removed from an optimization pass,  as the form is very specific (and thus easy to optimize for).

```haskell
    SeqEx
      [ PrimEx (DIG 1),
        PrimEx (DUP ""),
        PrimEx (DUG 2)
      ],
    PrimEx (DIG 0),
    PrimEx (DIG 2),
```
    + This is what the form looks like
Note that the two Dig's for it aren't going to be always next to each other. There may be up to n instructions in between.

**Comment by cwgoes** [comment]
Out of date
