### ISSUE TITLE
Self-amending function

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#39]
Juvix contracts that self-optimize proofs and rewrite rules etc.

**Comment by cwgoes** [comment]
The really cool part is that contracts written in Juvix can restrict their own future upgrades by requiring that the upgraded code still satisfies certain invariants (proofs) of behavioural semantics.

**Comment by cwgoes** [comment]
This does require https://github.com/cryptiumlabs/juvix/issues/104.
