### ISSUE TITLE
Change the frontend syntax to as close to Coq's as possible

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#409]
I'm sorry I know this is a little late for this but I still want to bring it up because I see huge benefits for any machine learning features we may want to add later. See [here](https://gist.github.com/thealmarty/9508f67de927fc1797dd27bb4ad7fdc9).

If interested, I can write a few example contracts in Coq to demonstrate.

**Comment by cwgoes** [comment]
Hmm, I don't think this will work since we don't have the same semantics as Coq? Models trained on Coq wouldn't work on Juvix, even if the syntax were the same. Nonetheless, I think this direction of research is interesting, but not a short-term priority.

**Comment by thealmarty** [comment]
It's true, it may not work. That is something we will have to find out. If we hadn't chosen a syntax, I'd say why not follow Coq's for this reason. But it may be too costly to change now.

**Comment by cwgoes** [comment]
I think I'm making a stronger claim - if the machine learning is in any way dependent on the semantics of Coq, as opposed to just the syntax, having the same syntax won't help - we'd also have to have the same semantics (in which case the language would just *be* Coq). If part of what is being learned is how to construct proofs, that will be dependent on the semantics.

That doesn't preclude us considering this method for Juvix (in the future) - I think it's interesting - but I think we'll need our own training data either way.
