### ISSUE TITLE
Don't always inline type aliases

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#426]
Since we are a dependently typed language, there may be some work done in type alises.

If this is the case, then a type alias boils down to the same thing as a let abstraction, and thus removing an alias duplicates work.

Thus we should consider treat aliases as let abstractions later down the road

**Comment by cwgoes** [comment]
Yeah, this might be prudent. I wonder if this is true anywhere else in the frontend syntax (or in our simplifications).

**Comment by cwgoes** [comment]
subset of more important issue
