### ISSUE TITLE
Suggestions for Juvix file endings

### ISSUE THREAD

**Issue by adrianbrink** [anoma/juvix#429]
Currently we seem to have `.jvx`.

I would like to propose the following for consideration:
* `.jv`
* `.ju`

I'm against these:
* `.jx`
* generally endings with `x` seem very close to JavaScript/React
  * `.jsx` (https://reactjs.org/docs/introducing-jsx.html)

**Comment by thealmarty** [comment]
I like `.ju`!

**Comment by cwgoes** [comment]
I don't have a strong opinion. `.ju` is cute, sounds a bit like the name of the mascot.

**Comment by cyberglot** [comment]
I'd strongly prefer `.jvx`, since it's all the consoants in the language's name :)

**Comment by cwgoes** [comment]
`.jvx` won 3-2 on the Juvix subteam.

**Comment by cwgoes** [comment]
Ah, never mind, `.jvx` is [taken](http://www.javaview.de/maple/gettingStarted/index.html#:~:text=mpl%20or%20.,-jvx.&text=jvx.-,The%20.,use%20runMarkupTree%20to%20view%20it.).

As far as I can tell, `.ju` is not.

**Comment by cwgoes** [comment]
`.ju` has been chosen
