### ISSUE TITLE
Encoding ADTs

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#434]
As our compiler gets more complete, we need a concrete plan for compiling ADTs

The default method when no speical tricks apply is to just add an additional decision int with every variant.

However for certain backends, namely arithemtic circuit compilation, an extra allocation is unacceptable.

All these tricks require extra information about types, and thankfully since we have dependent types, we can hopefully do these tricks more oftenly than a traditional compiler.

The Tricks are as follows:

1. If we have an ADT which has only 1 Sum with contents and said content is a pointer, then
    ```ocaml
       data Foo = F | B | Baz of Int * Int
    ```
   then we don't need to add a decision int, instead F is 0, B is 0, and Baz is a pointer

2. If we have an ADT, where the domain of the data is not total on the value of representation then we need not an extra int
    ```f*
     data Foo = Bar of i : Int { i >= 0} | Foo | B
    ```
    Here we know i has to be greater than 0, so FOO can be -1 and B can be -2.
   
    For an Arithemtic circuit even this can live without an extra int
    ```f*
     data Foo = Bar of Int | Foo | B | Baz of Int
    ```
    This is the case as the Field element is much greater than an Int, so we could thankfully shift (add) the elements to be non overlapping, and with Foo and B taking up 2 other values not taken

**Comment by Acentelles** [comment]
Closing in favor of https://hackmd.io/hYTy0bCKSvah-wVPk4mjMg
