### ISSUE TITLE
Module: Updating Context to deal with multiple files

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#457]
It would be best to refactor the context to have a few notions

1. What modules we are in
  - We need to store away an extra map that will be added back when jumping to a new module
  - also need to store the name as to lookup symbols from the proper location
2. knowledge of other compiled modules in some kind of format

With these notions we could effectively compile multiple files at once. Though at first we'll likely stage them all to happen in the contextify pass with the above changes

**Comment by mariari** [comment]
Also in This pass update top level `module opens` to note which symbols conflcit

we will signal an error when: 
  - when a conflicted symbol is used when the two packages that are not in conflict are not implicit
  - Examples of implict modules are Prelude and functions defined in the same file but in the modules above it 
   ```ocaml
     mod Bar = 
        let f x = x + 1
     end 

     mod Foo =
       open Bar 
       let x = f 2
     end

     let f x = x + 2 
  ```
  in `Foo` `f` should not be an error as the implicit `f` is shadowd by `Bar`.

However in 
   ```ocaml
     mod Bar = 
        let f x = x + 1
     end 

     mod Baz = 
        let f x = x + 1
     end 

     mod Foo =
       open Bar
       open Baz 
       let x = f 2
     end

     let f x = x + 2 
  ```

the use of `f` in `Foo` should error, as `f` is in both `Bar` and `Baz`


however note for local opens the rule changes:

   ```ocaml
     mod Bar = 
        let f x = x + 1
     end 

     mod Baz = 
        let f x = x + 1
     end 

     mod Foo =
       let x =
          open Bar in
          open Baz in
           f 2
     end

     let f x = x + 2 
  ```

In the example above, the use of `f` in `Foo.x` should not error, as the order is explictly stated to open `Bar` then `Baz`

The ordering on Locals and not globals are in line with haskell which allows free form configuration of defintions on the top level, but a strict ordering in lets.

If we were to have some kind of `where` notion, then the top level behavior would apply.


One last note:
  - Implicit shadowing is fine, as there is no direct signal the user wanted the functions in their namespace. We will likely offer 2 flags. `Implicit prelude override`, and `local functions in implicit module override ` That changes this beahvior.

  - I suspect the former might need to change defaults, while the latter would be considered more intuitive.

**Comment by cwgoes** [comment]
Superseded by future expected better issue by @mariari
