### ISSUE TITLE
An argument for the usage of | in match for indent sensitive syntax

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#475]
Remember that types are declared like
```haskell
data Test a b
  = Foo a
  | Just a
  | Nothing
  | Left b
```

This uses `|` to denote choice. Thus there is a good duality between creation and consumption

```ocaml
(* 1 *)
let foo a =
  match a with
  | Foo a   -> a
  | Just a  -> a
  | Nothing -> 3
  | Left _  -> 3

(* 2 *)
let foo a =
  match a with
    Foo a   -> a
    Just a  -> a
    Nothing -> 3
    Left _  -> 3

let foo a =
  match a with
  | Foo a   | Just a -> a
  | Nothing | Left _ -> 3
```
The above modulo `2` showcases the duality, along side giving the eye a place to focus on for new patterns. This meaning even extends to or patterns, with the last match above show casing the obvious relation.

The noise difference between `1` and `2` is noticeable, however not majorly so. This is due to the code being able to keep the response on the same line, allowing `->` to be aligned.

However, when lines get long and spill over to multiple lines 

TODO :: find a more noisy example in code, namely something nested, where the indentation is hard to tell, or when the matches are longer

```haskell
-- 1
updateTopLevel ty ctx =
  case ty of
    Repr.Type t@(Repr.Typ _ name _ _) ->
      Context.add (NameSpace.Pub name) (Context.TypeDeclar t) ctx
    Repr.Function (Repr.Func name f sig) ->
      Context.add (NameSpace.Pub name) (decideRecordOrDef f sig) ctx
    Repr.ModuleOpen (Repr.Open _mod) ->
      ctx

-- 2
updateTopLevel ty ctx =
  case ty of
  | Repr.Type t@(Repr.Typ _ name _ _) ->
      Context.add (NameSpace.Pub name) (Context.TypeDeclar t) ctx
  | Repr.Function (Repr.Func name f sig) ->
      Context.add (NameSpace.Pub name) (decideRecordOrDef f sig) ctx
  | Repr.ModuleOpen (Repr.Open _mod) ->
      ctx

-- 3
updateTopLevel :: Repr.TopLevel -> Context -> Context
updateTopLevel (Repr.Type t@(Repr.Typ _ name _ _)) ctx =
  Context.add (NameSpace.Pub name) (Context.TypeDeclar t) ctx
updateTopLevel (Repr.Function (Repr.Func name f sig)) ctx =
  Context.add (NameSpace.Pub name) (decideRecordOrDef f sig) ctx
updateTopLevel (Repr.ModuleOpen (Repr.Open _mod)) ctx =
  ctx
```

I'd argue that `2` gives the biggest visual queue for the match and the body, giving the eye a symbol to focus the eye on. Further one can imagine in nested matches where the indentation level gets a big harder to properly see, the anchoring effect this may have. 

`3` is easily the loudest, with the arguments/matchs and the body obstructing each other. I believe `1` will fair worse than `2` as the match gets larger.

**Comment by cwgoes** [comment]
Resolved, the new syntax does not do this.
