### ISSUE TITLE
Consider using the nominal library in core

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#479]
The [nominal library](http://hackage.haskell.org/package/nominal-0.2.0.0/docs/Nominal.html) provides a clean and efficient way for defining data types with binders. This could simplify the handling of the core terms.

See also [these lectures](https://www.youtube.com/playlist?list=PLmYPUe8PWHKpAyfjsrHYoJF7MtyT5W0-D) for details on how to use the library.

**Comment by cwgoes** [comment]
Considered and rejected, but thank you for the suggestion!
