### ISSUE TITLE
Documentation v1.0

### ISSUE THREAD

**Issue by awasunyin** [anoma/juvix#482]
Juvix' website v1.0's design has been finalised (implementation in progress) and it will have a subpage dedicated to documentation. For prioritisation, I think that docs will be enough with the following contents ready for the release of this website (headlines, for reference and can be changed):

1. Getting Started
  - Installing Juvix
  - Writing your first smart contract
  - Deploying the contract to Tezos
2. Programming an example
3. Contract development lifecycle & deployment procedures
4. Programming in Juvix: basic features
  - Datatypes
  - Pattern matching
  - Dependent types
  - Programming in Juvix: advanced features
  - Usage accounting
  - Modules
  - Writing proofs

The above content will be displayed in the following subpage:
<img width="876" alt="Screenshot 2020-08-19 at 09 50 12" src="https://user-images.githubusercontent.com/11296013/90607372-683e9d00-e201-11ea-94f7-fafca7e76ac1.png">

**Comment by cyberglot** [comment]
@awasunyin would you lmk what code theme are we going to use for the website so I can optimise our syntax highlighting for it? (sadly, this kinda of stuff is theme-dependent)

**Comment by awasunyin** [comment]
@cyberglot actually I wanted to ask you about it, as you've been working on the syntax highlighting plugins for different code editors. I'll ask the web developer to implement the same theme as for VS code, if there's something I can share with him already it'd be great.

**Comment by cyberglot** [comment]
> @cyberglot actually I wanted to ask you about it, as you've been working on the syntax highlighting plugins for different code editors. I'll ask the web developer to implement the same theme as for VS code, if there's something I can share with him already it'd be great.

the user can choose the theme for VSCode, and I've been trying to be the most compatible with famous themes.

**Comment by cyberglot** [comment]
Here is a list of the most famous VSCode themes (I'd suggest picking one of them for the juvix website):

- [Dracula](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)
- [Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)
- [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple)
- [One Monokai](https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai)
- [PaleNight](https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme)
- [SynthWave](https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode)
- [Horizon](https://marketplace.visualstudio.com/items?itemName=jolaleye.horizon-theme-vscode)

I personally would choose Horizon Light for the website, but it's your choice. Lmk so I can extra test it in advance.

**Comment by awasunyin** [comment]
> I personally would choose Horizon Light for the website, but it's your choice. Lmk so I can extra test it in advance.
- Thanks @cyberglot! I'll make this suggestion to the web developer (he hasn't gone so far yet).

**Comment by awasunyin** [comment]
The web developer has strongly recommended us to write the source of the docs in **MarkDown** (vs. LaTeX, as initially planned). 

The reasons are manifold:
- On web interfaces, MarkDown is the standard for content, which means that accessibility might be limited in some browsers and or devices if the website has to handle some LaTeX source.
- MarkDown can be enhanced via many plugins. For example, if we wish to include formulae, there's this library https://github.com/remarkjs/remark-math
- For more complex graphics, we can perhaps export an image and add the image to the docs
- Some popular languages docs have their source in MarkDown as well, e.g. https://doc.rust-lang.org/book/ https://github.com/rust-lang/book/blob/master/src/title-page.md

Something to keep in mind for doc writers is the following list of plugins: https://github.com/remarkjs/remark/blob/HEAD/doc/plugins.md

When writing the docs and wishing some fancy components to add, browse through the list above and see what can be easily enabled.

**Comment by awasunyin** [comment]
@mariari this is how your markdown files look on the website: https://juvix.wip.swifle.com/docs/basic-features/

**Comment by cwgoes** [comment]
Hmm, it's mostly correct but there are some formatting oddities? Also we definitely need syntax highlighting.

**Comment by awasunyin** [comment]
Can you point out specific formatting oddities? 

About syntax highlighting, the source code snippets are in .jvx correct?

**Comment by cwgoes** [comment]
The extension is now `.ju`, but yes, the source code syntax snippets should all be highlightable.

**Comment by awasunyin** [comment]
@mariari any comments on the markdown on the website?: https://juvix.wip.swifle.com/docs/basic-features/ We need to confirm that your markdown files (from whatever source) are rendered as you intended.

@cwgoes 
> it's mostly correct but there are some formatting oddities?
- Can you point out the formatting oddities?

**Comment by mariari** [comment]
> @mariari any comments on the markdown on the website?: https://juvix.wip.swifle.com/docs/basic-features/ We need to confirm that your markdown files (from whatever source) are rendered as you intended.
> 
> @cwgoes
> 
> > it's mostly correct but there are some formatting oddities?
> 
> * Can you point out the formatting oddities?

Overall it looks like I expect... maybe i overlooked something as per @cwgoes ?

**Comment by cwgoes** [comment]
Slightly misaligned:

![2020-10-17-224603_937x546_scrot](https://user-images.githubusercontent.com/24760279/96353248-8c680e80-10ca-11eb-9ef8-78b6b30ca4bd.png)

![2020-10-17-224636_439x354_scrot](https://user-images.githubusercontent.com/24760279/96353258-a0137500-10ca-11eb-8af6-3479ba6feeca.png)

Also, I suggest we increase the font size and maybe change the colour scheme a little, just to make it easier to read all the text.

**Comment by MaximeWillinger** [comment]
Hello 👋 

The syntax highlighting on the documentation website is independent of the Markdown parser.
We use [PrismJS](https://prismjs.com/) for this task. There is a [guide](https://prismjs.com/extending.html#creating-a-new-language-definition) on how to create a custom language definition.

Since you have already written a fairly similar grammar definition for your VSCode plugin, I think it would be a good idea if you would take care of this one as well. Does this seem feasible to you ?

Alternatively, we can also use [highlight.js](https://highlightjs.org/). It's a very similar library, although PrismJS is lighter. A [language definition guide](https://highlightjs.readthedocs.io/en/latest/language-guide.html) is also available.

Feel free to ask me if you need more information.

@cwgoes thanks for the other UI issues. I will fix them.

**Comment by cwgoes** [comment]
@cyberglot Do you think we could create this sort of language syntax highlighting definition easily from our existing ones?

**Comment by cyberglot** [comment]
> @cyberglot Do you think we could create this sort of language syntax highlighting definition easily from our existing ones?

Prism doesn't seem to follow any editor standard language for syntax highlighting definition (or at least it doesn't state it), but it should be in the same spirit as the work we've already done.

**Comment by cwgoes** [comment]
> > @cyberglot Do you think we could create this sort of language syntax highlighting definition easily from our existing ones?
> 
> Prism doesn't seem to follow any editor standard language for syntax highlighting definition (or at least it doesn't state it), but it should be in the same spirit as the work we've already done.

Great - do you think you could help with this, if possible?

**Comment by cyberglot** [comment]
> Great - do you think you could help with this, if possible?

sure, np :)

**Comment by cwgoes** [comment]
A quickstart guide should be appended to the existing docs.

**Comment by cwgoes** [comment]
Juvix docs are to be reconceptualised; this issue is out-of-date.
