### ISSUE TITLE
Open resolution

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#487]
So far it seems rust model for single files works fine

```rust
mod bar {
    pub mod foo {
        pub fn another_function() {
            println!("Another function.");
        }
    }
}

use bar::*;

fn test() {
    foo::another_function();
}

```

compiles

```rust
mod bar {
    pub mod foo {
        pub fn another_function() {
            println!("Another function.");
        }
    }
}

use bar::*;

fn test() {
    foo::another_function();
}


mod foo {
    pub mod bar {
        pub mod foo {
            pub fn another_function() {
                println!("Another function.");
            }
        }
    }
}
```

does not compile.

This example represents a pathological case for unordered definition languages, as what do you accept?

Further posts will disect this more, namely how this works through different files compiled with cargo

**Comment by mariari** [comment]
It seems rust's files work similarly, however there are annoyances we should avoid

```bash
src/
├── bar
│   └── foo.rs
├── bar.rs
├── foo
│   ├── bar
│   │   └── foo.rs
│   └── bar.rs
├── foo.rs
└── main.rs

```

is the file structure needed... the `foo.rs` above `foo/` is only there to say `pub mod bar;`

in the main.rs we have

```rust
mod foo;

use foo::*;

fn main() {
    // my::test::another_function();
    // foo::another_function();
    bar::foo::another_function();
    foo::bar::foo::another_function();
    println!("Hello, world!");
}

mod bar;

```

Like the file example, we are forced in making our inner modules explicit with mod.

thus we get to the same solution, with `use foo::*` being ignored in favor for the `mod foo`

**Comment by mariari** [comment]
In short, we can describe rust's behavior as

Locals beat opens.

 
This means that no matter the order it should be consistent.

Though this does not shine the light on who wins if we make it two locals instead of savin ourselves with a `mod` below us

**Comment by cwgoes** [comment]
> Locals beat opens.

I think this is reasonable, at least for the time being.

I think we probably don't want separate namespaces for functions & modules? How would we even do that? Seems strange.

**Comment by mariari** [comment]
> > Locals beat opens.
> 
> I think this is reasonable, at least for the time being.
> 
> I think we probably don't want separate namespaces for functions & modules? How would we even do that? Seems strange.

We won't, this is just how rust works.

We are only really taking their resolution mechanism, basically 

> locals beat opens.

**Comment by cwgoes** [comment]
"I have a strategy" - @mariari
