### ISSUE TITLE
Increase efficiency using Idris 2's implementation of inlining and erasure

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#488]
In Idris 2, inlining, erasure etc are done in `CExp`, right before the programs maps to Chez scheme. Brady noted that the inlining here yields huge efficiency gains. Unfortunately he didn't elaborate further on this. (@cwgoes see [here](https://github.com/idris-lang/Idris2/blob/master/src/Compiler/CompileExpr.idr))

**Comment by cwgoes** [comment]
Aye, we are planning to do inlining after the erasure step.

**Comment by cwgoes** [comment]
Out of date / superseded
