### ISSUE TITLE
Interactive editing support

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#493]
Similar to Agda's interactive editing support, Idris 2 has interactive editor support in [Vim](https://idris2.readthedocs.io/en/latest/tutorial/interactive.html) and other editors. Juvix should have similar support. According to [Edwin Brady](https://edwinb.wordpress.com/2013/10/28/interactive-idris-editing-with-vim/), a lot of work can be done via the REPL (at the `TTImp` level), which makes it easy to adopt to other editors. See the code for [vim](https://github.com/edwinb/idris2-vim) and [emac](https://github.com/idris-hackers/idris-mode) editor support.

**Comment by cyberglot** [comment]
I talked to some agda people about what would they like to see improved on agda-mode for emacs (their main tool) and it was quite iluminating. I will add the info I gathered to this issue.

**Comment by cwgoes** [comment]
Out-of-date.
