### ISSUE TITLE
Remove parseX and reservedX fields from Parameterisation

### ISSUE THREAD

**Issue by andy-morris** [anoma/juvix#512]
Instead the main parser recognises literals in some standard format (instead of per-param), and if (e.g.) `stringVal` returns `Nothing` then that is treated as a parse failure. Perhaps the `xxVal` fields should return an `Either String primVal` or something similar.

The `reservedX` fields are just the keys from `builtinX`.

**Comment by cwgoes** [comment]
This has since been done.
