### ISSUE TITLE
O(1) symbol comparison

### ISSUE THREAD

**Issue by andy-morris** [anoma/juvix#532]
A while back I wrote a library for [hash consing](https://github.com/andy-morris/hashcons), which maybe we could apply to `Symbol` some time.

It's designed to be usable with whole ASTs too, but it might be a pain to make it play nice with extensible. But it still might be worth looking into in future if our conversion checking ends up being annoyingly slow.

**Comment by cwgoes** [comment]
Closed as a duplicate.
