### ISSUE TITLE
Core representation for tuples

### ISSUE THREAD

**Issue by andy-morris** [anoma/juvix#533]
I think there are basically two possibilities for representing tuples in core:

1. **Built in Σ types and terms**—simpler, but the backend would have to flatten them if we want that
2. **Special type and term formers for n-ary products**—a bit more complicated, especially with the eliminator, but already flattened
3. ~~**Syntax sugar for some types in the stdlib**~~—probably a non-option until they can be parameterised by usage

---

Somewhat related, I think a number of things would probably be simpler if lists were made a core primitive too?

**Comment by cwgoes** [comment]
By "flatten", do you mean convert nested tuples into "flattened" n-ary tuples?

I think it is fine to have the backend or some post-core pass do that.

**Comment by andy-morris** [comment]
Yeah exactly. The only problem with a post-core pass is that we'd have to make sure we did it consistently.

For example, if we have

```
let f x y = (x, y)
let g y = y
let h x y = (g x, f x y)
```

we need to be careful not to end up with parts of the output treating `h 1 2` as `(1, 1, 2)` and other parts as `(1, (1, 2))`.

**Comment by cwgoes** [comment]
> edit: actually it looks like michelson might also only have nested pairs? In which case we don't even have to do that so option 1 is probably just The Right Answer™.

For now, at least - also I think we can still have a single (post-typechecking) pass for this anyways in the future.

**Comment by atennapel** [comment]
Just a note, if you have an explicitly typed core language and you want to have a simple type check algorithm for it, then you cannot retrieve the type of a tuple from just `(1, 2)`, because the type of the second component depends on the first value. You'd need to have tuples like `(1, 2 : (x : Nat) ** Nat)` or `(1, x : Nat. 2)` or so.

**Comment by cwgoes** [comment]
Got'em.
