### ISSUE TITLE
Consider supporting first class polymorphism

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#566]
See [A Quick Look at Impredicativity](https://www.microsoft.com/en-us/research/uploads/prod/2020/01/quick-look-icfp20.pdf). Not a priority atm but it's certainly a good feature to add later on.

**Comment by atennapel** [comment]
Also see the paper and implementation "Elaboration with First-Class Implicit Function Types" which is a more general (but more complicated) solution to the problem (https://github.com/AndrasKovacs/implicit-fun-elaboration).

**Comment by cwgoes** [comment]
Sounds like this doesn't apply to us.
