### ISSUE TITLE
Refactor the context passes to be more generic

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#570]
Currently the haskell backend has the following effects for any part of the syntax transformation

```haskell

type WorkingMaps m =
  ( HasState "old" (Old Context.T) m,
    HasState "new" (New Context.T) m,
    HasThrow "error" Error m
  )
```

We should weaken this to not refer to any particular map when possible.

Instead just have an interface for a context we query, and that in our entire transformation will query both maps for us.

**Comment by cwgoes** [comment]
Superseded by S-expressions.
