### ISSUE TITLE
An Iterative compiler Approach

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#571]
One aspect of our current compiler development leads to long stretches of code without really seeing an effect nor the ability to test it.

Thus I propose that compiler development should instead be done by allowing small simple parts of the juvix programming language to be compiled and expand from there.

We shall refer to this approach as the iterative compiler approach.

Namely for the the LLVM backend an iterative approach would look something like this:

1) compile simple numbers
2) compile an enum subset of case expressions
3) compile all non dependent parts of case expressions
4) compile simple functions
5) compile closures
6) ...
7) finish subset of the juvix compiler with all features working properly

As we work on these steps, one could also refactor parts of it to improve code generation. This is safe as the iterative approach allows incremental testing of each feature after they are finished.

Thus, instead of having to wait for large swaths of the compiler to be done to test behavior and have a large surface area for errors, instead we have a very small surface area and debugging is thus easier.

**Comment by cyberglot** [comment]
something like the [nanopass framework](http://andykeep.com/pubs/dissertation.pdf)?

**Comment by mariari** [comment]
When we get to the point of compiling continuations and GC re-read: 
  `From Folklore to Fact: Comparing Implementations of Stacks and Continuations`
In full

**Comment by cwgoes** [comment]
Agreed by social consensus.
