### ISSUE TITLE
Frontend desugaring tactics

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#61]
(related to #4 )

Different approaches to elaborate from a (slightly desugared) Juvix to the Juvix Core include:
- [Idris](https://github.com/cryptiumlabs/research/blob/master/weekly-papers/2019-08-23-idris/paper.pdf) approach:

Elaboration monad with tactics.

**Adv:** it is possible to expose tactics to the programmer. This opens up the possibility of implementing domain specific decision procedures, or implementing user defined tactics. (Very suitable for smart contract dev/Juvix)

- [Matita](https://www.researchgate.net/publication/220805831_The_Matita_Interactive_Theorem_Prover) approach:

A type directed approach, maintaining a set of yet to be solved unification problems and relying
on a small kernel, similar to IDRIS, but using refinement rules rather than tactics.

**Adv:** good error messages (very important I think!) though it is not clear how easy
it would be to extend to additional high-level language features, unlike the tactic-based
approach.

- Agda approach ([Norell, 2007](http://www.cse.chalmers.se/~ulfn/papers/thesis.pdf)):

Add metavariables and implicit arguments to the type theory.

**Adv:** implicit arguments can be used more freely (e.g., in higher order function arguments).
**Disadv:** more complicated type system.

- Epigram ([McBride & McKinna 2004](http://strictlypositive.org/vfl.pdf)) and (McBride [1999](https://pdfs.semanticscholar.org/47c8/e47d2c6ddfaba65b80e0221a8e8f567afced.pdf), [2000](http://www.e-pig.org/downloads/elim.pdf)):

It doesn't implement pattern matching directly. It translates pattern matching into elimination rules.

**Adv:** 
1. elimination rules provide termination and coverage proofs by construction. 
2. implementation of the evaluator is simplified, which provide easy optimization opportunities.

**Disadv:**
Requires the implementation of extra machinery for constructor manipulation.

We should look into these approaches further and pick and choose the best features/approaches for Juvix. Ideally have a design document explaining the details like the IDRIS paper, then implement it.

**Comment by cwgoes** [comment]
I think, for the first version, we should probably start with a tactic-based approach close to Idris.

Avoiding complexity in the core language & type theory is pretty important since it both reduces the chance of mistakes leading to lack of soundness / type preservation and should make optimisation easier ([ideally we can avoid data-types & pattern matching in the core](https://github.com/cryptiumlabs/juvix/issues/31#issuecomment-565753170)).

**Comment by cwgoes** [comment]
Superseded by Witch.
