### ISSUE TITLE
The Internal Juvix S-expression language 

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#634]
## Purpose

The purpose of the juvix S-Expression language is to facilitate a few things throuhgout our code base which we be listed as following:

1) Serves as a generic type throughout the passes.
    * Currently we have quite a bit of code in each pass
    ```haskell

     cloc library/Translate/src
          39 text files.
          39 unique files.
           0 files ignored.

    github.com/AlDanial/cloc v 1.88  T=0.02 s (1560.7 files/s, 265325.5 lines/s)
    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    Haskell                         39           1277            959           4394
    -------------------------------------------------------------------------------
    SUM:                            39           1277            959           4394
    -------------------------------------------------------------------------------

    ```
     Most of these come from redundant boilerplate to properly translate one trees that grow structure into another.
     Even if we had a fully automated way from going to one tree to another it'd still be quite a hassle. Note another alternative exists which we will get into in the Alternatives section.
  * Furhter what this means that to get to a certain part of the code base we either have to do one of two options.
    1) Write the structured AST by hand.
        * This option is mostly fine, however trying to write code which can go through a certain phase forces you to have the **specific** module with the constructors open.
        * Further we can have no generic parser for each phase unless major refactoring work is done.
        * This however does force us to write the correct pass which is a bonus.
    2) Write front end syntax, then run the translation phases to the step we need.
        * This forces every step along the way to be correct.
        * Further it forces us to force our way through boilerplate for very simple test data.
    + If we were to instead have SEXPs throughout the codebase, we could write a generic simple parser that can give us any phase we would want, thus bypassing these issues.
  * This also ties our passes in a fixed order.
    * Since we are moving from 1 AST tree to another, we have to fix the order, and the boilerplate may change based on the previous passes.
    * Further since all passes have to deal with the entire AST, we have to update every single pass for new constraints.
    * However with SEXPs we could just have each pass edit what they care about, thus giving us the freedom to mix ordering, as long as the passes don't conflict with each other in some way.
  * Lastly, This causes the enviornments in the translation functiosn to care about module semantics.
    * Since each pass is Type1 → Type2, both these types can't exist in the same context map, which means any pass in the context part has to allocate a second map, and has to internally deal with any oddities of context lookup. Instead of the context being able to handle all the complexities, we force that into every single context translation pass.
      * This makes it quite easy to make a semantic msitake that shouldn't exist.
2) Allows for a future Juvix macro language
  * Any serious language has some form of macro system, the more hacked on it is, the more complicated and arcane it is. To try to deal with this I propose that we can achieve homoiconic macros in Juvix through this intenral language.
  * My ideas are not fully fleshed out, so instead of giving the full details of what this entials I will note the rough idea of what I forsee.
  * Since Juvix desguars into SEXPs we can have a macro evaluator for our passes. So Cond desugaring into if desugaring into pattern matching could all be juvix level macros. Our macros will be run on a SEXP type much like what we will be processing in this planend refactor.
  * We will thus be able to desguar top level juvix ML syntax into this LISP internal structure for it to be processed.
  * The only complication is that we need a way from getting a juvix LISP macro into a juvix ML macro. This involes reader hackery that I have yet to think about, however the rest of the process is quite straightforward.
    * Firstly this gives us the ability to write macros in a backwards compatable way given we reserve \` and `~`.
      * This is the case we don't actually need to change anything in the frontend to preserve this!
    * Secondly, macros will be defined on the SEXP structure we provide.
    * When users call this, they can write simple Juvix ML without realizing they are using a SEXP macro
      ```juvix
      -- just for demonstration purposes
      -- let gets turned into define on the top level to distinguish top level declarations and local scoped functions
      -- this macro takes a function and renames it to bar
      macro-let foo (Literal define :: name :: body) = `(define bar ~@body)

      foo (let baz = 5)

      -- macro expands into
      -- let bar = 5
      ```
    * What they can't do is export new syntax like our cond syntax... that is until we think of a way to go from LISP macro → ML reader.

## Alternatives
Currently we have an alternative strategy for 1). Namely Generics. Generics would give us very similar properties as SEXP does, however it does not satisfy the benefits of 2). more reserach should go into comparing and contrasting these ideas.

**Comment by cwgoes** [comment]
Thank you. I agree that we need either something like this or generics. I'm a bit skeptical about adding a bunch of Lisp code - not because I don't like Lisp (I do!) but because that will introduce a lot of awkward conversions and potential future maintenance headaches. Is there a way to accomplish this without such a drastic syntax change, or do you think it's necessary?

**Comment by mariari** [comment]
> Thank you for the writeup. I agree that we need either something like this or generics. I'm a bit skeptical about adding a bunch of Lisp code - not because I don't like Lisp (I do!) but because that will introduce a lot of awkward conversions and potential future maintenance headaches. Is there a way to accomplish this without such a drastic syntax change, or do you think it's necessary?

Well we'd just be writing juvix code, the code average every day users use won't be lisp at all. This just gives us an easy way of gaining macros while still being an ML?

I'm not sure of what syntax change you mean, do you mean the intenral desugaring of it all? It seems lots of language do this to a degree, I know you can make ocaml spit out lisp code as it desugars into that itself (GCC does as well... but we shant talk about that).

Care to mention what maintance headaches you are thinking of? Most things will have a fairly direct translation

top-level let -> define

inner-let -> let

match -> match

\x -> lambda (x)

etc. etc.

as for 

> Is there a way to accomplish this without such a drastic syntax change, or do you think it's necessary?

I think it might be. I'll read about scheme macros and how that got turned into rust or elixir macros, but I'll likely find the translations not satisfying (I think I"ll find scheme style macros as being better, but that is besides the point). I want macros to be easy to write and easy to read, with most people not using them. Hence we'd have functions which could lisp-ify any statment given to them so they can see what kind of structure they need to write code over. That way it's very obvious what the macro does, and there is no disconnect between what the compiler sees and what you as the programmer sees.

But I think a macro system is quite important in the long run, and when it comes to end user applications, it really makes many classes of applications more readable and approachable. Combine that with our images and strong type system, it'll be very powerful yet very safe. We can maybe even combine these techniques with type system macros to create something truly amazing.

As a side note, the Lisp -> ML part of the plan will allow GHC style syntax extensions to be had without having to bake it into our compiler. That is what I suspect will be the only hard part of the design and something I need to sit down for an afternoon and flesh out.

**Comment by mariari** [comment]
Upon looking at elixir for a little bit, they seem to have a hygenic version of CL style macros, as internally it's a homoiconic language


example taken from: https://elixir-lang.org/getting-started/meta/macros.html
```elixir
 defmodule Unless do
  # function version which doesn't work properly!
  def fun_unless(clause, do: expression) do
    if(!clause, do: expression)
  end

  defmacro macro_unless(clause, do: expression) do
    quote do
      if(!unquote(clause), do: unquote(expression))
    end
  end
end

```

here is our unless macro, it uses quote and unquote much like CL! However the interesting part is what it takes

```elixir
Unless.macro_unless true, do: IO.puts "this should never be printed"

# gets the following

macro_unless(true, [do: {{:., [], [{:__aliases__, [alias: false], [:IO]}, :puts]}, [], ["this should never be printed"]}])

# generates 
{:if, [],
 [{:!, [], [true]},
  [do: {{:., [],
     [{:__aliases__,
       [], [:IO]},
      :puts]}, [], ["this should never be printed"]}]]}

```

Note that the page also shows that it can print it back in elixir style sytnax!

This article shows the homoiconicity of the underlying elxiir form

http://www.petecorey.com/blog/2017/08/07/what-if-elixir-were-homoiconic/

However my main complaint with this system is that their macro system is pretty unreadable (This may be caused by their macro -> elixir syntax which this form may give them benefits). What I'm suggesting is something much closer to our ML frontend!

**Comment by mariari** [comment]
It seems scheme style macros are similar to CL style but quite a bit different!

At least this is true for `syntax-rules`

```racket
(define-syntax my-cond
  (syntax-rules (else)
    ((_ (else e1 ...))
     (begin e1 ...))
    ((_ (e1 e2 ...))
     (when e1 e2 ...))
    ((_ (e1 e2 ...) c1 ...)
     (if e1
	 (begin e2 ...)
	 (cond c1 ...)))))
```

here is my CL version

```lisp
(defmacro our-cond (&body lists)
  (reduce (lambda (x ys)
            `(if ,(car x)
                 (progn ,@(cdr x))
                 ,ys))
          lists :initial-value nil :from-end t))
```

The main versions is in the `define-syntax` + `syntax-rules` version we don't need to unquote and mention what we generate as hygeine covers that for us. Furhter it mentions it introduces the literal symbol `else` into the scope which is a very nice touch.

Hygenic macros  definitely have high value as they are referentially transparent, however the small snipits I've seen of racket's complex transformations seem much less readable than their common lisp counter parts. More research needs to be done into how this works.

Oleg has a seris of articles on how to get scheme macros to compose better [1], which leads me to believe that scheme style macros may be the better choice, and either should work with the plan I have above  

[1]: http://okmij.org/ftp/Scheme/macros.html#Macro-CPS-programming

**Comment by cwgoes** [comment]
Can we write up a few more examples of what (real) macros in Juvix using this system would look like?

**Comment by cwgoes** [comment]
We now have S-expressions! Other topics are discussed elsewhere.
