### ISSUE TITLE
Smplifcation on the passes down

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#672]
Currently the Translation passes require 2 or 3 maps to go down. On whole program compilation this is just the transition from the old context type to the new one. However for the interpreter we currently need 3. One for the current context, and 2 for the transition functionality. Issue #634 Lays out a proposed solution.

Once we have SEXPs in some form down our pipeline we could instead do a much simpler task.

Since our translation steps now act more as macros, we could instead just run it over the new forms that come in, checking the context for various bits of information we need to fully do this.

Once we are done we can then commit it to the context as the proper fully fledged form.

This will likely happen in Phase 2 of #671

**Comment by cwgoes** [comment]
Superseded by idealised pipeline discussions.
