### ISSUE TITLE
Unable to run example code

### ISSUE THREAD

**Issue by fdedden** [anoma/juvix#677]
As mentioned in #674, there are some problems with the code at https://juvix.org/docs/example/. This very piece of code is used in multiple places in the `doc` directory as well.

* [x] rename usage of `Tree` to `tree`.
* [x] provide a signature for `func2`.
* [ ] Add necessary `open`s to the file.
* [ ] Implement `==` and add it to one of the preludes.

To make the example work, several `open`'s would need to be added for the preludes. If this is something we want, depends on the surrounding text. If it is just a showcase of some features, we don't need to add it. On the website however, I think it should be a self-contained piece of code.

**Comment by fdedden** [comment]
I have added @cwgoes and @mariari as these are the original committers of the files.

**Comment by cwgoes** [comment]
Indeed; this example is slightly out-of-date. We should add module opens and make changes as necessary to make it work.

Also, this should eventually be a compilable contract to Michelson, which means it needs a main function with the appropriate type.

**Comment by fdedden** [comment]
After implementing `==`, a new error is thrown:
```
Elaboration of expression
Match' (Match''' {matchOn = Name' ("foo" :| []) (), matchBindigns = MatchL' {matchLPattern = MatchLogic' {matchLogicContents = MatchCon' ("Branch" :| []) [MatchLogic' {matchLogicContents = MatchName' "left" (), matchLogicNamed = Nothing, annMatchLogic = ()},MatchLogic' {matchLogicContents = MatchName' "ele" (), matchLogicNamed = Nothing, annMatchLogic = ()},MatchLogic' {matchLogicContents = MatchName' "right" (), matchLogicNamed = Nothing, annMatchLogic = ()}] (), matchLogicNamed = Nothing, annMatchLogic = ()}, matchLBody = Application' (App' {applicationName = Name' ("TopLevel" :| ["Prelude","Michelson","Alias","+"]) (), applicationArgs = Application' (App' {applicationName = Name' ("TopLevel" :| ["Prelude","Michelson","Alias","+"]) (), applicationArgs = Application' (App' {applicationName = Name' ("func" :| []) (), applicationArgs = Name' ("left" :| []) () :| [], annApp = ()}) () :| [Name' ("ele" :| []) ()], annApp = ()}) () :| [Application' (App' {applicationName = Name' ("func" :| []) (), applicationArgs = Name' ("right" :| []) () :| [], annApp = ()}) ()], annApp = ()}) (), annMatchL = ()} :| [MatchL' {matchLPattern = MatchLogic' {matchLogicContents = MatchCon' ("Leaf" :| []) [MatchLogic' {matchLogicContents = MatchName' "ele" (), matchLogicNamed = Nothing, annMatchLogic = ()}] (), matchLogicNamed = Nothing, annMatchLogic = ()}, matchLBody = Name' ("ele" :| []) (), annMatchL = ()},MatchL' {matchLPattern = MatchLogic' {matchLogicContents = MatchCon' ("Empty" :| []) [] (), matchLogicNamed = Nothing, annMatchLogic = ()}, matchLBody = Constant' (Number' (Integer'' 0 ()) ()) (), annMatchL = ()}], annMatch'' = ()}) ()
is not yet implemented
```

**Comment by fdedden** [comment]
Some more tasks before completion:
- [ ] Add necessary `open`'s to the file.
- [ ] Implement `==` and add it to one of the preludes.

**Comment by cwgoes** [comment]
This example is still out-of-date.

@rokopt Do you think we could do something a bit similar (perhaps simpler) with products/coproducts now?
