### ISSUE TITLE
Incorrect types for a couple of primitives

### ISSUE THREAD

**Issue by andy-morris** [anoma/juvix#721]
- `Mul`/`EDivMutez` need one `nat` argument and one `mutez` argument, in either order, rather than two `mutez`-es
- Same for `Add`/`SubTimeStamp` with `int`

**Comment by cyberglot** [comment]
I think I typed them based on Morley's types, but it was 200 years ago (aka about 6 months)? I can fix them if everyone's busy.

**Comment by cwgoes** [comment]
@cyberglot That'd be great if you have a chance (should be minor presumably).
