### ISSUE TITLE
Having easy testing functionality

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#731]
Currently, I keep an uncommited file with a bunch of functions like

```haskell

contextualizeFoo ::
  ByteString ->
  IO
    ( Either
        Context.PathError
        (Contextify.ContextSexp, [Contextify.PreQualified])
    )
contextualizeFoo byte =
  Contextualize.contextifyS (("Foo", parseDesugarSexp byte) :| [])

parseDesugarSexp :: ByteString -> [Sexp.T]
parseDesugarSexp = Desugar.op . parsedSexp

parsedSexp :: ByteString -> [Sexp.T]
parsedSexp xs = ignoreHeader (Parser.parse xs) >>| SexpTrans.transTopLevel

ignoreHeader :: Either a (Frontend.Header topLevel) -> [topLevel]
ignoreHeader (Right (Frontend.NoHeader xs)) = xs
ignoreHeader _ = error "not no header"

```

along with a bunch of imports to quickly test functions in the REPL, along with copy and pasting theese into various files for testing. It would be nice to have such functionality exported in the `Translate` package for quickly sending various forms down the pipeline with less fussing about import dependencies etc.

**Comment by cwgoes** [comment]
Can you explicate?

**Comment by cwgoes** [comment]
Superseded by the EZ-pipeline.
