### ISSUE TITLE
Run precommit script on the CI only

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#749]
As suggested by @Fraccaman we shouldn't need to bother with running the formatter and org-gen. We'll let the pipeline do and push those steps.

**Comment by cwgoes** [comment]
Hmm, this is alright if and only if we can do it in a way which doesn't create many extra commits, since that would be annoying when reading Git logs etc.

**Comment by Fraccaman** [comment]
As PRs commit are squashed when merged, would it be a problem to run the precommit scripts only for pull requests? Or will it cause problems when reviewing ?

**Comment by cwgoes** [comment]
If the commit is squashed into the merge, that should be fine, I think.

**Comment by cwgoes** [comment]
CI now does amazing things, thank you @Fraccaman
