### ISSUE TITLE
List of Known Bugs

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#755]
# Bug

1. Qualified error on Imported types
   - Stops in FromFrontend due to a small bug
   - see #752
2. Nesting of 3 or more expressions
   - Issue in CheckTerm.hs
   - If we have a form like `-> make-pair nil (add (car ps) (cdr ps))`, then our compiler fails to evlauate this expression.
   - See #750
     - Progress → https://github.com/heliaxdev/juvix/pull/750#issuecomment-844211739
3. Parser has constructors take forms it shouldn't.
   - See #703
4. Inlining equivalent terms only works for a single level. #806
   - → #805
5. Inconsistent recursiveness of let #864  
6. #865. Name Resolution being inaccurate with modules

**Comment by systemf-frank** [comment]
Found some problems with (I guess) type inference:
```haskell
mod MichelsonTest where

open Prelude
open Prelude.Michelson

sig main : int
let main = add int 2 5
```
Gives us troubles:
```
$ stack run -- typecheck -b michelson MichelsonTest.ju
Elim' (App' (App' (App' (Free' (Global ("Prelude" :| ["Michelson","add"])) ()) (Elim' (Free' (Global ("Prelude" :| ["Michelson","int"])) ()) ()) ()) (Prim' (Constant (ValueInt 2)) ()) ()) (Prim' (Constant (ValueInt 5)) ()) ()) ()
"TypecheckerError unbound index 0"
```

Implementing an alias for `add int` does work like expected:
```haskell
mod MichelsonTest where

open Prelude
open Prelude.Michelson

sig addnew : int -> int -> int
let addnew = add int

sig main : int
let main = addnew 2 5
```
