### ISSUE TITLE
Strategies For Core

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#759]
### Preamble

Currently Core's strategy for extending itself is not ideal. It causes some confusion for others coming in along with a variety of other issues.

In the past the following choices were discussed on how to deal with sum type extensions.

1. Extensible (Trees that Grow)
2. Tagless Final

However it has come time to re-evaluate our options, however this time we have 5 choices

1. Extensible
2. Tagless Final
3. S-expressions
4. Hybrid of Merging Core and S-expressions
5. Merge Core into a single structure
6. Data types à la Carte
7. Refined S-expressions

The sections below will discuss benfits and downsides to each of these five techniques.

### Merge Core into a single structure

This strategy merges all our extensible extensions into 1 form.

#### Pros
- We have an understandable Layer  of an ADT with no type indirections
- We can write generic algorithms on this form

#### Cons
- We lose exhaustion due to some forms not being valid (Haskell's liquid would solve this)
- It may not be clear which algorithms work on which subset with the signature
- This form has to be updated with any extensions we write, cuasing annoying refactoring.

### Hybrid of Merging Core and S-expressions
Here we do a smart strategy, where for generic processing we turn our strucutre into S-expressions, but we can solidfy them for exhaustion and algorithm safety reasons

#### Pros
- All the Pros in the S-expression section
- The algorithms on the typed forms are obvious about which form they are on.
- Flexible in how much structure we care about
  - This become the new annotations, where we simplify the language
- We can lay out our core like the translation passes, with obivous control flows and many more short lived core forms.
  - Example: After running type-checking of pattern matching and algorithms for dependent match, we can simplify the definition form to remove match  and have an explicit match form.
  - This leaves us with the match in an optimal way for type checking, but allows us to regain simplicity after it
- Allows A more minimal Juvix standalone language
  - We can have a minimal implementation language that LLVM, Michelson etc. can implement that Core itself desugars to, fomralizing this in a natural way  

#### Cons
- We have to redefine many of the same ADT's variants over and over
  - Though this highly depends on what you care about in each core pass 
- There may be some miscommunications due to the weaker typing in the more generic passes
- Requires more documentation

### Extensible

This is the current strategy for Core

#### Pros

- We have a rather clean way of expression sum types, as extensions.
- Seems logic can be shared between some parts (see Evaluation in Core).
- We have Exhaustion.

#### Cons
- Due to the tools of GHC, looking at the types by querying the system is hard to understand and confusing.
- To get generic code, we still need a lot of boilerplate of type classes (See Evaluation in Core again!).
- We still get separate types for the forms, thus to add a context we need to have logic that cares about how the context works!
    - this can be leviated by writing more code to properly handle different context types, and what not. 

### S-expressions

This uses the same structure as the rest of the codebase up to this point

#### Pros

- We have generic tooling for dealing with s-expressions.
- S-expressions are used in the rest of the codebase to success.
- Juvix bootstrapping will have it's meta syntax be seralized in this form.
- It's easy to work over S-expressions.
- Context we work over can stay a single type, meaning we don't have to care about the details of how the context works (thus we don't break our code upon changes).
- Would allow us to further develop tooling that we can share on other parts of the codebase.

#### Cons
- Haskell isn't strongly typed enough to give us exhaustion
- Haskell isn't strongly typed enough to give us refinements on the lists.
- May have to deal with mis-communication of some forms due to the above 2 issues. 
### Tagless Final

This is the catamorphism

#### Pros
- Seems to deal with the Expression Problem well
- Same type, so single context!

#### Cons
- Haskell doesn't make working over them nice
    - Thus we have to research how well Haskell has progressed in aiding using these.
- They are catamorphisms, so usually ill-suited for the kind of work that core deals with.

**Comment by cyberglot** [comment]
I really like S-expressions, but I'd be happier if we could make a library of type-safe S-expressions?

**Comment by mariari** [comment]
> I really like S-expressions, but I'd be happier if we could make a library of type-safe S-expressions?

I would as well. However with Haskell's tooling I'm unsure if we could?

I know if we had Juvix level types, we could put refinements on them to ensure certain lengths, and have certain kernels that we can be exhaustive over and extend dipsatch in a few places.

Without those, all I can really think of are what Andy suggested. Namely, maybe liquid haskell to restrain the types.

**Comment by cyberglot** [comment]
I agree that a Liquid Haskell-based S-expression library would be great.

**Comment by rokopt** [comment]
> I agree that a Liquid Haskell-based S-expression library would be great.

I like this too -- maybe we should call out using Liquid Haskell for refined-type S-expressions as a separate strategy.

During today's Core Q&A, we also brought up another possible strategy:  [Data Types à la Carte](http://www.cs.ru.nl/~W.Swierstra/Publications/DataTypesALaCarte.pdf).

Andy suggested that we might want to write some toy Core-like modules using each of the strategies that we think might be the best, and seeing how they compare once we've written some actual code.

**Comment by cyberglot** [comment]
Data types à la carte is basically the same thing as extensible effects and it's slow :(

**Comment by rokopt** [comment]
A seventh strategy that we've discussed is to use "refined S-expressions", that is, S-expressions with refinement types in the sense of (for example) Liquid Haskell.  One way of defining refinements to S-expressions is with patterns.  There's some sample development/prototyping underway here:

- https://github.com/heliaxdev/research/blob/terence/patterned-s-expressions/code/quantitative-categories-with-families/src/PatternedSExpressions.idr
- https://github.com/heliaxdev/research/blob/terence/patterned-s-expressions/code/quantitative-categories-with-families/src/Test/PatternedSExpressionsTest.idr
