### ISSUE TITLE
Idris 2 and Unification notes

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#782]
As we add more core features these notes may be helpful:

- [Lessons from Idris 2](https://gist.github.com/thealmarty/ad574da780b902461117e905b3c078aa)
- [Unification in Idris 2](https://gist.github.com/thealmarty/3b6e0d1ddadf87564618a99b6863be82#conversion)
- [MVP unification implementation plan](https://gist.github.com/thealmarty/0d9e18f02dcf9194749f0fe4f3aa11a2)

**Comment by cwgoes** [comment]
Notes saved; thank you.
