### ISSUE TITLE
Remove the usage from Σ 

### ISSUE THREAD

**Issue by andy-morris** [anoma/juvix#845]
- it doesn't mean anything (a value of type Σ(x: A) → B is two independent terms)
- it isn't used anywhere (the type is checked in a 0 context anyway, and the subterms are checked as the two separate terms that they are)

**Comment by andy-morris** [comment]
I'll try and clarify why the usage in Σ is unnecessary.

Let's say we have this program:

```
type Eq (A: ty 0) (0 x: A): A → ty 0 =
| refl: Eq x x     -- in full, refl : (0 A: ty 0) (0 x: A) → Eq x x

x : Nat
x = 0

refl-x : Σ (x: Nat) → x ≡ x
refl-x = 〈x, refl x〉
```

Here, `refl-x` only uses `x` once, since the argument to `refl`, and the occurrences in its type, are all zero. A usage in the fst of a pair would not even affect the typing of the snd; in any case in the Σ type rule

```
 Γ ⊢ σ s: A       Γ ⊢ σ t: B[s/x]
────────────────────────────────────
   Γ ⊢ σ 〈s, t〉: Σ(x: A). B
```

the context is the same in both halves so there is nowhere that the usage is used

It _is_ true that we will want to package up multiple uses of a value (in which case, the first premise would be with a usage of σπ instead of just σ, probably? something like that), but since this is orthogonal to pairing, I suggest we instead have a separate □ type for that like in grtt. Instead of Σ(2 x: A) → B we have Σ(x: □ 2 A) → B, 

As a side note, Σ can be a datatype, and so can □ as soon as we have first class usages (and universes, probably) and can write something like

```
type box {ℓ} π (A : ty ℓ): ty ℓ =
| Box: A -(π)-> box π A
```

**Comment by cwgoes** [comment]
> It is true that we will want to package up multiple uses of a value (in which case, the first premise would be with a usage of σπ instead of just σ, probably? something like that), but since this is orthogonal to pairing, I suggest we instead have a separate □ type for that like in grtt. Instead of Σ(2 x: A) → B we have Σ(x: □ 2 A) → B.

If we can do this without causing type theoretic problems I'm in favour of it.

**Comment by andy-morris** [comment]
pairs in general are superseded by records; see #962.
