### ISSUE TITLE
Standard Library Suggestions: Or how to Best Abuse Parallelism 

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#86]
Since we are using interaction nets for evaluation, we are in a unique situation to abuse parallelism. Thus I think we should keep this in mind when producing the standard library.

_Guy Steele has many talks on this issue_: 
1. [Organizing Functional Code for Parallel Execution; or, foldl and foldr Considered Slightly Harmful](https://vimeo.com/6624203)
    + Lots of great advice, avoid accumulators
    + think in terms of mapping small cases into the solution space and combine that!
    + [Slides here.](http://xahlee.info/comp/i/ICFPAugust2009Steele.pdf)
2. [How to Think about Parallel Programming: Not!](https://www.infoq.com/presentations/Thinking-Parallel-Programming/)
3. [Four Solutions to a Trivial Problem](https://www.youtube.com/watch?v=ftcIcn8AmSY)
    + Guy Steeele goes over a trivial problem four ways, using Fortress, shows parallel programming and how to think about it

There are of course more talks, we should thus discourage the use of `list` in the standard library, and provide a structure which does `list`'s job (A talk of Guy Steele goes over this).

We should also investigate how easy is it to prove parallel algorithms and compare it against proofs of sequential algorithms. If it turns out to be harder, then we simply need to show an equality of functions and provide the sequential for proving and the parallel for running.

**Comment by cwgoes** [comment]
Quite so; additionally, we may elect to have syntax (at least in some level of core) for explicit "parallelism hints" - which could be used to place markers to instruct the runtime as to which primary ports or subgraphs should be reduced in parallel, and also to cause the compiler to check whether a term can be in fact evaluated in parallel (which is convenient for the programmer, and helpful for https://github.com/cryptiumlabs/juvix/issues/45).

**Comment by mariari** [comment]
Some interesting results regarding [parallel evaluation of interaction nets](https://journal.ub.tu-berlin.de/eceasst/article/view/1034) have been found. Namely that running a function like `eq` is quite inefficient as it requires extra copying and erasing of lists for these.

Thus an interesting observation is thus had:

1. introduce a syntax for declaring if a type is to be bespoke encoded or evaluation should be done with inets
  - We could use cost analysis to show to the program the cost of this decision.
  - It should be rather easy however, if the structure looks naturally sequential, then a bespoke encoding should be used.
  - Functions on this structure would thus use normal evaluation, so no wasted computation on functions like eq
2.  To leverage inherently parallel functions like maps and folds with semigroups/monoids, we should make a type class toStream, which takes a sequential structure and converts it to a lazy structure in which parallel algorithms can be effectively run
  - This should be lazy, as we don't want to pay the cost of fully transforming the structure for no reason
  - Could be easily done via a finger tree
3. Have a module language, and at the declaration have all terms be Inet by default, but allow changing this to sequental evaluation.
4. Have special syntax for declaring if some definition should use inet, sequential, or a mix of both

5. Have view patterns
  - This would allow us to pattern match on structure that are quite odd internally (think finger tree, or the Haskell fgl library).

**Comment by mariari** [comment]
It seems [chuncked sequences](http://deepsea.inria.fr/chunkedseq/doc/chunkedseq.html) could be a good replacement for lists. They have performance similar to `STL::deque`. What remains to be seen is how well do they update in parallel (the link mentions not very well, but this warrents further investigation).

**Comment by cwgoes** [comment]
[Original paper on interaction nets with some data structures](https://dl.acm.org/citation.cfm?doid=96709.96718).
