### ISSUE TITLE
Create Interface for Closures

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#896]
### Premable

With the need of closures throughout the codebase (Core, Translation, Witch), it's good that we standardize the interface for it.

Rather than have a single source of a data structure that is useful for all passes, perhaps we can have the same interface but different implementations that extend the point in various ways with extra meta information

### Related PRs
- #895 
   - Adds Meta Information to the closure in an adhoc way

**Comment by cyberglot** [comment]
It would be interesting to discuss it cuz I needed order-dependent anonymous closures for Witch and I implemented it.
