### ISSUE TITLE
Easy Pipeline's `printTimelapse` appears not to work with `->`

### ISSUE THREAD

**Issue by rokopt** [anoma/juvix#969]
While trying to chase a bug that's part of #910 , I changed `Easy.hs`'s `timeLapse1` to read as follows:

```haskell
timeLapse1 :: IO ()
timeLapse1 = do
  printTimeLapse
   "sig (+) : int -> int -> int\n\
   \let (+) = %LLVM.add\n\
   \declare infixl (+) 5\n\
   \\n\
   \type pq : ty = | P int int | Q int int int\n\
   \\n\
   \sig patternMatch : pq -> int\n\
   \let patternMatch (P x y) = x + y\n\
   \let patternMatch (Q x y z) = x + y + z\n\
   \\n\
   \sig main : int\n\
   \let main =\n\
     \patternMatch (P 1 2)"
   defLLVM
```

`defLLVM` itself is new code that I added to try to support using LLVM with the Easy Pipieline:

```haskell
-- @defLLVM@ gives us LLVM prelude
defLLVM :: Options LLVM.Prim.PrimTy LLVM.Prim.RawPrimVal
defLLVM =
  def
    { prelude =
        -- TODO: Avoid relative paths
        [ "../../stdlib/Prelude.ju",
          "../../stdlib/LLVM.ju"
        ],
      param = LLVM.Param.llvm,
      typeAgainst = LLVM.Prim.Set
    }
```

The same behavior occurs with `defMichelson` as well, though, which is that the `Right context <- contextifyDesugar byteString option` in `printTimeLapse` fails because `contextifyDesugar` returns a `Left`.  Adding a `traceShowM` to try to figure out where produces:

```
"contextifyReturn = Left (PassErr (UnknownSymbol (\"->\" :| [])))"
```

I'm not sure why it doesn't recognize the `->`.

**Comment by mariari** [comment]
Try adding `open Prelude` to the input, as `->` has no meaning on it's own.

**Comment by rokopt** [comment]
> Try adding `open Prelude` to the input, as `->` has no meaning on it's own.

Ah, thanks, that works!  The easy pipeline doesn't support `mod`, but for some reason I thought it didn't support `open` either.
