### ISSUE TITLE
Higher order functions are not working

### ISSUE THREAD

**Issue by systemf-frank** [anoma/juvix#980]
Take the basic higherorder function example as follows:
```haskell
mod HigherOrder where

open Prelude
open LLVM

sig higherorder : (int -> int) -> int
let higherorder f = f 10

sig g : int -> int
let g _ = 20

sig main : int
let main = higherorder g
```

When trying to typecheck the code, we are presented with an error:

```
$ stack run -- compile -b llvm higherorder.ju   /dev/stdout
"Error on toHR: Name "f" :| [] not in scope
    ( probably a bug in the elaborator from frontend )"
```

Interestingly the error that pops up is related to the temporary fix in https://github.com/anoma/juvix/pull/902.

**Comment by rokopt** [comment]
This morning I suggested that this bug might have a root cause related to #981 .  However, I think I was wrong -- I tried compiling `mod HigherOrder` with the tracing that I added for #981 , and none of it appeared.  Whatever's going wrong here appears to be in the `toHR` step of `typecheck'`, before we get to `toErased` (or even `toIR`).

**Comment by mariari** [comment]
We can make the example a bit more minimal with

```haskell
mod HigherOrder where

open Prelude

sig higher-order : (int -> int) -> int
let higher-order f = f 10

sig main : int
let main = higher-order 20
```

Namely it seems to fails on this function in the `toHR`

```haskell
-- | Get special signature from atom
getSpecialSig ::
  ( Show primTy,
    Show primVal,
    HasCoreSigs ext primTy primVal m,
    HasThrowFF ext primTy primVal m
  ) =>
  NameSymbol.Mod ->
  Sexp.T ->
  m (Maybe Special)
getSpecialSig q x
  | Just Sexp.A {atomName} <- Sexp.atomFromT x = getSpecialSig' q atomName
  where
    getSpecialSig' q x = do
      sig <- lookupSig (Just q) x
      case sig of
        Just (SpecialSig s) -> pure $ Just s
        Just _ -> pure Nothing
        Nothing ->
          traceShow "hit here" $
          throwFF $ WrongSigType x Nothing
getSpecialSig _ _ = pure Nothing

```

**Comment by mariari** [comment]
This can be solved by shoving the variable into scope. 

As we can see the signature of `getSpecialSig` returns `Nothing` in the case of a non special sig. Thus if we introduce `f` into scope then it should be fine.

**Comment by mariari** [comment]
#987 Solves this issue by adding the `Closure` Concept to the `toHR` Environment.

The underlying issue is that there was no way for the type code to know that `f` even exists at that point

**Comment by mariari** [comment]
This should now be resolved

**Comment by systemf-frank** [comment]
> #987 Solves this issue by adding the `Closure` Concept to the `toHR` Environment.
> 
> The underlying issue is that there was no way for the type code to know that `f` even exists at that point
> 
> The code now errors are Erasure.
> 
> ```haskell
> "finished Inline"
> [ "Error: TypecheckerError
>     ( WrongPrimTy
>         { primVal = LitInt 20
>         , primTy = PrimType
>             { getPrimType = PrimTy
>                 ( IntegerType
>                     { typeBits = 8 }
>                 ) :|
>                 [ PrimTy
>                     ( IntegerType
>                         { typeBits = 8 }
>                     )
>                 ]
>             }
>         }
>     ) on Term: Elim
>     ( App
>         ( Free
>             ( Global
>                 ( "Juvix-User" :| [ "higher-order" ] )
>             ) ()
>         )
>         ( Prim
>             ( LitInt 20 ) ()
>         ) ()
>     ) ()" ]
> *** Exception: Failure on erase step
> CallStack (from HasCallStack):
>   error, called at /home/katya/Documents/Work/repo/juvix/library/EasyPipeline/src/Easy.hs:515:7 in main:Easy
> λ> 
> ```

Just for reference: this error is thrown because the input program was ill-typed: `20` is not of type `int -> int`, so it obviously can't be applied to `higher-order`.
