### ISSUE TITLE
Pattern variables don't shadow globals (even when they're defined before the globals)

### ISSUE THREAD

**Issue by rokopt** [anoma/juvix#991]
# Description

In https://github.com/anoma/juvix/issues/975#issuecomment-913201732 I described how investigating #975 revealed that pattern variables currently don't shadow globals, so a pattern variable which has the same name as  global anywhere in the same module will be interpreted as a match on the value of that global.  For example, in the following code:

```ml
type functionTypeInConstructor :
  ty = FTIC_Left field | FTIC_Right field -> field

sig fticTestFunc : field -> field
let fticTestFunc x = x

sig fticTestTerm : functionTypeInConstructor
let fticTestTerm = FTIC_Right fticTestFunc

sig x : field
let x = 1

sig main : field
let main = let ftict = fticTestTerm in 0
```

The `x` in the definition of `fticTestFunc` (`let fticTestFunc x = x`) is interpreted as `1`, the value given to `x` by the later global declaration.  I don't think this is what we intend (I'd find it extremely surprising).

# Blocks

# Blocked by

**Comment by cwgoes** [comment]
No, that is definitely not what we intend.
